### ISSUE TITLE
error MSB4216: Could not run the "GenerateResource" task because MSBuild could not create or connect to a task host with runtime "CLR2" and architecture "x86". 

### ISSUE THREAD

**Issue by mbookham7** [Microsoft/dotnet-framework-docker#101]
When trying to compile my project using the image https://hub.docker.com/r/microsoft/dotnet-framework-build/ I get the following errors.

Build FAILED.

"C:\src\CCCF\CCCF.Client\CCCF\CCCF.csproj" (default target) (1) ->
"C:\src\Common\Microsoft.ApplicationBlocks\Microsoft.ApplicationBlocks.UIProcess\Microsoft.ApplicationBlocks.UIProcess.csproj" (default target) (3:2) ->
(CoreResGen target) ->
 C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(3009,5): error MSB4216: Could not run the "GenerateResource" task because MSBuild could not create or connect to a task host with runtime "CLR2" and architecture "x86".  Please ensure that (1) the requested runtime and/or architecture are available on the machine, and (2) that the required executable "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuildTaskHost.exe" exists and can be run. [C:\src\Common\Microsoft.ApplicationBlocks\Microsoft.ApplicationBlocks.UIProcess\Microsoft.ApplicationBlocks.UIProcess.csproj]
 C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(3027,7): error MSB4028: The "GenerateResource" task's outputs could not be retrieved from the "FilesWritten" parameter. Object does not match target type. [C:\src\Common\Microsoft.ApplicationBlocks\Microsoft.ApplicationBlocks.UIProcess\Microsoft.ApplicationBlocks.UIProcess.csproj]

"C:\src\CCCF\CCCF.Client\CCCF\CCCF.csproj" (default target) (1) ->
"C:\src\Common\TaxTools.Common\TaxTools.Common.csproj" (default target) (4:2) ->
 C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(3009,5): error MSB4216: Could not run the "GenerateResource" task because MSBuild could not create or connect to a task host with runtime "CLR2" and architecture "x86".  Please ensure that (1) the requested runtime and/or architecture are available on the machine, and (2) that the required executable "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuildTaskHost.exe" exists and can be run. [C:\src\Common\TaxTools.Common\TaxTools.Common.csproj]
 C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(3027,7): error MSB4028: The "GenerateResource" task's outputs could not be retrieved from the "FilesWritten" parameter. Object does not match target type. [C:\src\Common\TaxTools.Common\TaxTools.Common.csproj]

When I run the same command from my laptop I do not have an issue. This is a .Net 3.5 application

**Comment by ravimeda** [comment]
Please could you provide more details about your app?

- Which image (version 1709 or ltsc2016) is being used?
- Is this a WPF app?

**Comment by mbookham7** [comment]
This is am in house developed ASP.net application written in .Net 3.5. The image I have been using for the build agent is dotnet-framework-build:3.5-windowsservercore-ltsc2016. The solution is composed of two projects one delivers the UI component (webpages) the other a web-service that delivers the business logic.

**Comment by MichaelSimons** [comment]
@mbookham7 - The microsoft/dotnet-framework-build images currently don't support building web projects.

**Comment by MichaelSimons** [comment]
Support for this is being tracked with https://github.com/Microsoft/dotnet-framework-docker/issues/103
