### ISSUE TITLE
Add support for building ASP.NET applications with Docker

### ISSUE THREAD

**Issue by MichaelSimons** [Microsoft/dotnet-framework-docker#103]
@MichaelSimons commented on [Wed Nov 01 2017](https://github.com/Microsoft/aspnet-docker/issues/63)

Microsoft should produce Docker images that can be utilized to build ASP.NET applications.

---

@MichaelSimons commented on [Wed Nov 01 2017](https://github.com/Microsoft/aspnet-docker/issues/63#issuecomment-341181173)

Depends on https://github.com/Microsoft/dotnet-framework-docker/issues/38

---

@juliolima86 commented on [Thu Mar 01 2018](https://github.com/Microsoft/aspnet-docker/issues/63#issuecomment-369745989)

Now depends on Microsoft/dotnet-framework-docker#37
I'm expecting this image to build asp.net framework and modernize then.

**Comment by jrob** [comment]
Is there a projected timeline for implementation? I am attempting to get my application building in       microsoft/dotnet-framework-build:3.5 but I am facing the same problem as #91. I would like to avoid putting a stop gap in place to get it working.

**Comment by dazinator** [comment]
To echo @jrob  - it would be nice to know a rough timeline as to when we could expect to build asp.net 3.5 web applications within a docker container?

**Comment by dazinator** [comment]
The specific problem I am facing with building asp.net 3.5 web applications is tools like `lc.exe` and `al.exe` aren't found during the build.

**Comment by jsturtevant** [comment]
@dazinator  looks like the PR for this is close: https://github.com/Microsoft/dotnet-framework-docker/pull/89#issuecomment-389233391

**Comment by dazinator** [comment]
@jsturtevant  - thanks that PR does solve some issues, but beware if you use RESX files you may still encounter this one: #154

**Comment by MichaelSimons** [comment]
This was resolved with #89
