### ISSUE TITLE
Include signtool.exe to dotnet-framework-build

### ISSUE THREAD

**Issue by dnperfors** [Microsoft/dotnet-framework-docker#107]
We are using a custom docker image for our CI build. But keeping that image up to date is rather annoying (we have a lot of problems installing VS2017) so I am looking to the dotnet-framework-build as an alternative.
Would it be possible to include signtool.exe to this image so that we can digitally sign our builds? According to [this](https://docs.microsoft.com/en-us/dotnet/framework/tools/) page, signtool is a dotnet framework tool, although it is only part of the windows sdk as far as I know...

**Comment by MichaelSimons** [comment]
Yes - It would make sense to add it to the image.  I will investigate how it can be easily acquired without bringing a bunch of unwanted baggage.

**Comment by hendrakwong** [comment]
I also have similar problem with my project that uses third party components with licenses.lcx file. My CI build failed due to the missing lc.exe. 

Here's the error log:
> C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(3089,5): error MSB3086: Task could not find "lc.exe" using the SdkToolsPath "" or the registry key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.7.1\WinSDK-NetFx40Tools-x86". Make sure the SdkToolsPath is set and the tool exists in the correct processor specific location under the SdkToolsPath and that the Microsoft Windows SDK is installed

**Comment by onovotny** [comment]
As a shameless plug, for CI code signing, I would recommend using my code signing service here:
https://github.com/onovotny/SignService

It can be deployed to your Azure environment and handles Authenticode, VSIX, NuGet, and ClickOnce code signing. It also means you do not have to have a pfx file anywhere near your build agent as the certificates reside in Key Vault's HSM. 

Happy to help get it configured if you run into any issues. As a reference, the .NET Foundation is using this for their member projects.

**Comment by jmezach** [comment]
Actually, there are a couple of other tools that I would like to see inside the container, such as resgen.exe and al.exe. It probably makes sense to have the Windows SDK inside the container as well, although that might significantly increase its size.

**Comment by startin148** [comment]
Any word on this? I'm running into the same issue when trying to run msbuild in docker. 

`C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(3624,5): error MSB3086: Task could not find "al.exe" using t
he SdkToolsPath "" or the registry key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.7.1\WinSDK-NetFx40Tools-x86". Make sure the SdkToolsPath is set and the tool e
xists in the correct processor specific location under the SdkToolsPath and that the Microsoft Windows SDK is installed [C:\sprocket\Framework\ODATech.Framework\ODATech.Framework.csp
roj]`

**Comment by dazinator** [comment]
Experiencing same problem as @startin148 
I have installed the vs_buidtools.exe with `-all` as per the docs. Are tools like `lc.exe` and `al.exe` not included in the installation? Or are they installed somewhere else and we need to set `SdkToolsPath` or something?

**Comment by onovotny** [comment]
Not a direct solution to this, but I would strongly encourage anyone who needs `signtool.exe` in a build to consider setting up an instance of a code signing service instead:
https://github.com/onovotny/SignService

It's really easy and far more secure as the certificates never leave Key Vault's HSM. Signtool is not required on the build agent for this to work either.

**Comment by jmezach** [comment]
In fact, I have already created a PR #121 to include the .NET Framework SDK into the build image. Hasn't been merged yet though, but I still think it makes sense to have this included in the build image since it's part of the SDK.

**Comment by startin148** [comment]
It would seem that when using
`FROM microsoft/dotnet-framework:4.7.1`
nuget is not longer a recognized command. When running 
`RUN nuget locals --clear all`
an error comes back stating
`[91m'dotnet' is not recognized as an internal or external command,
operable program or batch file.
docker : The command 'cmd /S /C dotnet nuget locals --clear all' returned a non-zero code: 1
At C:\_Development_git\buildTaylor.ps1:1 char:1
+ docker build --rm --no-cache -t sprocket:latest -f C:/_Development_gi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (The command 'cm...on-zero code: 1:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError`
