### ISSUE TITLE
_WPPCopyWebApplication error using microsoft/dotnet-framework-build:4.7.1 Docker image

### ISSUE THREAD

**Issue by vaughnmb** [Microsoft/dotnet-framework-docker#110]
I am running into the error below when trying to build an MVC application using the microsoft/dotnet-framework-build:4.7.1 Docker image.  Here is the msbuild command I am using

```
msbuild.exe /t:clean /target:Build;_WPPCopyWebApplication /p:Configuration=Release /p:OutputPath=out
```

What do I need to add to the image to fix this problem? Below is the error I am getting from the msbuild command

```
_WPPCopyWebApplication : The term '_WPPCopyWebApplication' is not recognized
as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is
correct and try again.
At line:1 char:111
+ ... e'; msbuild.exe /t:clean /target:Build;_WPPCopyWebApplication /p:Conf ...
+                                            ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (_WPPCopyWebApplication:String)
   [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by MichaelSimons** [comment]
The microsoft/dotnet-framework-docker images don't currently support ASP.NET scenarios (see https://github.com/Microsoft/dotnet-framework-docker/issues/103).  As a workaround to unblock yourself, you can add the changes included in https://github.com/Microsoft/dotnet-framework-docker/pull/89 within your own Dockerfile.

**Comment by vaughnmb** [comment]
I added those changes to my buiild file.

```
FROM microsoft/dotnet-framework-build:4.7.1 

# Install web targets
RUN Invoke-WebRequest -UseBasicParsing https://dotnetbinaries.blob.core.windows.net/dockerassets/MSBuild.Microsoft.VisualStudio.Web.targets.2017.12.zip -OutFile MSBuild.Microsoft.VisualStudio.Web.targets.zip;`
    Expand-Archive MSBuild.Microsoft.VisualStudio.Web.targets.zip -DestinationPath \"${Env:ProgramFiles(x86)}\Microsoft Visual Studio\2017\BuildTools\MSBuild\Microsoft\VisualStudio\v15.0\"; `
    Remove-Item -Force MSBuild.Microsoft.VisualStudio.Web.targets.zip

ENV ROSLYN_COMPILER_LOCATION "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Roslyn"
```

But it still doesn't know what _WPPCopyWebApplication is.  I am still getting this error
```
_WPPCopyWebApplication : The term '_WPPCopyWebApplication' is not recognized
as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is
correct and try again.
At line:1 char:111
+ ... e'; msbuild.exe /t:clean /target:Build;_WPPCopyWebApplication /p:Conf ...
+                                            ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (_WPPCopyWebApplication:String)
   [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException
```

What else do I need to do to get _WPPCopyWebApplication to work?

**Comment by MichaelSimons** [comment]
@vaughnmb - The microsoft/dotnet-framework-build Docker images have [set the SHELL to PowerShell](https://github.com/Microsoft/dotnet-framework-docker/blob/master/4.7.1-windowsservercore-1709/build/Dockerfile#L5).  The semicolon in your msbuild cmd is being interpreted by PowerShell as a statement separator rather than letting msbuild interpret it as a target list delimiter.  To fix this you can either separate the targets such as `/t:clean /t:Build /t:_CopyWebApplication` or use the semicolon escape character \` such as  /t:clean\`;Build\`;_CopyWebApplication

**Comment by MichaelSimons** [comment]
Closing - if there are anymore questions feel free to comment.
