### ISSUE TITLE
"no matching manifest for linux/amd64 in the manifest list entries" when pulling `microsoft/dotnet-framework:4.7`

### ISSUE THREAD

**Issue by stianlagstad** [Microsoft/dotnet-framework-docker#113]
Hopefully I haven't missed something completely obvious here. I'm on a Windows 10 (not pro) machine and have installed [Docker Toolbox](https://docs.docker.com/toolbox/toolbox_install_windows/). I open `Docker Quickstart Terminal` and type `docker pull microsoft/dotnet-framework:4.7`, and this is the output I see:
```
$ docker pull microsoft/dotnet-framework:4.7
4.7: Pulling from microsoft/dotnet-framework
no matching manifest for linux/amd64 in the manifest list entries
```

Should this work on Windows 10 (not pro) using the docker toolbox?

**Comment by MichaelSimons** [comment]
@stianlagstad - Docker Toolbox is a legacy product and does not support [multi-arch tags](https://github.com/dotnet/announcements/issues/14).  Your options are to either use [Docker for Windows](https://docs.docker.com/docker-for-windows/) or to use the non-manifest tags.  The non-manifest tags are the fully qualified tags such as `4.7-windowsservercore-ltsc2016`.

**Comment by MichaelSimons** [comment]
Closing as Docker Toolbox does not support multi-arch tags.  If there are questions, feel free to continue the conversation.

**Comment by shivashankar-awanti** [comment]
@MichaelSimons if im not using docker for windows i cannot pull images related to dotnet framework "docker pull microsoft/dotnet-framework:4.7"?
if im using minikube can i achieve this?
and can we get same thing done on azure? 

Thanks in advance.

**Comment by MichaelSimons** [comment]
The .NET Framework is only supported on Windows.  Windows images can only be run on a Windows Docker host.  If you are interested in Kubernetes, running Windows containers, and Azure then [Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/aks/intro-kubernetes) is what you should look into.
