### ISSUE TITLE
Fault bucket , type 0 Event Name: APPCRASH

### ISSUE THREAD

**Issue by erkkov2lja** [microsoft/dotnet-framework-docker#1132]
Issue: Fault bucket , type 0 Event Name: APPCRASH Response: Not available Cab Id: 0

Image: 4.7.2-20240213-windowsservercore-ltsc2019, 4.7.2-windowsservercore-ltsc2019, 4.7.2
The issue starts **right after 13 days of the container uptime.**

![image](https://github.com/microsoft/dotnet-framework-docker/assets/17758801/51cf296f-e33e-4fa1-9146-f20501f7819d)

![image](https://github.com/microsoft/dotnet-framework-docker/assets/17758801/af574169-bf4c-4339-965d-730995e98a2f)

Problem signature:
P1: svchost.exe_DiagTrack
P2: 10.0.17763.1
P3: b900eeff
P4: ntdll.dll
P5: 10.0.17763.4377
P6: ac56554b
P7: cfffffff
P8: 00000000000a3974
P9:
P10:

**Comment by erkkov2lja** [comment]
It is not limited only to this docker image, images with IIS has this issue.

**Comment by lbussell** [comment]
[Triage] @John-Hart, can you look into this? IIS container image is crashing after 13 days of uptime.

**Comment by John-Hart** [comment]
This doesn't look like it's an IIS issue.  I would recommend contacting Microsoft Support

**Comment by erkkov2lja** [comment]
Microsoft Support? I know that it is easy to redirect, Microsoft Support will not solve the issue. Who created this official docker image?

**Comment by richlander** [comment]
Are you running any Windows Services in your container?

**Comment by lbussell** [comment]
[Triage] Closing as not planned since there isn't enough info to diagnose the issue. @erkkov2lja feel free to re-open this issue if you have more info to share.
