### ISSUE TITLE
Docker short description of dotnet-framework-build confusion

### ISSUE THREAD

**Issue by bzuu** [Microsoft/dotnet-framework-docker#114]
The short description on the [Docker dotnet-framework-build repository ](https://hub.docker.com/r/microsoft/dotnet-framework-build/) reads:

> The official Docker images for building .NET Framework on Windows Server 2016 Server Core.

Which can be misinterpreted as this being images that are used by Microsoft to build .NET Framework itself rather than this being images that can be used to build your own .NET Framework based applications.

Therefore I would suggest to reword it as:

The official Docker images for building .NET Framework **applications** on Windows Server 2016 Server Core.

**Comment by MichaelSimons** [comment]
@bzuu - Thanks for logging this issue.

I changed the descriptions as follows:
* https://hub.docker.com/r/microsoft/dotnet-framework/ - `Official images for running .NET Framework applications on Windows Server Core`
* https://hub.docker.com/r/microsoft/dotnet-framework-build/ - `Official images for building .NET Framework applications on Windows Server Core`
