### ISSUE TITLE
Broken repo pages on Docker Hub

### ISSUE THREAD

**Issue by mthalman** [microsoft/dotnet-framework-docker#1150]
There's an issue with the repo pages on Docker Hub where pages using a certain URL format are no longer loading (404 result). This is pervasive across all Microsoft-owned repos.

Example broken URL: https://hub.docker.com/_/microsoft-dotnet-framework-sdk/
Example working URL: https://hub.docker.com/r/microsoft/dotnet-framework-sdk/

This is a regression as the currently broken URL format was previously working.

We're working with the MAR team which manages the Docker Hub content syndication to get this issue resolved: [IcM ticket](https://portal.microsofticm.com/imp/v3/incidents/incident/527764874/summary) (internal link).

**Comment by lbussell** [comment]
This appears to be fixed now.
