### ISSUE TITLE
Windows Defenders detects threat in image

### ISSUE THREAD

**Issue by Schums** [microsoft/dotnet-framework-docker#116]
Hello,
when trying to pull down and use the latest image **4.7.1-windowsservercore-ltsc2016** we are running into this:
`
PS C:\Windows\system32> docker pull microsoft/dotnet-framework:4.7.1-windowsservercore-ltsc2016
4.7.1-windowsservercore-ltsc2016: Pulling from microsoft/dotnet-framework
3889bb8d808b: Already exists
133e38d368dd: Pull complete
cda823bc6d27: Extracting [==================================================>]  360.1MB/360.1MB
bc848a7c134f: Download complete
2a7a6140868c: Download complete
failed to register layer: re-exec error: exit status 1: output: time="2018-04-06T16:15:23+02:00" level=error msg="hcsshi
m::ImportLayer failed in Win32: Der Vorgang konnte nicht erfolgreich abgeschlossen werden, da die Datei einen Virus oder
 möglicherweise unerwünschte Software enthält. (0xe1) layerId=\\\\?\\C:\\ProgramData\\docker\\windowsfilter\\4db90ad516f
f4d23f3f5dc5e793ba4e42dc87c8027337831965ed42e09e3d4ea flavour=1 folder=C:\\Windows\\TEMP\\hcs997842119"
hcsshim::ImportLayer failed in Win32: Der Vorgang konnte nicht erfolgreich abgeschlossen werden, da die Datei einen Viru
s oder möglicherweise unerwünschte Software enthält. (0xe1) layerId=\\?\C:\ProgramData\docker\windowsfilter\4db90ad516ff
4d23f3f5dc5e793ba4e42dc87c8027337831965ed42e09e3d4ea flavour=1 folder=C:\Windows\TEMP\hcs997842119
`
The Windows Defender recognizes it as a threat (https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aScript%2fCloxer.A!cl&threatid=2147725998&enterprise=0). Although we are quite certain that it is a false positive, it is from our point of view reasonable to report this here and ask if it indeed a false positive.
The Windows Defender Antivirus definitions are as follows:
`
Version of Antivirus definitions: 1.265.150.0
`
`
Version of Spyware definitions:  1.265.150.0
`
![github_ticket](https://user-images.githubusercontent.com/33601756/38426287-8e291036-39b6-11e8-903b-8fa6fadd9a12.PNG)
Regards

**Comment by MichaelSimons** [comment]
@Schums, Is this still an issue for you?  If so please post this issue to the [Windows Containers forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers) as this is a general issue not specific to the .NET images.
