### ISSUE TITLE
`cg-detection` pipeline is failing due to incorrect pool usage 

### ISSUE THREAD

**Issue by lbussell** [microsoft/dotnet-framework-docker#1170]
Failing pipeline run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2534703&view=results

```
  ##[error]The pipeline is not valid. Could not find a pool with name $(default1ESInternalPoolName). The pool does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.
```

/cc @ellahathaway, perhaps something was missing from https://github.com/microsoft/dotnet-framework-docker/pull/1167?

**Comment by ellahathaway** [comment]
It looks like this pipeline isn't importing the common variables template where `default1ESInternalPoolName` is specified. I think that this pipeline should import the template and use the 1es official template too
