### ISSUE TITLE
aspnet:4.7.1-windowsservercore-ltsc2016 doesn't actually have dotnet 4.7.1 installed

### ISSUE THREAD

**Issue by Spotypop** [Microsoft/dotnet-framework-docker#119]
We are using microsoft/aspnet:4.7.1-windowsservercore-ltsc2016 image.
In last couple of days seems like some changes were made to the image and now it lacks dotnet 4.7.1

**Comment by MichaelSimons** [comment]
Issue moved to [Microsoft/aspnet-docker #96](https://github.com/Microsoft/aspnet-docker/issues/96) via [**ZenHub**](https://www.zenhub.com/)
