### ISSUE TITLE
Migrate WCF docker samples from dotnet-framework-docker-samples repro to this repro

### ISSUE THREAD

**Issue by Lxiamail** [Microsoft/dotnet-framework-docker#129]
Let's follow the same format as these [samples](https://github.com/Microsoft/dotnet-framework-docker/tree/master/samples).

**Comment by yujayee** [comment]
@MichaelSimons @richlander @Lxiamail  Are there any specific requirements or new format we need to follow when migrating WCF samples?

**Comment by yujayee** [comment]
Close this issue since the pr is merged.
