### ISSUE TITLE
Xcopy not working - 

### ISSUE THREAD

**Issue by ideabelleyra** [Microsoft/dotnet-framework-docker#132]
Hi, Could it be that xcopy is not working anymore? 

`PS C:\> xcopy`
`PS C:\> echo $LASTEXITCODE `
`-1073741511`
`PS C:\> xcopy -version`
`-1073741511`

Tested on latest dotnet-framework and dotnet-framework-build (Deprecated) images.

Heard of other people having the same issue and "fixed" it by using an older image.

`Host: Windows 2016 Server Datacenter`
`DockerEE: Docker version 17.06.2-ee-8, build 4e8ed51`

Thanks, 
Ignacio

**Comment by MichaelSimons** [comment]
@ideabelleyra - Can you provide the specific steps used to reproduce this?  I tried the following, which works as expected.

1. docker pull microsoft/dotnet-framework:latest
1. docker run --rm microsoft/dotnet-framework:latest xcopy /?

**Comment by ideabelleyra** [comment]
Hi Michael, thanks a lot for your help. 

Did command #2 provide any output? 

` C:\Users\Administrator> docker pull microsoft/dotnet-framework:latest`
`latest: Pulling from microsoft/dotnet-framework`
`Digest: sha256:9939fe883e17d61198733806dca6df4ae6bd562226ceb24627e39d09328aca1c`
`Status: Image is up to date for microsoft/dotnet-framework:latest`
`PS C:\Users\Administrator> docker run --rm microsoft/dotnet-framework:latest xcopy /?`
`PS C:\Users\Administrator>`

Specific steps used to reproduce the error: 
A) What I did was get into the container by running:  `docker exec -it <container_id> powershell`
B) Then I did run the xcopy command inside the container: `xcopy /?`
C) As it did not provide any output I did run `echo $LASTEXITCODE` in order to retrieve the "xcopy /?" command's exit code. I got `-1073741511` as exit code. 
Cannot even find what this error code number means in the web. 

Thanks,

**Comment by ideabelleyra** [comment]
Thank you, 

> When you run docker exec -it <container_id> powershell, what image is the container you are using based on?

docker inspect <container_id> shows:
```
"Image": "microsoft/dotnet-framework:latest",
```
and 
```
"Image": "sha256:023c98ee4c6b950c468e790e1febf1c4f0babd124f1079a2b66948eb904a2b01",
```

While docker ps shows: 

```
REPOSITORY                         TAG            IMAGE ID            CREATED             SIZE
microsoft/dotnet-framework         latest         023c98ee4c6b        10 days ago         12.6GB
```



> What happens when you run docker run --rm microsoft/windowsservercore:latest xcopy /??

It takes me back to the command prompt, and does not show any output at all:
`PS C:\Users\Administrator> docker run --rm microsoft/windowsservercore:latest xcopy /?
PS C:\Users\Administrator>`

> Can you include the output of docker info?

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 15
Server Version: 17.06.2-ee-8
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.447.amd64fre.rs1_release_inmarket.161102-0100)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 4GiB
Name: WIN-NF1EHB05SS5
ID: 5Q6K:LAIA:R4PV:DBKS:HA7M:RC5P:6LJC:OPVT:CYQW:MJ3Q:5AYI:Y7XR
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

It is strange

**Comment by MichaelSimons** [comment]
I presume you get a similar behavior (e.g. no std output appearing) when you run something like `docker run --rm microsoft/windowsservercore:latest dir`?  What happens if you try to run something interactive?

1. `docker run -it --rm microsoft/windowsservercore:latest`
2. `xcopy /?`

I'm not sure I am going to be much help on this one.  Something is different about your Docker environment that I can't put a finger on immediately.  We've shown this is not something specific to the `microsoft/dotnet-framework` images.  You might have better luck getting an answer on StackOverflow where the audience is much larger or logging an issue with [Docker](https://github.com/moby/moby/issues/)

Closing issue as this is not specific to microsoft/dotnet-framework.  Feel free to continue the conversation and post anything you find.

**Comment by ideabelleyra** [comment]
> docker run --rm microsoft/windowsservercore:latest dir

I get the following error: 
```
PS C:\Users\Administrator> docker run --rm microsoft/windowsservercore:latest dir
C:\Program Files\Docker\docker.exe: Error response from daemon:
container 44bd2da05093bc54cdce9a721a5faf398e086ce8bf4583366a31e220a0971311 
encountered an error during CreateProcess:
failure in a Windows system call:
The system cannot find the file specified. 
(0x2) extra info: {"ApplicationName":"","CommandLine":"dir","User":"","WorkingDirectory":
"C:\\","Environment":{},"EmulateConsole":false,"CreateStdInPipe":true,"CreateStdOutPipe":
true,"CreateStdErrPipe":true,
"ConsoleSize":[0,0]}.
PS C:\Users\Administrator>
```

>1. docker run -it --rm microsoft/windowsservercore:latest
2.xcopy /?

```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\>xcopy /?
C:\>
```

> MichaelSimons closed this 3 minutes ago

Thank you for your help, I understand.

**Comment by RenganathanV** [comment]
@ideabelleyra @MichaelSimons  I am facing similar issue. I am using base image as microsoft/windowsservercore. xcopy is returning the same error code (-1073741511). Any idea how to fix this ?

**Comment by Francommit** [comment]
Facing the same issue.

**Comment by MichaelSimons** [comment]
This is an issue to take up with the Windows base images.  Please post in [Windows Containers forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers).
