### ISSUE TITLE
Problem of setting Volume in Dockerfile

### ISSUE THREAD

**Issue by eightrivers** [Microsoft/dotnet-framework-docker#14]
Hi, 

I have one question about how to set Volume in Dockerfile. What we want to do is to map a folder in host to a folder(volume) in docker, so that the file written in docker can be accessed outside docker. We try kinds of formats, such as ".:\app", "[.:/app]", in Dockerfile, but seems it can not work correctly. 

The error message is : "**Unrecognised volume spec: invalid volume specification: '.:\app'**". 

Would you please let us know how to set the Volume of Dockerfile ? 

Thanks a lot!

**Comment by richlander** [comment]
@kendrahavens - can you help?

**Comment by kendrahavens** [comment]
Hi @eightrivers,

Looks like it can't find the volume you are mounting. Try using an absolute path for the host-src.

[The Docker doc on volumes](https://docs.docker.com/engine/reference/run/#volume-shared-filesystems) could help with this.

**Comment by kendrahavens** [comment]
Closing if no further discussion is needed here.
