### ISSUE TITLE
Tag 4.7.1-windowsservercore-ltsc2016 doesn't start with memory 4G

### ISSUE THREAD

**Issue by GerritSo** [Microsoft/dotnet-framework-docker#148]
If I run a new container without any memory limitation it starts successfully.
`docker run microsoft/dotnet-framework:4.7.1-windowsservercore-ltsc2016`
`Microsoft Windows [Version 10.0.14393]`
`(c) 2016 Microsoft Corporation. All rights reserved.`
`C:\>`

If I run a new container with --memory 4G it doesn't start and seems so be in an endless loop (I've stopped after waiting about an hour:
`docker run --memory 4G  microsoft/dotnet-framework:4.7.1-windowsservercore-ltsc2016`

So I try to start with --memory 3G and it starts as expected
`docker run --memory 3G  microsoft/dotnet-framework:4.7.1-windowsservercore-ltsc2016`
`Microsoft Windows [Version 10.0.14393]`
`(c) 2016 Microsoft Corporation. All rights reserved.`
`C:\>`

I'm running the latest Docker Version under Win 10 1703 (Build 15063.1088)

**Comment by MichaelSimons** [comment]
@GerritSo - I'm not able to reproduce this.  Can you include the output from `docker version` and `docker info`?  Thanks

**Comment by MichaelSimons** [comment]
The one thing I noticed that with your configuration is that your Docker service is running with the `Experimental` features enabled.  You might want to disable this and retry.  You should also verify this issue is not specific to microsoft/dotnet-framework.  Can you try `docker run --memory 4G microsoft/windowsservercore:ltsc2016`?

**Comment by GerritSo** [comment]
I've also tried `docker run --memory 4G microsoft/windowsservercore:ltsc2016` and also with `--memory 3G` and without `--memory` so I think this problem can be closed here and I'll open an issue for the windowsservercore
