### ISSUE TITLE
error MSB3086: Task could not find "sgen.exe" using the SdkToolsPath "" or the registry key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.7.1\WinSDK-NetFx40Tools-x86"

### ISSUE THREAD

**Issue by sgtobin** [Microsoft/dotnet-framework-docker#168]
Attempting to build project results in error...
error MSB3086: Task could not find "sgen.exe" using the SdkToolsPath "" or the registry key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.7.1\WinSDK-NetFx40Tools-x86"

Build command...
RUN ["msbuild.exe", "c:/source/istart/istart.csproj /p:Configuration=Release /p:DeployOnBuild=true /p:PublishUrl='/inetpub/wwwroot'"]

**Comment by ccrowhurstram** [comment]
My experience thus far is that the images produced for `dotnet-framework-docker:sdk` doesn't support anything more than basic builds.

For example, it does not support pre-compiling razor views. Also I found that the .net framework SDK is not installed.

Personally I gave up for the time being on using these images and created my own: [christianacca/dotnet-framework](https://github.com/christianacca/dockerfiles/blob/master/dotnet-framework-sdk/windowsservercore-1803/Dockerfile)

I created a sample project that uses this as a base image to build and publish: [christianacca/aspnetapp-sample](https://github.com/christianacca/docker-aspnet-sample)

However there are things that are not ideal with creating your own like I have done:
* the image is not [multi-platform](https://blog.docker.com/2017/11/multi-arch-all-the-things/)
* you have to keep this image up to date whenever it's base image is patched (microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-1803)
* the path to the SDK needs to hard coded in the csproj file (see [this example](https://github.com/christianacca/docker-aspnet-sample/blob/24fc12ee5c291ebdd40d93ce299fda791682c0ee/src/PartsUnlimited.Web/PartsUnlimited.Web.csproj#L247))

**Comment by dcormier** [comment]
This should be handled by #121.

**Comment by MichaelSimons** [comment]
Closing as sgen.exe was added as part of #169
