### ISSUE TITLE
csc.exe exits with 255

### ISSUE THREAD

**Issue by meringu** [Microsoft/dotnet-framework-docker#170]
## When

Running `C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe` in `microsoft/dotnet-framework-build:latest`. `csc.exe` allways seems to exit with 255 no matter what arguments I pass.

## Expected behaviour

```
PS C:\> C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe /?
Microsoft (R) Visual C# Compiler version 4.6.1586.0
for C# 5
Copyright (C) Microsoft Corporation. All rights reserved.

This compiler is provided as part of the Microsoft (R) .NET Framework, but only supports language versions up to C# 5, which is no longer the latest version. For compilers that support newer versions of the C# programming language, see http://go.microsoft.com/fwlink/?LinkID=533240

...
PS C:\> echo $LASTEXITCODE
0
```

## Actual behaviour

```
PS C:\> C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe /?
PS C:\> echo $LASTEXITCODE
255
```

**Comment by meringu** [comment]
I found another `csc.exe` that looks to work here:
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Roslyn\csc.exe
```
Should this location be added to the `PATH`? Otherwise I can get around this by using a `CSC` build target for `msbuild.exe`, which is on the `PATH`

**Comment by MichaelSimons** [comment]
@jaredpar - Can you provide guidance on this?

**Comment by jaredpar** [comment]
@meringu the issue description has some possibly conflicting information. Are you running the `csc.exe` instance under Framework or Framework64? Both are listed in the issue. 

@MichaelSimons my guidance would be: don't use that csc. It's in 100% service only mode at the moment and hasn't been updated since before I rejoined the C# team four years ago. The other one is the active csc that should be used.

**Comment by jaredpar** [comment]
I am though a bit curious as to why it's failing. If there is a dump for me to look at I'd be happy to take a look.

**Comment by MichaelSimons** [comment]
@meringu - is using `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Roslyn\csc.exe` acceptable to you?

@Jaredpar - Do you think we should be adding `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Roslyn` to the path in our SDK docker images?

**Comment by meringu** [comment]
Yes! I am happy using that csc.exe, I just had a bit of trouble finding it.

I can check which of the Framework or Framework64 error. I'm not sure how to provide a dump. It should be fairly easy to reproduce however, as they error no matter the arguments

**Comment by jaredpar** [comment]
@MichaelSimons 

>  Do you think we should be adding C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Roslyn to the path in our SDK docker images?

If the intent is to have a compiler then yes that is the right item to add.

**Comment by MichaelSimons** [comment]
It feels like adding the csc compiler to the path does not align the primary intent of the image.  The primary intent is more msbuild focused.  For csc scenarios, you would need to add it to the path yourself or reference it via the appropriate path.
