### ISSUE TITLE
WCF net.tcp with Transport security mode

### ISSUE THREAD

**Issue by fedemonte89** [Microsoft/dotnet-framework-docker#176]
Hi, I'm trying to use the WcfServiceConsoleApp project in a container turning on the security mode for net.tcp protocol. As a local app it works without any issue, inside the container no.

Do you know any Windows feature to install in order to use the Transport security?

The following is my app.config file:
`<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.2" />
  </startup>
  <system.serviceModel>
    <behaviors>
      <serviceBehaviors>
        <behavior name="">
          **<serviceMetadata httpGetEnabled="false" httpsGetEnabled="false" />**
          <serviceDebug includeExceptionDetailInFaults="false" />
        </behavior>
      </serviceBehaviors>
    </behaviors>
    <services>
      <service name="WcfServiceConsoleApp.Service1">
        
        <endpoint binding="netTcpBinding" contract="WcfServiceConsoleApp.IService1" bindingConfiguration="noSecurityBind"/>
        **<endpoint address="mex" binding="mexTcpBinding" contract="IMetadataExchange" />**
        <host>
          <baseAddresses>
            
            <add baseAddress="net.tcp://localhost:808/Service1.svc" />
          </baseAddresses>
        </host>
      </service>
    </services>
    <bindings>
      <netTcpBinding>
        <binding name="noSecurityBind" portSharingEnabled="false">
          **<security mode="Transport" />**
        </binding>
      </netTcpBinding>
    </bindings>
  </system.serviceModel>
</configuration>`

**Comment by MichaelSimons** [comment]
Moving to the wcf docker repo since it is WCF related.
