### ISSUE TITLE
docker hub images missing

### ISSUE THREAD

**Issue by chrishiestand** [Microsoft/dotnet-framework-docker#177]
`docker pull microsoft/dotnet-framework`

> Using default tag: latest
> latest: Pulling from microsoft/dotnet-framework
> no matching manifest for unknown in the manifest list entries

`docker pull microsoft/dotnet-framework:4.7.2-sdk`

> 4.7.2-sdk: Pulling from microsoft/dotnet-framework
> no matching manifest for unknown in the manifest list entries
> 

`docker pull microsoft/dotnet-framework:3.5-sdk`

> 3.5-sdk: Pulling from microsoft/dotnet-framework
> no matching manifest for unknown in the manifest list entries

**Comment by chrishiestand** [comment]
This could be a problem on the docker hub side? I'd imagine that any tag listed here https://hub.docker.com/r/microsoft/dotnet-framework/tags/ , as the above are, should be pullable by definition.

**Comment by chrishiestand** [comment]
Seems like this problem is caused because I'm running linux, not windows. I didn't realize that docker images don't always run on linux.

https://github.com/Microsoft/dotnet-framework-docker/issues/113

**Comment by kenneho** [comment]
I'm running Docker for Windows on my Windows 10 laptop, and got the same error message. The solution was to right click the Docker icon in the notification ares (bottom right corner of the desktop), and click "Switch to Windows containers".

**Comment by jeking3** [comment]
Not sure why this was closed - it's an awful way to error out and provides no reasonable explanation as to how to resolve it.

**Comment by MichaelSimons** [comment]
The original author closed the issue because he discovered what he did wrong.  Please follow up with the [Docker CLI](https://github.com/moby/moby/issues) on the behavior of this scenario - trying to pull a tag that doesn't support the platform you are pulling from.
