### ISSUE TITLE
Rerunning vs_buildtools.exe, vs_professional.exe is impossible without cleanup

### ISSUE THREAD

**Issue by daghb** [Microsoft/dotnet-framework-docker#180]
I am running vs_installer (vs_buildtools.exe etc) to add components to the stack already deployes in the image. However, the installation fails with errors like "Visual Studio Build Tools 2017 is already installed."

After running the cleanup tool `%programfiles(x86)%\Microsoft Visual Studio\Installer\resources\app\layout\InstallCleanup.exe` I am able to do my additional installs.

Perhaps something to look into?

**Comment by heaths** [comment]
From the logs, it appears you were using the `install` command verb, but to modify an existing installation of Visual Studio you need to use the `modify` command verb. See https://docs.microsoft.com/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2017#list-of-command-line-parameters.

**Comment by rakeshsinghranchi** [comment]
I could successfully add Azurebuildtools workload consuming microsoft/dotnet-framework:4.7.2-SDK image.
Here is my docker file : https://gist.githubusercontent.com/rakeshsinghranchi/f73bac2d328ddd3e06004c631492e117/raw/39d64332b8ff935ec88fcfdaf2b5bfd34a6887b5/gistfile1.txt

@daghb , if you are still blocked, please share your sample dockerfile that reproduces the issue ?

**Comment by MichaelSimons** [comment]
Per @heaths suggestion and @rakeshsinghranchi sample, the `modify` verb should be used.  Closing.

**Comment by gilescope** [comment]
I need an upsert :-) - will modify fail if there's not one already installed?

**Comment by heaths** [comment]
Yes, modify will fail if it doesn't exist. You can use https://github.com/Microsoft/vswhere (always installed to "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" if VS2017 or newer is installed) to see if there's already an instance, but if you're building a docker container from an existing base image, wouldn't you already know if there's one there?
