### ISSUE TITLE
Add a reference to this github repository in the description that ends up on docker hub

### ISSUE THREAD

**Issue by daghb** [Microsoft/dotnet-framework-docker#181]
When reading the docs in the Docker Hub repository at https://hub.docker.com/r/microsoft/dotnet-framework/, there is no link back to this backing github repository, a thing that would be greatly appreciated.

**Comment by daghb** [comment]
There IS a link to the issue list. Should be sufficient.

**Comment by MichaelSimons** [comment]
Additionally, every single Dockerfile link in the `Complete set of Tags` section points back to the github repo.
