### ISSUE TITLE
Add support for Windows Server 2019 

### ISSUE THREAD

**Issue by sixeyed** [Microsoft/dotnet-framework-docker#189]
The Windows Server Core Docker image is GA now  at `mcr.microsoft.com/windows/servercore:1809`. It already has .NET 4.7 installed, but an `sdk` image would be great to have (we already have them for .NET Core via [PR 719](https://github.com/dotnet/dotnet-docker/pull/719)).

**Comment by MichaelSimons** [comment]
Note the base OS images are currently not available.  See https://support.microsoft.com/en-us/help/4464619/windows-10-update-history.

**Comment by davidmatson** [comment]
@MichaelSimons - can you clarify regarding base OS image availability? I believe `mcr.microsoft.com/windows/servercore:1809` has been available for a couple of weeks now, separate from the Windows 10 rollout.

**Comment by davidmatson** [comment]
Or I guess that image get removed after it had initially been made available? I have it locally but `docker pull mcr.microsoft.com/windows/servercore:1809` is now failing with a not found error.

**Comment by MichaelSimons** [comment]
The base OS images were pulled and are no longer available.

**Comment by sixeyed** [comment]
@MichaelSimons can I ask if you got a working version of the 4.7.2 SDK on 1809 using the Dockerfiles in the `rs5` branch? I've tried building using a cached local copy of the base image, but the VS Build Tools don't install. I get a bunch of NGen errors, but [after removing those calls](https://github.com/sixeyed/dockerfiles-windows/blob/master/dotnet-framework-sdk/windowsservercore/1809/Dockerfile.old) VS installs without errors but there's no VS 2017 folder in Program Files (x86). [Also tried with Chocolatey](https://github.com/sixeyed/dockerfiles-windows/blob/master/dotnet-framework-sdk/windowsservercore/1809/Dockerfile) and I get the same result - no errors, but no VS 2017. Wondering if there's a missing Windows feature I need to enable?

**Comment by MichaelSimons** [comment]
@sixeyed - There is a compatibility issue between with 1809 OS images and the VS Installer.  The product teams are aware of the issue and a fix is forthcoming.

**Comment by sixeyed** [comment]
Thanks for the update @MichaelSimons - I'll stop trying for now :)

**Comment by Lars-Jakobsen-3Shape** [comment]
> @sixeyed - There is a compatibility issue between the1809 OS images and the VS Installer. The product teams are aware of the issue and a fix is forthcoming.

Is there a separate issue reported on this to follow? we ran into this exact same problem few weeks back.

Best regards
Lars Jakobsen

**Comment by MichaelSimons** [comment]
There is not an external issue you can follow because VS is not open source.

**Comment by pacoxu** [comment]
why I cannot pull the image ？

PS C:\Users\Administrator> docker pull mcr.microsoft.com/windows/servercore:1809
Error response from daemon: manifest for mcr.microsoft.com/windows/servercore:1809 not found

**Comment by biiiipy** [comment]
@pacoxu Images have been removed from registry because of Windows bugs in 1809 release. Wait for re-release in a week or two.
