### ISSUE TITLE
Clean up VS installer artifacts from SDK image

### ISSUE THREAD

**Issue by rakeshsinghranchi** [Microsoft/dotnet-framework-docker#191]
Visual Studio setup leaves behind files under %programdata%\Microsoft\VisualStudio\Packages that can be removed to further slim down the SDK image. 
Note : %programdata%\Microsoft\VisualStudio\Packages\_Instances is required by build process and shouldn't be removed.

**Comment by MichaelSimons** [comment]
As part of fixing this, please investigate if the Windows Event log can and should be cleaned up as well.  I noticed the other day that this adds 10's of MB to the image size.

**Comment by mthalman** [comment]
Fixed by #252
