### ISSUE TITLE
msbuild.exe / full dotnet SDK

### ISSUE THREAD

**Issue by alexellis** [Microsoft/dotnet-framework-docker#2]
Hi,

I'd like to write about CI with Windows Containers and msbuild.

Can you help me put together an image which could run msbuild / nuget and output DLLs etc?

Here are a couple of posts I'm thinking about bringing under CI in a tutorial:

Docker voting app converted to Windows containers + ASP.NET:
http://blog.alexellis.io/p/2bca0a86-6c72-4b36-a5d0-73dc58cf847a/

Getting started guide for IIS / Windows Containers + .NET

http://blog.alexellis.io/run-iis-asp-net-on-windows-10-with-docker/

**Comment by alexellis** [comment]
Potential Dockerfile here? Thoughts?

https://github.com/alexellis/aspnet-voteservice/blob/master/src/Dockerfile.build

**Comment by shirhatti** [comment]
@alexellis We are looking at publishing official "-onbuild" images on DockerHub similar to what we've done for [.NET Core already](https://hub.docker.com/r/microsoft/dotnet/tags/)

Your Dockerfile looks good for just building your application, however it might be worthwhile to say perhaps have IIS/IIS Express to run integration tests for a web application. We've haven't reached consensus on what we're putting in that image, but we definitely plan to address the CI scenario.

As a data point, here's another [Dockerfile](https://github.com/anthonychu/aspnet-4.x-docker-windows-container/blob/master/Dockerfile) I've seen out in the wild, so we realize you are not the only person with this question.

cc @staceyhaffner @glennc @richlander

**Comment by alexellis** [comment]
This is where I got - http://blog.alexellis.io/3-steps-to-msbuild-with-docker/

**Comment by masaeedu** [comment]
> We are looking at publishing official "-onbuild" images on DockerHub similar to what we've done for .NET Core already

Is this still in the roadmap?

**Comment by anushaande** [comment]
Hi Alexellis, I am working on a project where I have to set up CI workflow for .net applications using Docker containers. I refered your blog to understand how to use Docker containers to build and deploy .net applications. Thanks for your work. Now I am struggling for a container to perform unit tests after code build. I am new to .net using containers and I hope you can provide some help with this.

**Comment by alexellis** [comment]
Hi I'm glad you found the blog post useful. I'm not sure if this issue is the best forum to provide support, perhaps you could take it up with the .NET team at Microsoft or the .NET community forums?

Alex

**Comment by MichaelSimons** [comment]
Producing `onbuild` images is no longer something that we are considering.  The usage of `onbuild` images doesn't seem to have taken off.  Please refer to the [samples](https://github.com/Microsoft/dotnet-framework-docker/tree/master/samples) for our recommended usage patterns.
