### ISSUE TITLE
Unable to load the service index

### ISSUE THREAD

**Issue by LeonardAB** [Microsoft/dotnet-framework-docker#203]
when running `docker run microsoft/dotnet-framework-samples`  on powershell, it worked without any problem.
Then I cloned the source-code, went to `samples/dotnetapp` folder, then tried to build the image using `docker image build -t dotnet_local_test .`
at `Step 7/23: RUN dotnet restore`, this is the result that I got:

```
  Restoring packages for C:\app\dotnetapp\dotnetapp.csproj...
  Restoring packages for C:\app\tests\tests.csproj...
  Generating MSBuild file C:\app\dotnetapp\obj\dotnetapp.csproj.nuget.g.props.
  Generating MSBuild file C:\app\dotnetapp\obj\dotnetapp.csproj.nuget.g.targets.
  Restore completed in 136.08 ms for C:\app\dotnetapp\dotnetapp.csproj.
  Restoring packages for C:\app\utils\utils.csproj...
  Generating MSBuild file C:\app\utils\obj\utils.csproj.nuget.g.props.
  Generating MSBuild file C:\app\utils\obj\utils.csproj.nuget.g.targets.
  Restore completed in 719.71 ms for C:\app\utils\utils.csproj.
C:\Program Files\dotnet\sdk\2.1.500\NuGet.targets(114,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\app\dotnetapp.sln]
C:\Program Files\dotnet\sdk\2.1.500\NuGet.targets(114,5): error :   No connection could be made because the target machine actively refused it [C:\app\dotnetapp.sln]
The command 'powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; dotnet restore' returned a non-zero code: 1
```

context: Docker version 18.09.0, build 4d60db4, Win 10 Pro, behind corporate proxy, using CNTLM

Can anybody help? Thank you.

**Comment by MichaelSimons** [comment]
@LeonardAB - Have you verified your Docker environment has access to the internet?  If not try executing something like `docker run --rm mcr.microsoft.com/windows/servercore:1809 curl -SL --output index.json https://api.nuget.org/v3/index.json` to verify.

**Comment by LeonardAB** [comment]
@MichaelSimons Yup, docker could not access the internet from inside the container. I found out that the problem is the proxy setting in my CNTLM. I documented the problem and solution [here](https://stackoverflow.com/a/53551452/5122657) just in case somebody faces a similar problem.

**Comment by Dynom** [comment]
Hi,

I have a similar problem only it's the DNS:

It seems that the `RUN` statements in the Dockerfile don't have the "correct" network configuration. I can reproduce the problem with the following:
```
PS C:\> docker run --rm -it --dns=80.80.80.80 microsoft/dotnet-framework:4.7.2-sdk ping -4 -a -n 1 google.com

Pinging google.com [172.217.16.14] with 32 bytes of data:
Reply from 172.217.16.14: bytes=32 time=23ms TTL=125

Ping statistics for 172.217.16.14:
    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 23ms, Maximum = 23ms, Average = 23ms
```

And:
```
PS C:\> docker run --rm -it microsoft/dotnet-framework:4.7.2-sdk ping -4 -a -n 1 google.com

Ping request could not find host google.com. Please check the name and try again.
```

Or, within the container:
```
c:\Users\ContainerAdministrator\AppData\Roaming\NuGet>nslookup api.nuget.org
Server:  UnKnown
Address:  172.26.176.1

*** UnKnown can't find api.nuget.org: Server failed
```

```
nslookup api.nuget.org 80.80.80.80 # With explicit DNS server
Server:  UnKnown
Address:  80.80.80.80

Non-authoritative answer:
Name:    cs22.wpc.v0cdn.net
Address:  152.199.19.160
Aliases:  api.nuget.org
          nugetapiprod.trafficmanager.net
          az320820.vo.msecnd.net
```


I'm not sure what the problem is, I've not had this issue before (first time for me to running Docker on Windows, only experience with Linux and macOS). I'm running Windows (Windows Server 2016 Datacenter Evaluation Build 14393.rs1_release.161220-1747) in a VM.
