### ISSUE TITLE
Git is crashing microsoft/dotnet-framework:4.7.2-sdk container

### ISSUE THREAD

**Issue by mersadk** [Microsoft/dotnet-framework-docker#204]
Git doesn't work inside `microsoft/dotnet-framework:4.7.2-sdk` container. When I call it, it crashes container with following message:

> ERRO[0014] Error waiting for container: failed to shutdown container: container 241ab62f352890066ac8eae614087af2b8575afa06c1b810487a51f9e7dd5e0b encountered an error during Shutdown: failure in a Windows system call: The connection with the Virtual Machine hosting the container was closed. (0xc037010a)

It works fine with `microsoft/windowsservercore` container.

You can build test image with following Dockerfile:
```
FROM microsoft/dotnet-framework:4.7.2-sdk
#FROM microsoft/windowsservercore

SHELL [ "powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';" ]

ENV chocolateyUseWindowsCompression false

# Install Chocolatey
RUN powershell -Command "Invoke-WebRequest -Uri 'https://chocolatey.org/install.ps1' -OutFile 'install_chocolatey.ps1'"
RUN powershell -file .\install_chocolatey.ps1

# Install git
RUN choco install -y git -params "/GitAndUnixToolsOnPath"

CMD [ "powershell" ]
```
Build image with `docker build -t "git-crash" .` and run it with `docker run -it git-crash powershell`. To reproduce issue execute `git config --list`.

Someone else describes same issue at https://social.msdn.microsoft.com/Forums/azure/en-US/2ff654d5-0d28-40b1-9b05-47140b8693bc/container-shuts-down-unexpectedly-happens-to-be-from-8220git-config-8211list8221?forum=windowscontainers

I'm running Windows 10 Pro with following docker version

> Client: Docker Engine - Community
>  Version:           18.09.0
>  API version:       1.39
>  Go version:        go1.10.4
>  Git commit:        4d60db4
>  Built:             Wed Nov  7 00:47:51 2018
>  OS/Arch:           windows/amd64
>  Experimental:      false
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          18.09.0
>   API version:      1.39 (minimum version 1.24)
>   Go version:       go1.10.4
>   Git commit:       4d60db4
>   Built:            Wed Nov  7 00:56:41 2018
>   OS/Arch:          windows/amd64
>   Experimental:     true

**Comment by MichaelSimons** [comment]
@mersadk - Can you include the `docker history` output for your image that reproduces the problem?  You are using multi-arch tags therefore I can't determine which version of windowsservercore you are using.  I haven't been able to reproduce with any of the following.

```
FROM microsoft/windowsservercore:ltsc2016
FROM microsoft/dotnet-framework:4.7.2-sdk-windowsservercore-ltsc2016
FROM mcr.microsoft.com/windows/servercore:ltsc2019
FROM microsoft/dotnet-framework:4.7.2-sdk
FROM microsoft/dotnet-framework:4.7.2-sdk-windowsservercore-ltsc2019
```

**Comment by mersadk** [comment]
@MichaelSimons When I run `docker history git-crash` I get following output, not sure if this is what you need?
![docker-git-crash](https://user-images.githubusercontent.com/137991/49298456-c4a5da00-f4bd-11e8-90dd-47121e0c9f01.png)

**Comment by mersadk** [comment]
It appears this is a known issue.
https://github.com/docker/for-win/issues/262

**Comment by MichaelSimons** [comment]
Closing as this doesn't appear to be an issue specific to the microsoft/dotnet-framework images.
