### ISSUE TITLE
Wrong Tag Description: Multiple 'latest'

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [Microsoft/dotnet-framework-docker#209]
In https://github.com/Microsoft/dotnet-framework-docker/blob/master/README.md and thus https://hub.docker.com/r/microsoft/dotnet-framework
you mention a docker tag `latest` four times:
- `4.7.2-runtime-20181211-windowsservercore-ltsc2019, 4.7.2-runtime-windowsservercore-ltsc2019, 4.7.2-runtime, runtime, latest`
- `4.7.2-runtime-20181211-windowsservercore-1803, 4.7.2-runtime-windowsservercore-1803, 4.7.2-runtime, runtime, latest`
- `4.7.2-runtime-20181211-windowsservercore-1709, 4.7.2-runtime-windowsservercore-1709, 4.7.2-runtime, runtime, latest`
- `4.7.2-runtime-20181211-windowsservercore-ltsc2016, 4.7.2-runtime-windowsservercore-ltsc2016, 4.7.2-runtime, runtime, latest`

This is impossible (since it is the same repo?) and confusing. I would pull and check but those images are huge.

**Comment by MichaelSimons** [comment]
This is possible with the use of [multi-platform tags](https://github.com/Microsoft/dotnet-framework-docker/issues/32).  Windows containers have a [compatibility limitations](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility) between the host OS and container OS.  By utilizing multi-platform tags, users can pull a tag that will retrieve a compatible with the host OS.

**Comment by Mario-Hofstaetter** [comment]
Thanks @MichaelSimons , I already bookmarked the Container Version compatibility page but didn't know that.
"_retrieve a image compatible with the host OS_" << I guess that means the _**highest**_ compatible windows version?
It would probably be nice to add that info to the docs, there is no mention of "docker pull" there.
