### ISSUE TITLE
Provide better visibility creating ASP.NET apps in README

### ISSUE THREAD

**Issue by richlander** [Microsoft/dotnet-framework-docker#21]
The current README doesn't do a good job of directing readers how to create ASP.NET apps using the dotnet-framework Docker image. We need to fix that. 

At the very least, we should direct people to: https://github.com/Microsoft/dotnet-framework-docker-samples/tree/master/aspnetapp. I think we can do more than that.

/cc @kendrahavens, @glennc

**Comment by MichaelSimons** [comment]
This was addressed by the most recent samples refactoring - https://github.com/Microsoft/dotnet-framework-docker/issues/128
