### ISSUE TITLE
2019 images seems to be missing NGEN optimization

### ISSUE THREAD

**Issue by artisticcheese** [microsoft/dotnet-framework-docker#211]
Please see this announcement https://github.com/dotnet/announcements/issues/33
2019 Dockerfile missing all NGEN optimization stuff looks like.

**Comment by artisticcheese** [comment]
![image](https://user-images.githubusercontent.com/13176884/50579175-5a5bbe80-0e08-11e9-9b09-6a98d0c6b5f3.png)

**Comment by MichaelSimons** [comment]
@NikolaMilosavljevic - @dleeapho asked if you could take a look at this?  My initial look makes me suspicious this is an issue with both the 1809 and 1803 images.  I wonder if Windows isn't re-running ngen after applying the .net LCU.

**Comment by NikolaMilosavljevic** [comment]
Running 'ngen update' definitely fixes the issue. Following up with Windows owners to understand their imaging process.

**Comment by MichaelSimons** [comment]
Assigning to Matt to validate.  I see Windows has resolved the their infrastructure issue which is the supposed source of the underlying issue.

**Comment by mthalman** [comment]
@MichaelSimons - This doesn't seem to be resolved in the base image.

`docker run --rm mcr.microsoft.com/dotnet/framework/runtime:4.7.2-windowsservercore-1803 powershell -Command (Measure-Command { powershell -command exit }).TotalSeconds`

Result: `2.187819`

@NikolaMilosavljevic - What was the result of your follow-up with the Windows team?
