### ISSUE TITLE
Server Core 2019 and International Settings

### ISSUE THREAD

**Issue by sanguedemonstro** [Microsoft/dotnet-framework-docker#213]
I'm running Docker Desktop Community on Windows 10 Desktop
- Docker version: 18.09.0
- Windows 10 host version: 10.0.17763.195 - It's a Desktop, not a Server - pt-BR version
- Server Core 2016 version: 10.0.17134.469 - Running just fine
- Server Core 2019 version: 10.0.17763.134 - With language issue

Dockerfile is the same for both (2016 and 2019), except for base image:
- Server Core 2016:	`FROM microsoft/aspnet:4.7.2-windowsservercore-1803`
- Server Core 2019: `FROM mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-windowsservercore-ltsc2019`

### The problem
Our IIS Application make a call to an legacy Win32 .exe process, that Win32 .exe deal with scripts, but scripts are being truncated on Server Core 2019, only when scripts have pt-BR chars like â, ã, é, ç,...

### Diagnostic
**I'm not sure**, but "Language for non-Unicode programs" setting looks suspicious:
- Running container Server Core 2016, _I think_ that it reads (the setting) from Windows host machine, which is pt-BR.
- Running container Server Core 2019 (**probablly more isolated version**) it's not readding from Windows host machine.

I've tried to run [Set-WinSystemLocale](https://docs.microsoft.com/pt-br/powershell/module/internationalcmdlets/Set-WinSystemLocale?view=winserver2012-ps) on dockerfile but Server Core container ignore that setting. I also read about restart required, but that's doesn't make any sense when we are talking about containers, right?!

### Help!
- Does anyone know for sure from where, how and when Server Core 2019 container reads that settings? And how it differs from 2016?
- What is the right way to [set international settings](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/configure-international-settings-in-windows) on Server Core 2019 containers, ideally, without restart required?
- Does anyone changed successfully those settings on Server Core 2019 container, using dockerfile instructions?

**Comment by MichaelSimons** [comment]
This is related to Windows Server Core images which the .NET Framework images are based on.  You are going to get more/better help by posting this question to the [Windows Containers forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers).  

Regarding the following:

> Running container Server Core 2019 (probablly more isolated version) it's not reading from Windows host machine.

I think you may need to run container in process isolation (only windows server with compatible base image, see https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility). Then container inherits Language for non-Unicode programs setting from host machine.

**Comment by sanguedemonstro** [comment]
Hi, thanks!

I open a post at Windows Container forum. [Here](https://social.msdn.microsoft.com/Forums/en-US/30b3cd8f-3e09-41b9-9e45-5707b1f1228b/server-core-2019-and-international-settings?forum=windowscontainers) and [here](https://social.msdn.microsoft.com/Forums/en-US/windowscontainers/thread/6664f006-8947-4685-936e-bc7faef2825f/#8b3a9f5d-683e-4b57-978b-96100f4ff8d3).

About,
> I think you may need to run container in process isolation (only windows server with compatible base image, see https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility). Then container inherits Language for non-Unicode programs setting from host machine.

Well would be an temporary workaround, actually not for me cause windows desktop supports only hyperv isolation.

But if I understand the whole container thing right, and I'm saying cause I'm newbie: Then the least a container depends on host, better. Right?! I mean, ideally I don't have to worry about where my images will run, so more isolatation is better.

I've  described all attempts [here](https://github.com/sanguedemonstro/docker-playground/blob/master/langpack-on-servercore2019.md), but no success so far. Any idea will be welcome.

Thanks!

**Comment by sanguedemonstro** [comment]
Digging deeper on that, I ended up understanding that:
- At this moment, for Server Core 2019, you have to install [language pack by yourself](https://docs.microsoft.com/pt-br/windows-server/get-started-19/rel-notes-19).
- The way to do it, is [using lpksetup](https://support.microsoft.com/en-us/help/4466511/cannot-configure-language-pack-for-windows-server-2019).
- **But lpksetup.exe crashes when running on container.**


Finally, I've described step by step how to reproduce lpksetup.exe error on container, **producing crash report logs** that I've extracted from container. 
All [here](https://github.com/sanguedemonstro/docker-playground/issues/1#issuecomment-453078549), with extra details [here](https://github.com/sanguedemonstro/docker-playground/blob/master/langpack-on-servercore2019.md#why-am-i-playing-around-this-subject).

But I'm not able to understand logs or fix windows base image. And I can't open support ticket once I'm not MS Partner.

So if anyone could help I'm here to support.

Thanks!

**Comment by sanguedemonstro** [comment]
> But I'm not able to understand logs or fix windows base image. And I can't open support ticket once I'm not MS Partner.
> 
> So if anyone could help I'm here to support.

Well, I started opening a suggestion on Windows Server User Voice.

**So please, everybody, vote up [here](https://windowsserver.uservoice.com/forums/295047-general-feedback/suggestions/36491128-add-support-to-multi-language-server-core-2019-whe).**

and spread the word :)

**Comment by MichaelSimons** [comment]
Closing as this is issue is specific to the Windows base OS images.  @cwilhit - Can you provide and guidance/help?

**Comment by cwilhit** [comment]
Thanks Michael. And thanks @sanguedemonstro for opening the User voice feedback. We'll use that going forward.
