### ISSUE TITLE
SDK containers should always include 4.6.1 SDK

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/dotnet-framework-docker#214]
MSBuild 15 defines some properties that point to the 4.6.1 SDK even when a newer SDK is available. That means that some projects can fail to build in a container that has _only_ the 4.7.2 SDK installed.

This was originally reported by @steffen-wilke in https://github.com/Microsoft/msbuild/issues/4049#issuecomment-452307519. Thanks!

> I'm using the [microsoft/dotnet-framework:4.7.2-sdk-20181211-windowsservercore-ltsc2016](https://github.com/Microsoft/dotnet-framework-docker/blob/master/4.7.2/sdk/windowsservercore-ltsc2016/Dockerfile) Docker image as a base for our build containers.
> 
> And our build process resulted in the outcome:
> 
> ```
> > You should have .NET 4.7.2 SDK installed.
> > Can't create the satellite assembly dll.
> > .NET 4.7.2 framework tools not found. Make sure that .NET framework has been installed.
> > "AL.exe" file does not exist.
> ```
> 
> Installing **Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools** from the [vs_buildtools](https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2017) to the image fixed the issue for me. This seems to be the [Component](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2017) that also installs the .NET 4.6.1 SDK to the machine.
> 
> Edit: Installing only **Microsoft.Net.Component.4.6.1.SDK** also worked
> 
> While only building .NET 4.7.2 projects, out build servers also have to have .NET 4.6.1 SDK installed at the moment which is a bit inconvenient.
> 
> Another example of this problem is the usage of the **resgen.exe** while building our solutions which is being accessed from the path `C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\resgen.exe`.
> 
> Maybe the Microsoft .NET 4.7.2 SDK Docker Images should be extended with the required .NET 4.6.1 SDK by default.

**Comment by rainersigwald** [comment]
I'd be happy to send a PR to install 4.6.1 whenever 4.7.2 is being installed, but I have a couple of related questions:

* Is the size impact OK? _Many_ builds will work with just 4.7.2, but not all.
* Is there a reason that `Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools` isn't installed? I would expect that, since it's the most likely user-checkbox path, and probably drags in some additional things.

**Comment by MichaelSimons** [comment]
> Is the size impact OK? Many builds will work with just 4.7.2, but not all.
Yes it is very important - the SDK is already borderline unwieldy in size.  A Docker image that would support every scenario is a goal hear.  Can you tell us the size impact of adding `Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools`?

**Comment by rainersigwald** [comment]
> Can you tell us the size impact of adding `Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools`?

I don't know of a better way to tell than trying it and I don't currently have Docker installed on Windows, so no, sorry. It's nontrivial, because it needs a closure of packages and I don't know how that would change.

**Comment by chrishibler** [comment]
I'm hoping someone might be able to post an example of the workaround @steffen-wilke mentioned, installing Microsoft.VisualStudio.Workload.ManagedDesktop. I'm starting with mcr.microsoft.com/dotnet/framework/sdk:4.7.2 as a base image and adding:

ADD https://aka.m/vs/16/release/vs_buildtools.exe C:\\TEMP\\vs_buildtools.exe
RUN C:\TEMP\vs_buildtools.exe --quiet --wait --norestart --nocache --add Microsoft.VisualStudio.Workload.ManagedDesktop

Builds are still failing with  "AL.exe" file does not exist.
