### ISSUE TITLE
4.7.2 windowsservercore-ltsc2019 does not point to mcr.microsoft.com/windows/servercore:ltsc2019

### ISSUE THREAD

**Issue by timcools** [Microsoft/dotnet-framework-docker#216]
Both dockerfiles for sdk and runtime of windowsservercore-ltsc2019 still point to microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-ltsc2019 instead of mcr.microsoft.com/windows/servercore:ltsc2019

**Comment by MichaelSimons** [comment]
@timcools - Can you clarify what you mean?  Are you asking about hosting the microsoft/dotnet-framework on MCR?

**Comment by MichaelSimons** [comment]
Closing with the assumption this issue is asking about when the images will be available on mcr.microsoft.com.  Issue #223 is tracking the work to host the images on mcr.
