### ISSUE TITLE
Receiving runtime error in my .NET application because certain fonts are no longer included in the Windows Server Core 2019 base image

### ISSUE THREAD

**Issue by mchristensen80** [Microsoft/dotnet-framework-docker#217]
It appears that all of the windows fonts except lucon.ttf have been eliminated in the server core 2019 base images. My .NET application no longer runs using the latest microsoft/dotnet-framework:4.7.2-runtime. I receive the exception: System.InvalidOperationException: Cannot read the file for font: Arial 
I am using GrapeCity Active Reports 12 to generate a pdf. When I swap fonts in my Active Reports code to Lucida Console, the pdf will generate. If I specify 1803 as my base image, the application will work; however, this doesnt seem like a good long term solution.

Has anyone else run into a similar problem? 
Does anyone have a suggestion for registering the fonts? 

I have attempted several methods for registering the fonts:
http://code.kliu.org/misc/fontreg/
https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-windows-containers-custom-fonts
https://www.itprotoday.com/powershell/trick-installing-fonts-vbscript-or-powershell-script
None of these have worked for me.

**Comment by MichaelSimons** [comment]
I can confirm all of the fonts except I believe one have been removed from the server core 2019 base image.  Please post this to the [windows containers forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers) for guidance.  Closing as this issue isn't directly related to the microsoft/dotnet images.

**Comment by mchristensen80** [comment]
Thank you Michael. I have posted my question in the containers forum. https://social.msdn.microsoft.com/Forums/en-US/c2059e86-7651-47ad-a0f5-1230e87d6508

**Comment by TripleEmcoder** [comment]
I believe this issue should be reopened, as there does not seem to be any guidance on how to proceed after the font removal. The .NET Framework is widely used for business applications, and those often need to generate PDF reports, which is rather impossible without proper font support. What's the solution? Don't move to Windows Server 2019? Don't move to Docker? Separate report generation as microservice hosted on a good old manually managed server?

**Comment by MichaelSimons** [comment]
@TripleEmcoder - This is an issue with the base Windows image, you will get a better response by posting to the [windows containers forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers).  One alternative, would be to use the full Windows base image to host this report generation microservice.
