### ISSUE TITLE
How to send legacy application logs to default docker log?

### ISSUE THREAD

**Issue by sanguedemonstro** [Microsoft/dotnet-framework-docker#218]
Hi, 

So, I have one Windows Container with **various processes**, .NET and Win32 legacy applications.

## First scenario
Entry Point calls _my_configurator.exe_, who calls _first.exe_, who creates a pool of _second.exe_

## Second scenario
Entry Point calls _my_configurator.exe_, who calls _ServiceMonitor.exe_, who initialize my IIS ASP.NET Web Application, who creates a pool of _second.exe_ process

# Problem
I'm already using log4net appender to send all logs to elasticsearch, and it's all good.

**But, I need to send logs to default docker log too**, so datacenter operators can see logs the same way they do with linux containers, using portainer or any other tool.

# Question
**How random processes running inside Windows Container could write to default log output?**

Knowing how it works, then I can write a custom log4net appender.

Thanks!
JP

**Comment by MichaelSimons** [comment]
You might have better luck getting a good answer on [StackOverflow](https://stackoverflow.com/) where the audience is much larger.  Closing as this issue isn't directly related to the microsoft/dotnet image in question.
