### ISSUE TITLE
Are the Docker Hub repositories for .NET Framework image with `Verified Publisher` content?

### ISSUE THREAD

**Issue by bobuva** [Microsoft/dotnet-framework-docker#219]
In looking around for .NET Framework-based Docker images, I discovered that this repository has some great examples. But I've also seen that Microsoft has started moving official images from the "community" listing to the "Verified Publisher" category on Docker Hub (see https://cloudblogs.microsoft.com/opensource/2019/01/17/improved-discovery-experience-microsoft-containers-docker-hub/). Are the .NET Framework images in that category yet? If not, will they be at some time?

**Comment by MichaelSimons** [comment]
Yes this is something we are currently working on.  This work is being tracked with #223.
