### ISSUE TITLE
Enabling windows defender on windows server core.

### ISSUE THREAD

**Issue by CrazyTuna** [Microsoft/dotnet-framework-docker#222]
I have an existing Web API than scans files against windows defender on a windows 2016 VM (hosted on Azure). 
I'd like to use a windows container for web app and I am trying to migrate my existing app.

Using this image `microsoft/aspnet:4.7.2-windowsservercore-ltsc2016`, I have my app up and running but defender seems to be disable on this image.

How could I enable windows defender on the image ?

I've tried this:

    SHELL ["cmd", "/S", "/C"]
    RUN sc start WinDefend

But I received an access denied exception.

**Comment by MichaelSimons** [comment]
This is an issue that is specific to the windowsservercore OS base image that the aspnet image is based on.  Please post this to the [windows containers forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers).
