### ISSUE TITLE
Host images on mcr.microsoft.com

### ISSUE THREAD

**Issue by MichaelSimons** [Microsoft/dotnet-framework-docker#223]
Steve Lasker wrote a blog back in May titled [Microsoft syndicates container catalog ](https://azure.microsoft.com/en-us/blog/microsoft-syndicates-container-catalog/), describing how Microsoft will start serving container images from mcr.microsoft.com, the Microsoft Container Registry (MCR), and syndicating the content describing the container images with Docker Hub and Red Hat.

When this transition is done, the images on Docker Hub will remain and serviced as to not cause any disruption to existing users.  All existing images will be copied to MCR and new tags will only be added to MCR.

The following is a working proposal of the repo hierarchy for the entire .NET family.

mcr.microsoft.com/dotnet (dotnet landing repo - no images)
mcr.microsoft.com/dotnet/framework (full FX landing repo – no images)
mcr.microsoft.com/dotnet/framework/runtime
mcr.microsoft.com/dotnet/framework/sdk
mcr.microsoft.com/dotnet/framework/aspnet
mcr.microsoft.com/dotnet/framework/wcf
mcr.microsoft.com/dotnet/framework/samples
mcr.microsoft.com/dotnet/core (core landing repo – no images)
mcr.microsoft.com/dotnet/core/runtime
mcr.microsoft.com/dotnet/core/runtime-deps
mcr.microsoft.com/dotnet/core/aspnet
mcr.microsoft.com/dotnet/core/sdk
mcr.microsoft.com/dotnet/core/samples
mcr.microsoft.com/dotnet/core-nightly (core nightly landing repo – no images)
mcr.microsoft.com/dotnet/core-nightly/runtime
mcr.microsoft.com/dotnet/core-nightly/runtime-deps
mcr.microsoft.com/dotnet/core-nightly/aspnet
mcr.microsoft.com/dotnet/core-nightly/sdk

Related to https://github.com/dotnet/dotnet-docker/issues/745

**Comment by Dynom** [comment]
The host `mcr.microsoft.com` is currently not accepting connections on port 5000 ¯\_(ツ)_/¯
