### ISSUE TITLE
Could not resolve a service of type ‘System.Net.Http.HttpClient’ for the parameter ‘httpClient’ of method ‘Configure’ on type ‘MyProject.WindowsService.Startup 

### ISSUE THREAD

**Issue by ianpano** [Microsoft/dotnet-framework-docker#224]
This code runs fine outside docker, 

```
try
{       
    services.AddSingleton(new HttpClient(new HttpClientHandler { })
    {
        DefaultRequestHeaders ={
                    Authorization =
                    new AuthenticationHeaderValue("Bearer",this.JSONWebToken.Value)
                    }
    });
}
catch(Exception ex)
{
    Console.WriteLine($"Error in Startup.ConfigureServices() {ex.Message}");
}
```
but when I run inside docker, I get this error:

> Could not resolve a service of type ‘System.Net.Http.HttpClient’ for the parameter ‘httpClient’ of method ‘Configure’ on type ‘MyProject.WindowsService.Startup

My docker file looks like this:
FROM microsoft/aspnet:4.7.2-windowsservercore-ltsc2016
EXPOSE 50500
WORKDIR /WinService
COPY dotnet-sdk-2.2.104-win-x64.exe ./
RUN Start-Process ‘dotnet-sdk-2.2.104-win-x64.exe’ ‘/quiet’ -PassThru | Wait-Process;
COPY WindowsService/bin/Release/* ./
COPY WindowsService/launcher.bat .
ENTRYPOINT [“MyProject.WindowsService.exe”, “–consolemode=true”]

**Comment by MichaelSimons** [comment]
Issue moved to [Microsoft/aspnet-docker #169](https://github.com/Microsoft/aspnet-docker/issues/169) via [**ZenHub**](https://www.zenhub.com/)
