### ISSUE TITLE
Offer image for .NET 4.5

### ISSUE THREAD

**Issue by AArnott** [Microsoft/dotnet-framework-docker#24]
Since .NET 4.6x is an in-place update and Windows Server Core ships with that, no docker image exists (that I can find) with .NET 4.5.  For folks who are targeting .NET 4.5 and have light-up code to emulate .NET 4.6 behaviors, the only sure way of testing that is on a machine that does not have .NET 4.6 installed. 

Can we get a docker image that has .NET 4.5 instead of 4.6, please?

**Comment by richlander** [comment]
Great question.

Two challenges to that:

- .NET 4.5 is out of support. .NET 4.5.2 is in support so would be an option.
- Windows containers don't support this scenario since Windows Server 2016 contains .NET Framework 4.6.2. Neither .NET Framework or Windows containers enables us to "go backwards". We cannot provide an older .NET Framework in place of 4.6.2 or an older Windows Server container images than 2016. Everything about Windows containers is forward looking from the point of Windows Server 2016 and Windows 10.

**Comment by AArnott** [comment]
net452 would probably be fine. The main requirement for my own purposes is to *not* have net46+.

I was concerned that your second point would be made. 😢  What if we hacked it? You know...  took a servercore image and replaced .NET dll's with those delivered by net45x?

**Comment by richlander** [comment]
Sure. That could work. It obviously wouldn't be supported/endorsed/hosted but it could work well enough for testing (assuming that there are no Windows 10 app compat issues we worked around; I don't know).

You'd need a copy of 4.5.2 and a Dockerfile that pulled it all together.

**Comment by AArnott** [comment]
Just one more idea... is .NET Framework an optional component on Server Core? As in, could it be removed with a `dism` command or similar, perhaps? If so, we could do that in the dockerfile then install 4.5.x

**Comment by richlander** [comment]
That's an interesting q. It might be. You'd have to try.

**Comment by richlander** [comment]
I'm going to close this issue. There is no official product direction on this and no obvious guidance for me to give you. I gave you another Microsoft contact offline for you to brainstorm with on possible avenues to make this work for your scenario.

**Comment by Vittel** [comment]
i would vote for this. just trying to setup a ci with docker, and its not possible to compile our 4.5.2 projects 👎

**Comment by AArnott** [comment]
@vittel, it sounds like you want to vote for it, but you gave it a thumbs down, so I'm a bit confused.

Also, you don't need this to _compile_ 4.5.2 projects, since you can target net452 even with the net46 runtime on the box. You just need the net452 targeting pack installed. 
I need this because I want to run tests on the net452 *runtime*.

**Comment by AArnott** [comment]
@vittel, it sounds like you want to vote for it, but you gave it a thumbs down, so I'm a bit confused.

Also, you don't need this to _compile_ 4.5.2 projects, since you can target net452 even with the net46 runtime on the box. You just need the net452 targeting pack installed. 
I need this because I want to run tests on the net452 *runtime*.

**Comment by AArnott** [comment]
@vittel, it sounds like you want to vote for it, but you gave it a thumbs down, so I'm a bit confused.

Also, you don't need this to _compile_ 4.5.2 projects, since you can target net452 even with the net46 runtime on the box. You just need the net452 targeting pack installed. 
I need this because I want to run tests on the net452 *runtime*.

**Comment by Vittel** [comment]
Was a thumbs down for closing the ticket.
Also what you just wrote is absolutely correct as i had figured out earlier. My ci container is up and running :)

**Comment by richlander** [comment]
@Vittel, what @AArnott says is correct. You don't need his proposal for your needs. What would benefit you is: https://github.com/Microsoft/dotnet-framework-docker/pull/37. We intend to add a .NET Framework 4.5.2 targeting pack as part of that PR (or a later one).

**Comment by Vittel** [comment]
@richlander thanks for confirming. also: https://github.com/Microsoft/dotnet-framework-docker/issues/24#issuecomment-343008143 💃
