### ISSUE TITLE
Native images missing?

### ISSUE THREAD

**Issue by chrisvanderpennen** [Microsoft/dotnet-framework-docker#25]
While investigating why a PowerShell healthcheck script consisting solely of `iwr http://localhost/health -usebasic` took three seconds and a full CPU core to execute, I discovered the .NET 4.7 container doesn't seem to have valid native images for framework assemblies.  Running `ngen update` from inside the container built new images from mscorlib up, and reduced the script time to about 200ms.

Is it possible to have these either built into the base image, or background generated on container start?

**Comment by shirhatti** [comment]
ping @richlander

**Comment by shirhatti** [comment]
@jinhuafei
