### ISSUE TITLE
Can't pull any image 

### ISSUE THREAD

**Issue by ls-acwn** [microsoft/dotnet-framework-docker#282]
Hi!
I can't pull any image. Whatever I take as a tag, I get the same error. For example:

docker pull mcr.microsoft.com/dotnet/framework/sdk:4.8

4.8: Pulling from dotnet/framework/sdk
no matching manifest for unknown in the manifest list entries

docker pull mcr.microsoft.com/dotnet/framework/sdk:3.5

3.5: Pulling from dotnet/framework/sdk
no matching manifest for unknown in the manifest list entries

I am refering to the description at https://hub.docker.com/_/microsoft-dotnet-framework-sdk

Kind regards,
Alexander

**Comment by mthalman** [comment]
All of the .NET Framework images are Windows-only.  I suspect your Docker configuration is set to use Linux containers.  Make sure to set it Windows containers.  Please confirm whether this resolves your issue.

**Comment by ls-acwn** [comment]
Thank you for the headsup. I totally missed that point.

**Comment by MichaelSimons** [comment]
If you are looking for a version of .NET that is cross platform, checkout the [.NET Core images](https://hub.docker.com/_/microsoft-dotnet-core) (if you haven't already).

**Comment by carloswm85** [comment]
From system tray you switch between Linux, and Windows containers.

![image](https://github.com/microsoft/dotnet-framework-docker/assets/29048235/ad7bf9d9-0651-4ed7-9ff5-dd614568c6cc)
