### ISSUE TITLE
Refactor PR build pipeline to split build and tests into separate jobs

### ISSUE THREAD

**Issue by mthalman** [microsoft/dotnet-framework-docker#283]
Currently the PR build flow ends up executing both the building of dependent images and testing into the same job.  This was done due to not being able to make use of the secrets in order to connect to the ACR since the pipeline is publicly exposed.  There are some workarounds we can explore to resolve this though.

**Comment by MichaelSimons** [comment]
Issue moved to [dotnet/docker-tools #185](https://github.com/dotnet/docker-tools/issues/185) via [**ZenHub**](https://www.zenhub.com/)
