### ISSUE TITLE
C# program with C++ dll failed: ' Could not load file or assembly  "some C++".DLL or one of its dependencies. The specified module could not be found.'

### ISSUE THREAD

**Issue by Yullissa** [microsoft/dotnet-framework-docker#286]
If the target dll is a simple c++ dll, this problem can be solved by adding vcruntime140d.dll and ucrtbased.dll to the \bin or C:\windows\system32\ in docker. Since it is a common case that add C++ dll in C# program, so I suggest to add these two dll in the standard .net framework. Besides, if this problem still happens, you could choose depends.exe to find out the missing dependency. 

Use it in the cmd as 
"cmd.exe /c depends /c /ot:.\out.txt .\somec++.dll"

**Comment by MichaelSimons** [comment]
@Yullissa, thanks for logging an issue for this.  It is the first time support has been requested for this scenario.  It feels reasonable to require users to copy the dependent C++ assemblies.  Closing as won't fix at this time.
