### ISSUE TITLE
`host.docker.internal` is not accessible in Windows Server Core container.

### ISSUE THREAD

**Issue by stack247** [microsoft/dotnet-framework-docker#295]
## Issue

Using the following docker image, I'm not able to use `host.docker.internal` in any connection string (database or Azure Storage emulator).
* `mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-windowsservercore-ltsc2019`
* `mcr.microsoft.com/dotnet/framework/aspnet:4.8`

## Background

I have an ASP.Net MVC web application (.Net Framework 4.6) that I containerized using the above-mentioned image. This application access database and Azure Storage that are running in the host. The host is running Docker for Windows and using Windows containers.

The issue is when the application runs, it won't be able to connect to any service in the host. I use `host.docker.internal` in the configuration file.

However, I was able to ping `host.docker.internal`.

In a separate test, `host.docker.internal` is accessible from a .Net Core application, running in Linux container and using the following image
* mcr.microsoft.com/dotnet/core/sdk:2.2-stretch

## Expected Result

Should be able to use `host.docker.internal` in connection string of the application that's running in a Windows container.

## Error

![image](https://user-images.githubusercontent.com/5100717/59082638-b8aa3300-88b9-11e9-8ea8-355a44d83d3d.png)

Tracer Route result

![image](https://user-images.githubusercontent.com/5100717/59082768-4128d380-88ba-11e9-94c8-38e4ec556f7e.png)

Ping result

![image](https://user-images.githubusercontent.com/5100717/59082831-746b6280-88ba-11e9-8ed1-258097fab4b8.png)

## Other Configurations

Host machine: Windows 10
Docker Desktop for Windows, version 2.0.0.3
Docker is running Windows container.

`Dockerfile` file
```
FROM mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-windowsservercore-ltsc2019
ARG source
WORKDIR /inetpub/wwwroot
COPY ${source:-obj/Docker/publish} .
```

Firewall is turned off
![image](https://user-images.githubusercontent.com/5100717/59082948-ea6fc980-88ba-11e9-9d1e-7f3d41a2b768.png)

**Comment by mthalman** [comment]
Issue moved to [microsoft/aspnet-docker #184](https://github.com/microsoft/aspnet-docker/issues/184) via [**ZenHub**](https://www.zenhub.com/)
