### ISSUE TITLE
Cannot set ErrorActionPreference "$ErrorActionPreference = 'Stop'" in run when deriving from sdk:4.8-windowsservercore-ltsc2019

### ISSUE THREAD

**Issue by ggirard07** [microsoft/dotnet-framework-docker#298]
I am trying to use the samples from [Microsoft doc best practices](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/optimize-windows-dockerfile#group-related-actions),  but with the framework sdk base image instead. The docker build is successful but a powershell error is always outputted:

```powershell
Stop : The term 'Stop' is not recognized as the name of a cmdlet, function, 
script file, or operable program. Check the spelling of the name, or if a path
was included, verify that the path is correct and try again.
At line:1 char:1
+ Stop = Stop
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (Stop:String) [], CommandNotFoun
   dException
    + FullyQualifiedErrorId : CommandNotFoundException
```
When using the default image from the example (mcr.microsoft.com/windows/servercore:ltsc2019), I do not have any error outputted to the logs of the docker build command.

Here is the content of the Dockerfile producing the described behavior:
```dockerfile
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019

RUN powershell.exe -Command \
  $ErrorActionPreference = 'Continue'; \
  Invoke-WebRequest https://www.python.org/ftp/python/3.5.1/python-3.5.1.exe -OutFile c:\python-3.5.1.exe ; \
  Start-Process c:\python-3.5.1.exe -ArgumentList '/quiet InstallAllUsers=1 PrependPath=1' -Wait ; \
  Remove-Item c:\python-3.5.1.exe -Force
```
And the command used for the docker build:
```cmd
docker build --rm -f "Dockerfile" -t test:latest .
```

I am using Docker Desktop 2.0.0.3 in Windows container mode (without experimental features) on Windows 10 Pro 1903 (Build 18362.116).

**Comment by mthalman** [comment]
The default shell in the Windows .NET SDK images is already PowerShell.  So you don't need to run powershell.exe.  You should just be able to use this:
```
RUN $ErrorActionPreference = 'Continue'; \
    Invoke-WebRequest https://www.python.org/ftp/python/3.5.1/python-3.5.1.exe -OutFile c:\python-3.5.1.exe ; \
    Start-Process c:\python-3.5.1.exe -ArgumentList '/quiet InstallAllUsers=1 PrependPath=1' -Wait ; \
    Remove-Item c:\python-3.5.1.exe -Force
```

Note that setting ErrorActionPreference is only needed if you don't want the default value of Stop.

If that fixes your issue, please go ahead and close this issue.

**Comment by ggirard07** [comment]
@mthalman It indeed fixed my issue. Sorry about this, I wasn't aware about powershell being the default shell in dotnet sdk images.

Regarding the ErrorActionPreference set to Continue and not Stop, it was a copy/paste isse on my side when I created this issue.

Thanks a lot!
