### ISSUE TITLE
ltsc2016 image contains Windows Server 2019

### ISSUE THREAD

**Issue by daghb** [microsoft/dotnet-framework-docker#306]
When i base my image using
`FROM mcr.microsoft.com/dotnet/framework/sdk:4.7.2-windowsservercore-ltsc2016`
in my Dockerfile, reporting the OS version from the running container based on this image returns these values

```
> [System.Environment]::OSVersion.Version
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17763  0
```

```
> (Get-WmiObject -class Win32_OperatingSystem).Caption
Microsoft Windows Server 2019 Standard
```

Image LastUpdatedTime: 06/12/2019

Is this because Windows Server 2016 core images are being discontinued?

**Comment by yamac-kurtulus** [comment]
Seems like you can still use `mcr.microsoft.com/dotnet/core/runtime:2.1-nanoserver-sac2016` for WS2016 images. Not sure if you still need this, but oh well...
