### ISSUE TITLE
Provide documentation on image contents

### ISSUE THREAD

**Issue by mthalman** [microsoft/dotnet-framework-docker#312]
There should be a readme that provides clear documentation on what software is provided in the images, most importantly for the SDK images since they contain a variety of things.  We shouldn't require that consumers locate and parse through a Dockerfile to have an understanding of what they're getting.  As example, the contents of the VMs for Azure DevOps agents are nicely documented: https://github.com/microsoft/azure-pipelines-image-generation#image-contents.

**Comment by MichaelSimons** [comment]
Closing as the basic content is described in the readme which is available in GitHub and DockerHub.  A good example is the SDK readme - https://hub.docker.com/_/microsoft-dotnet-framework-sdk/
