### ISSUE TITLE
Install VSTest.Console.exe

### ISSUE THREAD

**Issue by zhangxin511** [microsoft/dotnet-framework-docker#314]
Given the word

> It is optimized for performance and is used in place of MSTest.exe in Visual Studio 2012 or later versions

from https://docs.microsoft.com/en-us/previous-versions/jj155800(v=vs.140), could the VSTest.Console.exe included into the images? The image contains MSTest.exe, but this executable won't pickup the MSTestV2 tests: https://github.com/Microsoft/vstest/issues/1213#issuecomment-395303692.

Thanks,
Xin

**Comment by MichaelSimons** [comment]
`VSTest.Console.exe` is currently included in the SDK images.  Run `docker run --rm mcr.microsoft.com/dotnet/framework/sdk:4.8 where vstest.console.exe` to find where it is installed.

Closing - feel free to continue discussing.

**Comment by zhangxin511** [comment]
Thanks @MichaelSimons
