### ISSUE TITLE
error MSB6006: "csc.exe" exited with code -2146232576 with netfx471 image

### ISSUE THREAD

**Issue by WeihanLi** [microsoft/dotnet-framework-docker#315]
I'm using  `mcr.microsoft.com/dotnet/framework/sdk:4.7.1` to build a aspnet web project, when I build the project I got the error below

**Error I got**

> C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(59,5):
 error MSB6006: "csc.exe" exited with code -2146232576

**Dockerfile I used**

``` dockerfile
FROM mcr.microsoft.com/dotnet/framework/sdk:4.7.1 AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln ./
COPY AspNetWebTest/*.csproj ./AspNetWebTest/
COPY AspNetWebTest/*.config ./AspNetWebTest/

RUN nuget restore

# copy everything else and build app
COPY . .

WORKDIR /app/AspNetWebTest/
RUN msbuild /p:Configuration=Release


FROM microsoft/iis:windowsservercore-ltsc2016

RUN powershell -NoProfile -Command Remove-Item -Recurse C:\inetpub\wwwroot\*

WORKDIR /inetpub/wwwroot

COPY --from=build /app/AspNetWebTest/. ./
```

**Comment by MichaelSimons** [comment]
@WeihanLi - It is difficult to know the source of the error without having the ability to see the source of what you are building.  Have you tried simplifying the project to identify the source of the error?

You might have better luck getting a good answer on [StackOverflow](https://stackoverflow.com/) where the audience is much larger.

**Comment by WeihanLi** [comment]
I'd searched on google and stackoverflow, but found no useful answers.

maybe this's a issue with roslyn, found a similar issue here <https://github.com/dotnet/roslyn/issues/37098>

it can build with `msbuild` success locally, and the msbuild version is completely the same with the `msbuild` in docker image.

a sample project here, I'd updated the dockerfile to use dotnet cli tools

[WebApplication1.zip](https://github.com/microsoft/dotnet-framework-docker/files/3395565/WebApplication1.zip)

**Comment by mthalman** [comment]
@WeihanLi - I extracted the WebApplication1.zip file you provided and was able to build it just fine with the command `docker build --pull -t webapp .`.  Try to use the `--pull` option to ensure that you're using the latest base image.

**Comment by WeihanLi** [comment]
Hi @mthalman , I've updated the Dockerfile in the demo, you could use the dockerfile below for test

``` dockerfile
FROM mcr.microsoft.com/dotnet/framework/sdk:4.7.1 AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln ./
COPY AspNetWebTest/*.csproj ./AspNetWebTest/
COPY AspNetWebTest/*.config ./AspNetWebTest/

RUN nuget restore

# copy everything else and build app
COPY . .

WORKDIR /app/AspNetWebTest/
RUN msbuild /p:Configuration=Release


FROM microsoft/iis:windowsservercore-ltsc2016

RUN powershell -NoProfile -Command Remove-Item -Recurse C:\inetpub\wwwroot\*

WORKDIR /inetpub/wwwroot

COPY --from=build /app/AspNetWebTest/. ./
```

it works with dotnetcore sdk, but not with msbuild, the demo supplied had changed to use dotnetcore sdk to build the project

**Comment by mthalman** [comment]
Thanks I can repro now and have identified the problem.  Your project requires the `Microsoft.Net.Compilers` package.  Add this:
```
<PackageReference Include="Microsoft.Net.Compilers" Version="2.4.0" />
```

That should resolve your problem so I'm closing the issue.  If you're still having issues, feel free to reopen it.
