### ISSUE TITLE
Suggestion: would you please add `choco` into the base image?

### ISSUE THREAD

**Issue by WeihanLi** [microsoft/dotnet-framework-docker#320]
with chocolatey  ,we could install the software/package/module much more easily, for example we could install iis dotnetcore windows hosting package just a command `choco install dotnetcore-windowshosting -y`

**Comment by MichaelSimons** [comment]
@WeihanLi - Can you clarify which images you would like Chocolatey added to?  Are you asking for it to be added to the `sdk`, `runtime`, or both?

**Comment by WeihanLi** [comment]
I'm using `mcr.microsoft.com/dotnet/framework/aspnet:4.8` for runtime image, and I installed on this image for now, but maybe both.
It seemed the dockerfile now download the sdk from microsoft directly, maybe we could use choco install specific sdk? I'm not sure which is better, just a mind.

**Comment by MichaelSimons** [comment]
Adding chocolatey is not something we are considering at this time.  We receive feedback consistently that the runtime related images are too large.  Adding components such as chocolatey are only going to make this problem worse.  It is very easy to install in a derived image.

**Comment by WeihanLi** [comment]
Yeah, thanks for your reply @MichaelSimons
