### ISSUE TITLE
Apply standard formatting convention to WCF dockerfiles.

### ISSUE THREAD

**Issue by StephenBonikowsky** [microsoft/dotnet-framework-docker#331]
For docker files merged via #318

The standard formatting convention used within Dockerfiles is the left align the Dockerfile instructions and indent multi-line content. This helps with readability.

**Comment by MichaelSimons** [comment]
Related to #333

**Comment by MichaelSimons** [comment]
@StephenBonikowsky - is this something that can be addressed for the Sept patch release?

**Comment by StephenBonikowsky** [comment]
I should be able to get this done, when does it have to be done by for the Sept patch?

**Comment by MichaelSimons** [comment]
Would be nice to have it available by the end of the week before (Friday Sept 6).
