### ISSUE TITLE
Remove SHELL lines from WCF docker files.

### ISSUE THREAD

**Issue by StephenBonikowsky** [microsoft/dotnet-framework-docker#332]
For docker files merged in #318

The SHELL is inherited from the base image so this is not necessary here.

**Comment by MichaelSimons** [comment]
@StephenBonikowsky - is this something that can be addressed for the Sept patch release?

**Comment by StephenBonikowsky** [comment]
Not sure if I can get to it in time, working on some high pri work for .NetCore 3.0 release.
