### ISSUE TITLE
Update ASPNET docker files to the best practice guidelines.

### ISSUE THREAD

**Issue by StephenBonikowsky** [microsoft/dotnet-framework-docker#333]
Invoking powershell.exe for each cmd within the RUN instruction is not very efficient.

In addition, our normal convention for multi-command statements is to use double-ampersand && which will ensure that the entire call fails if any of the individual commands fail. By using a single ampersand & it will silently fail and continue to execute the next command. And each line after the initial command should be preceded by &&.

Example:
```
RUN command1 `
    && command2 `
    && command3
```

**Comment by MichaelSimons** [comment]
@StephenBonikowsky - is this something that can be addressed for the Sept patch release?

**Comment by StephenBonikowsky** [comment]
Not sure if I can get to it in time, working on some high pri work for .NetCore 3.0 release.
