### ISSUE TITLE
WCF with Https

### ISSUE THREAD

**Issue by aravindan545** [microsoft/dotnet-framework-docker#341]
how to enable the https , i tried by adding /enabledProtocols:"http,net.tcp,https" but no luck.

basically i'm try to host the windows container with https in Azure service fabric cluster.

please suggest how to achieve.

**Comment by HongGit** [comment]
@shirhatti can you please help out?

**Comment by HongGit** [comment]
@shirhatti ping!

**Comment by HongGit** [comment]
@aravindan545 is this still an issue for you?

This shouldn't be too different from turning on SSL for IIS, since http and net.tcp are already enabled in the WCF base image.

**Comment by aravindan545** [comment]
@HongGit i resolved by installing SSL on docker image level while building the windows docker image
