### ISSUE TITLE
Running wcfclient in a docker and the server outside the sample doesn't works

### ISSUE THREAD

**Issue by domenicocanavero** [microsoft/dotnet-framework-docker#345]
Hello,
I need to run a wcf server not in a docker and the wcf client in a docker.
I check this configuration with your example:
- The server runs on my PC as console
- Run the client in a container, set the env HOST to the ip address of my PC,
I have this exception: EndpointNotFoundException.
Both in a container is OK
Can you help to me to manage this configuration?
Thanks

**Comment by domenicocanavero** [comment]
Hello,
I use Docker Desktop and probably it's this the reason of the problem described above.
From docker doc:
https://docs.docker.com/docker-for-windows/networking/
.......
_Use cases and workarounds
There are two scenarios that the above limitations affect:

I WANT TO CONNECT FROM A CONTAINER TO A SERVICE ON THE HOST
The host has a changing IP address (or none if you have no network access). From 18.03 onwards our recommendation is to connect to the special DNS name host.docker.internal, which resolves to the internal IP address used by the host. This is for development purpose and will not work in a production environment outside of Docker Desktop for Windows.

The gateway is also reachable as gateway.docker.internal._
.....

I understood that there some limitations on Docker Desktop to connect from container to out,
but it's not clear to me the workaround suggested.

**Comment by HongGit** [comment]
@domenicocanavero This is an issue that is specific to the windowsservercore OS base image that the wcf image is based on. Please post this to the [windows containers forum](https://social.msdn.microsoft.com/forums/en-us/home?forum=windowscontainers).
