### ISSUE TITLE
Request: Allow configuration of virus scanning components in server core 2019 image

### ISSUE THREAD

**Issue by Sephizor** [microsoft/dotnet-framework-docker#347]
I am using the aspnet:4.7.2 image as a base for a large, complex C# .NET application and am running into issues with some false positives being flagged by virus scanning components when running the image in Azure Container Instances. The exception is "System.IO.IOException: Operation did not complete successfully because the file contains a virus or potentially unwanted software". This happens sometimes when extracting javascript files from a zip. I have spoken already with a Microsoft support representative via Azure Help + Support and was directed to create an issue here.

Since Windows Defender is not installed (and unable to be installed) in the server core 2019 image, there is no way to configure the virus scanning components. It does look like there are related "Windows Defender Advanced Threat Protection" components installed in the container but I cannot find a way to configure or remove these.

I would therefore like either the ability to disable WDATP (or any other related virus scanning components) or for the ability to install Windows Defender, even in a limited fashion, so that exclusion rules can be set up.

**Comment by StephenMolloy** [comment]
@shirhatti and @MichaelSimons  do you know any contact from Windows team?  should we transfer this to windows docker repo?

**Comment by MichaelSimons** [comment]
I apologize for the run-around but all support requests and general questions related to the base Windows images should be reported on the [Windows Containers forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers)

**Comment by Sephizor** [comment]
@MichaelSimons I actually posted this there as well a couple of weeks ago https://social.msdn.microsoft.com/Forums/en-US/7e3446b0-3b34-43b9-af26-d67ce71ce47e/how-can-i-disable-all-virusthreat-protection-in-a-server-core-2019-container?forum=windowscontainers

**Comment by MichaelSimons** [comment]
This issue is not tied to the .NET FX images.  It it specific to ACI and the Windows OS images.  Continue to pursue on the Windows Containers forum.  Closing.
