### ISSUE TITLE
windows server 1903 tags can't be pulled

### ISSUE THREAD

**Issue by pjolin-di** [microsoft/dotnet-framework-docker#352]
Pulling tags based on windows server 1903 

For instance, 

docker pull mcr.microsoft.com/dotnet/framework/aspnet:4.8-20190522-windowsservercore-1903

results in: 

failed to register layer: Cannot create layer with missing parent 9c50f974044a5d7fa3a3c1adb48b6d628df957ca9631afa917e15f589be2cf5e

**Comment by StephenMolloy** [comment]
@pjolin-di this should have been fixed.
