### ISSUE TITLE
Intermittent 502 errors when accessing container behind Application Gateway

### ISSUE THREAD

**Issue by dragan-bjelosevic** [microsoft/dotnet-framework-docker#356]
We are hosting a container based on this image in a VM in Azure. In front of the VM is Applicaton Gateway. Occasionally we get 502 Bad Gateway. For testing purpose we removed application code from the image and left just simple  static index.html file (Hello World) like in following Dockerfile.
To isolate the problem we tried packet capturing. That shows that every http request reaches the host but sometimes container just does not reply. Approximately 2/3 of requests get HTTP 200 response while 1/3 lack response. When that occurs App Gateway resets TCP connection and sends 502 to the client. When next request comes, App Gateway initiates a new 3-way handshake, establishes a connection and container responds with HTTP 200 again. Then after a while container does not respond and the whole circle repeats. Do you have any idea why container is not responding? Can you help me troubleshoot this issue?
When deployed directly to the IIS in host the application works well. 
We've done detailed checks of App Gateway settings together with MS support engineers. Everything is done right. 

Dockerfile:
#escape = `
FROM mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-windowsservercore-ltsc2019
WORKDIR c:\prep
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; $verbosePreference='Continue';"]
RUN Add-WindowsFeature WAS,WAS-Process-Model,  Web-Windows-Auth,Web-Digest-Auth, Web-Basic-Auth,WAS-Config-APIs, Web-Net-Ext45,NET-WCF-HTTP-Activation45,Web-Http-Redirect
COPY index.html c:\inetpub\wwwroot\index.html
 
EXPOSE 80

**Comment by StephenMolloy** [comment]
@shirhatti is there any update?

**Comment by shirhatti** [comment]
No idea. I'm closing this issue. Feel free to re-open if this issue persists.
