### ISSUE TITLE
CefSharp not working (missing a system assembly)

### ISSUE THREAD

**Issue by SebastienLorrain** [microsoft/dotnet-framework-docker#357]
Since upgrading from **microsoft/aspnet:4.7.2-windowsservercore-ltsc2016** to **mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-windowsservercore-ltsc2019**, the same sample code for CefSharp Offscreen code does not run anymore.

After investigating, using the CefSharp Minimal Sample (_https://github.com/cefsharp/CefSharp.MinimalExample_), even the sample does not run anymore.

One of the libraries used by KERNELBASE.DLL is missing (could not find a way to determine which one at this point).

Performing a dumpbin on KernelBase.dll lists the following dependencies:

```
Dump of file C:\Windows\System32\KERNELBASE.dll

File Type: DLL

  Image has the following dependencies:

    ntdll.dll
    api-ms-win-eventing-provider-l1-1-0.dll
    api-ms-win-core-apiquery-l1-1-0.dll
    api-ms-win-core-apiquery-l1-1-1.dll

  Image has the following delay load dependencies:

    ext-ms-win-advapi32-registry-l1-1-0.dll
    ext-ms-win-advapi32-registry-l1-1-1.dll
    ext-ms-win-kernel32-appcompat-l1-1-0.dll
    ext-ms-win-ntuser-string-l1-1-0.dll
    ext-ms-win-kernel32-file-l1-1-0.dll
    ext-ms-win-kernel32-datetime-l1-1-0.dll
    ext-ms-win-kernel32-quirks-l1-1-0.dll
    ext-ms-win-kernel32-quirks-l1-1-1.dll
    ext-ms-win-kernel32-sidebyside-l1-1-0.dll
    ext-ms-win-mrmcorer-resmanager-l1-1-0.dll
    ext-ms-win-gpapi-grouppolicy-l1-1-0.dll
    ext-ms-win-ntdsapi-activedirectoryclient-l1-1-0.dll
    ext-ms-win-ntdsapi-activedirectoryclient-l1-1-1.dll
    ext-ms-win-shell32-shellcom-l1-1-0.dll
    ext-ms-win-advapi32-ntmarta-l1-1-0.dll
    ext-ms-win-security-capauthz-l1-1-1.dll
    ext-ms-win-feclient-encryptedfile-l1-1-0.dll
    ext-ms-win-security-efswrt-l1-1-0.dll
    api-ms-win-security-sddl-l1-1-0.dll
    ext-ms-win-appmodel-daxcore-l1-1-0.dll
    ext-ms-win-kernel32-errorhandling-l1-1-0.dll
    ext-ms-win-kernel32-registry-l1-1-0.dll
    ext-ms-win-kernelbase-processthread-l1-1-0.dll
    ext-ms-win-advapi32-npusername-l1-1-0.dll
    ext-ms-win-appxdeploymentclient-appxdeploy-l1-1-0.dll
    ext-ms-onecore-appmodel-staterepository-internal-l1-1-1.dll
    ext-ms-win-appxdeploymentclient-appxdeployonecore-l1-1-0.dll
    ext-ms-win-winrt-device-access-l1-1-0.dll
    ext-ms-win-appmodel-appexecutionalias-l1-1-0.dll
    ext-ms-win-appmodel-appexecutionalias-l1-1-1.dll
    api-ms-win-security-isolationpolicy-l1-1-0.dll
```
The same sample code run perfectly on Windows Server 2019 standard.

Do you know whether a specific module has been stripped from the image (for sizing reasons) and needs to be included back in this case?

I cannot attach the sample here due to size limits.

**Comment by StephenMolloy** [comment]
@shirhatti do you know who the contact is from Windows team?

**Comment by shirhatti** [comment]
I'd ask this on the [Windows container forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers) instead. This repo is not the right place to track this.

@cwilhit if he has more to add.

**Comment by cwilhit** [comment]
If a user needs to use DirectX libraries, they should retarget to the [Windows](https://hub.docker.com/_/microsoft-windows) base image, which carries that dependency. 

Note there is no dotnet framework image based upon the `Windows` base image, so users will need to add that themselves in their dockerfiles.
