### ISSUE TITLE
"latest" tag has not been updated for 3 months

### ISSUE THREAD

**Issue by robbiezhang** [microsoft/dotnet-framework-docker#361]
The "latest" tag was updated 3 months ago. When will you rebuild it with the latest microsoft/dotnet-framework:4.7.2-runtime-20190108-windowsservercore-ltsc2016.

**Comment by StephenMolloy** [comment]
@robbiezhang we just migrated ASP.NET docker into dotnet-framework-docker, hopefully this will be resolved in this month and forward.

**Comment by MichaelSimons** [comment]
`mcr.microsoft.com/dotnet/framework/aspnet:lastest` and `microsoft/aspnet:latest` both point to the latest images available which were serviced earlier this week.
