### ISSUE TITLE
Hosting a Web API 2.0 inside Windows Server Core 2019 results in ManagedPipelineHandler error

### ISSUE THREAD

**Issue by ershadnozari** [microsoft/dotnet-framework-docker#362]
I'm trying to host a Web API 2.0 (.NET Framework 4.7.2) inside a Windows Server Core 2019 container. Here is my Dockerfile:

```
FROM mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-windowsservercore-ltsc2019
WORKDIR /inetpub/wwwroot
COPY . .  
```
Upon submitting a request to the container hosted API I'm receiving a HTTP 500 status. I went ahead and enabled Failed Request Routing and can see below entry in the log file:
```
 <EventData>
  <Data Name="ContextId">{80000002-0000-FF00-B63F-84710C7967BB}</Data>
  <Data Name="ModuleName">ManagedPipelineHandler</Data>
  <Data Name="Notification">128</Data>
  <Data Name="HttpStatus">500</Data>
  <Data Name="HttpReason">Internal Server Error</Data>
  <Data Name="HttpSubStatus">0</Data>
  <Data Name="ErrorCode">0</Data>
  <Data Name="ConfigExceptionInfo"></Data>
 </EventData>

```
Performing the command: `dism /online /enable-feature /featurename:IIS-ASPNET45 /all` does not help.

I have uploaded the failing image to Docker Hub:` docker run -d -p 16670:80 ershadnozari/xbrlvalidator2:latest`. HTTP POST sample request here:
[XbrlRequest.txt](https://github.com/Microsoft/aspnet-docker/files/2806208/XbrlRequest.txt)

I don't have any issue hosting the Api locally, on Windows 10 1809 (version 17763.292).

Any help I can get with this issue is much appreciated.

**Comment by StephenMolloy** [comment]
@ershadnozari, is this still an issue for you?

**Comment by ershadnozari** [comment]
Hey Stephen, we did move to .NET Core & Linux containers, therefore passed the problem. However, we never managed to get to the root cause and solve the issue I’ve here. It can be closed if you wish. Thanks
