### ISSUE TITLE
Server Core 2019 with different languages required, what should I do?

### ISSUE THREAD

**Issue by sanguedemonstro** [microsoft/dotnet-framework-docker#364]
Hello, I'm testing the Windows Server Core 2019 image below:
`FROM mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-windowsservercore-ltsc2019`

My ASP.NET application makes use of a Win32 component that runs scripts containing pt-br punctuation chars, like ã, ç, é and others.

The problem is that scripts with pt-br punctuation chars are being truncated, generating runtime error.

I think the problem is related with 2019 OS language. Using Server Core 2016 works just fine, all good.

Browsing server core registry on docker hub, for Server Core 2016 there is an image available for each language.

So the question is:
- For Server Core 2019, are you planning to release one image for each language? 
- Or, is it possible to install and change 2019 OS Language through dockerfile build?

**Comment by StephenMolloy** [comment]
@shirhatti ?

**Comment by shirhatti** [comment]
I'd re-ask this question in the [Windows Container forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers)

It is my understanding that this is already supported. See the list of available Windows image (including localized) on [DockerHub](https://hub.docker.com/_/microsoft-windows-servercore).

**Comment by s-tokutake** [comment]
@shirhatti 

Hello, I want to use `mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019` with .net framework language package ( ja-jp ).
But as @sanguedemonstro wrote, the installation fails.
And I can't find `mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019`  with the lang pack on DockerHub.

Is there any workaround?

**Comment by ShemTovYosef** [comment]
Hi try it with 2022, it comes with many improvements to language support 

Regards,
Yosef
