### ISSUE TITLE
microsoft/aspnet:4.7.2-windowsservercore-1803 timezone correct but time is incorrect

### ISSUE THREAD

**Issue by Rich-biomni** [microsoft/dotnet-framework-docker#366]
Using Image microsoft/aspnet:4.7.2-windowsservercore-1803

Run: docker exec container powershell get-date... returns incorrect time.

Expected: The Current (Now) time returned

Possible issue: 
w32Time Service is not running? Don't seem to be able to make it run, always exits with access denied.

Thanks

**Comment by StephenMolloy** [comment]
Please direct this issue to the Windows Containers forum at https://social.msdn.microsoft.com/forums/en-us/home?forum=windowscontainers. Your examples make use of mcr.microsoft.com/dotnet/framework/runtime:4.7.2-windowsservercore-1803. There's nothing special about that image from a .NET standpoint. It's essentially just a thin wrapper around the mcr.microsoft.com/windows/servercore:1803 image which already comes with 4.7.2 installed. One thing you may want to try is using one of the main Windows image at https://hub.docker.com/_/microsoft-windows.
