### ISSUE TITLE
What is the best practice to hosting multiple asp.net containers on same VM Docker host?

### ISSUE THREAD

**Issue by kbdavis07** [microsoft/dotnet-framework-docker#367]
So far had not seen any documentation any where on how to host multiple asp.net based containers on the same Docker VM host?

IIS by itself can host multiple websites, but what about now with docker containers that includes IIS in the base image so that is having multiple instances of IIS sharing the same Port 80.

Would like to know what is the best practice to host multiple asp.net 4.6 based websites each in their own containers on the same Docker VM host?

Would like to map by Domain names like IIS does.

-------------------------------------------------------------
Windows Server 2016 VM Docker Host 01

Web1.Website.com --------->  Container Web1 
Web2.Website.com --------->  Container Web2
Web3.Website.com --------->  Container Web3

--------------------------------------------------------------

Each container is self contained and can be easily transfer to another VM with no changes.

What is the best method to do this with Windows Asp.net 4.6+ based websites?

-----------------------------------------------------------------------------------------------------------
Other question:

Is there a way to have an IIS container and have websites content in different containers and some how them connect to the IIS container?

Seems to be waste of resources of having Multiple instances of IIS on the Same VM?

So in this set-up just have 1 IIS Container, and each website content is in their own containers?

----------------------------------------------------------
Windows Server 2016  Docker Host VM 02

IIS : Port 80 ------------------------> IIS Container

Web1.Website.com ---------------> Web1 Content only (No IIS)
Web2.Website.com ---------------> Web2 Content only (No IIS)

So I guess a Docker Compose file needed?

IIS Image

Web content image, depends on IIS?

So for each Web content container added it adds a site to the IIS container and all of the other settings needed for the website?

-----------------------------------------------------------

Just trying to figure out the best method to host multiple Asp.Net 4.6+ based websites on same VM Docker Host according to Docker container best practices as keeping each container to a single service or function.

**Comment by StephenMolloy** [comment]
@shirhatti can you please help?

**Comment by shirhatti** [comment]
> Would like to map by Domain names like IIS does.

Port-sharing between containers isn't supported.

> Each container is self contained and can be easily transfer to another VM with no changes.

There isn't any supported tooling that I'm aware of.

> Is there a way to have an IIS container and have websites content in different containers and some how them connect to the IIS container?

Not sure what you're trying to achieve. The ASP.NET container image is an opinionated image. You're achieving isolation between containers by introducing some redundancy. The overhead of running multiple instances of WAS/W3SVC is minimal and we believe maintaining compatibility is far more important than trying to eliminate it.

If you so chose, you can run your worker process directly without running IIS in each container albeit with some loss in functionality.

**Comment by kbdavis07** [comment]
So how would you host multiple websites in containers on the same VM Host?

What is the best way to do that?

I don't want to have a Separate VM for each website that would be over kill.

Would like to have around 10 or so websites per VM but each with its own container.

Thanks,

Brian Keith Davis

**Comment by shirhatti** [comment]
I'd recommend looking at solutions such as docker compose or kubernetes that help orchestrate running multiple containers concurrently.

**Comment by cyungmann** [comment]
I am interested in this usage scenario as well. It seems like there is a decent amount of documentation about hosting in Azure but virtually no documentation about self-hosting, especially as this thread talks about with multiple IIS instances per host machine. @shirhatti is this still not a supported use case? @kbdavis07 did you ever find a solution?

**Comment by kbdavis07** [comment]
@cyungmann Docker compose or Kubernetes is the best option.
