### ISSUE TITLE
Please enable IIS Rewrite module by default in aspnet-docker image

### ISSUE THREAD

**Issue by MikeChristensen** [microsoft/dotnet-framework-docker#369]
It would be great to have access to the [IIS rewrite module](https://docs.microsoft.com/en-us/iis/extensions/url-rewrite-module/using-the-url-rewrite-module) in IIS by default without having to modify or create our own image.  I think this makes sense as this module is available by default in Azure Websites.  Can this be added by default?

**Comment by StephenMolloy** [comment]
Sorry, we have no plans to add this module by default, as we have many users who do not wish to have this additional module in their base image, and it is not difficult to add it in derived images.

**Comment by 47th** [comment]
Just in case someone comes across this thread. Using ADD will cause docker to issue web request each time it builds the container. To avoid this and cache this layer properly, you may replace ADD with Invoke-WebRequest like this:

```
FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-1909
ARG source
# Install IISRewrite Module
RUN Invoke-WebRequest http://download.microsoft.com/download/D/D/E/DDE57C26-C62C-4C59-A1BB-31D58B36ADA2/rewrite_amd64_en-US.msi -OutFile c:/inetpub/rewrite_amd64_en-US.msi
RUN powershell -Command Start-Process c:/inetpub/rewrite_amd64_en-US.msi -ArgumentList "/qn" -Wait
```

**Comment by MikeChristensen** [comment]
@47th Note that works pretty well for small files, but `iwr` is horridly slow and probably shouldn't be used for large files.  `Start-BitsTransfer` is a lot faster, but doesn't work on all web servers..

**Comment by MichaelSimons** [comment]
Using `ADD` is not a Dockerfile best practice.  In a case like this is you end up carrying the msi in the resulting image which is causing bloat.  See [ADD or COPY](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy) best practices for details.  Keep in mind windows supports `curl` which is a nice alternative here.

**Comment by sekmenhuseyin** [comment]
I am trying to install this module with this dockerfile. is it possible to install it with in linux server. I always get errors like "powershell notfound", "Invoke-WebRequest notfound"

```
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
ENV TZ=Europe/Istanbul
USER $APP_UID
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY ["Sekmen.Web/Sekmen.Web.csproj", "Sekmen.Web/"]
RUN dotnet restore "Sekmen.Web/Sekmen.Web.csproj"

COPY . .
WORKDIR "/src/Sekmen.Web"
RUN dotnet build "Sekmen.Web.csproj" -c "$BUILD_CONFIGURATION" -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "Sekmen.Web.csproj" -c "$BUILD_CONFIGURATION" -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "Sekmen.Web.dll"]
```

**Comment by MikeChristensen** [comment]
> I am trying to install this module with this dockerfile. is it possible to install it with in linux server. I always get errors like "powershell notfound", "Invoke-WebRequest notfound"

Why are you trying to run IIS on Linux?  It's a Windows web server.  There's plenty of great Linux web servers that will support .NET just fine.

**Comment by sksk571** [comment]
@sekmenhuseyin IIS and URL rewrite module only work on Windows. If you need the URL rewrite functionality on Linux, you can for example use [URL rewriting middleware](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/url-rewriting?view=aspnetcore-8.0).
