### ISSUE TITLE
Docker built in references to host do not resolve

### ISSUE THREAD

**Issue by AmrineA** [microsoft/dotnet-framework-docker#370]
I've tried several different things that should resolve to the host IP, but it doesn't seem to do that. Here are the ones I've tried:

host.docker.internal
docker.for.win.localhost
docker.for.win.internal

Below are the steps I did for for this.

```
docker pull microsoft/aspnet:4.7.1-windowsservercore-1709
docker run -d -p 81:80 --name testapp microsoft/aspnet:4.7.1-windowsservercore-1709
docker exec -it testapp powershell
```

Once inside the container, you can do

```
nslookup
> host.docker.internal
```

It won't be able to resolve that to the host.

**Comment by HongGit** [comment]
@AmrineA Please direct this issue to the Windows Containers forum at https://social.msdn.microsoft.com/forums/en-us/home?forum=windowscontainers.  This isn't an issue with ASP.NET container.  ASP.NET container is just a wrapper around windows images https://hub.docker.com/_/microsoft-windows.
