### ISSUE TITLE
An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by arnigunnar** [microsoft/dotnet-framework-docker#376]
I am trying to run this command ``docker pull mcr.microsoft.com/dotnet/framework/runtime:4.7.2-windowsservercore-ltsc2019``, but using the console, I always get an error. ``read tcp 10.44.103.63:59824->204.79.197.219:443: wsarecv: An existing connection was forcibly closed by the remote host.``. There are 4 layers to the image, and when I am running the command, it starts downloading all four, completes the last two, but the first two (1.408GB and 514MB) the console starts downloading a few times but always ends up failing.

I have tried building through VS2019 as well with a DOCKERFILE pointing to this image, that also fails.

Full results:
```
65014b3c3121: Downloading [==================================================>]  1.522GB/1.522GB
02a4c14ecf32: Downloading [==================================================>]  529.5MB/529.5MB
1477e74c02fd: Download complete
f5debc34d550: Download complete
read tcp 10.44.103.63:59910->204.79.197.219:443: wsarecv: An existing connection was forcibly closed by the remote host.
```

Does anyone have any suggestions for me?

**Comment by MichaelSimons** [comment]
moved to https://github.com/microsoft/containerregistry/issues/6 since this is an issue with pulling the image from MCR.
