### ISSUE TITLE
mcr.microsoft.com/dotnet/framework/aspnet:4.8 application pool crashes

### ISSUE THREAD

**Issue by tfrijsewijk** [microsoft/dotnet-framework-docker#388]
Hi all,

I'm having troubles running my legacy application within a container. It does work when I use a volume mount.

I build my image using this Dockerfile:
```
FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8

COPY /redactie-service/redactie/service /iprox/service
RUN /iprox/service/bin/setup.ps1

COPY /redactie/data /inetpub/data

COPY /redactie/www /inetpub/wwwroot

WORKDIR /inetpub/wwwroot

RUN Set-Service -Name aspnet_state -StartupType Automatic
```

To start:

```
docker run -it -p "3000:80" -v "D:\temp\demo-docker\redactie\settings:C:\inetpub\wwwroot\apps\settings" demo-docker/redactie
```

When I open http://localhost:3000 I get `HTTP Error 503. The service is unavailable.`. If I open a Powershell to the running container with

```
docker exec -it nervous_babbage powershell
```

And then run `Get-IISAppPool` inside the container I get

```
PS C:\inetpub\wwwroot> Get-IISAppPool

Name                 Status       CLR Ver  Pipeline Mode  Start Mode
----                 ------       -------  -------------  ----------
DefaultAppPool       Stopped      v4.0     Integrated     OnDemand
.NET v4.5 Classic    Started      v4.0     Classic        OnDemand
.NET v4.5            Started      v4.0     Integrated     OnDemand
```

I'm unable to keep the DefaultAppPool running with `Start-WebAppPool`. As soon as I open http://localhost:3000 the Application Pool crashes.

But if I start the container by mounting the files that I copied:

```
docker run -it -p "90:80" -v "D:\temp\demo-docker\redactie\redactie\www:C:\inetpub\wwwroot" -v "D:\temp\demo-docker\redactie\settings:C:\inetpub\wwwroot\apps\settings" demo-docker/redactie
```

It works!

If I run `dir` on both containers, I see the exact same files.. But with slightly different permissions.

Permissions of working container:

```
PS C:\inetpub\wwwroot> icacls .
. BUILTIN\IIS_IUSRS:(RX)
  BUILTIN\IIS_IUSRS:(OI)(CI)(IO)(GR,GE)
  NT SERVICE\TrustedInstaller:(I)(F)
  NT SERVICE\TrustedInstaller:(I)(OI)(CI)(IO)(F)
  NT AUTHORITY\SYSTEM:(I)(F)
  NT AUTHORITY\SYSTEM:(I)(OI)(CI)(IO)(F)
  BUILTIN\Administrators:(I)(F)
  BUILTIN\Administrators:(I)(OI)(CI)(IO)(F)
  BUILTIN\Users:(I)(RX)
  BUILTIN\Users:(I)(OI)(CI)(IO)(GR,GE)
  CREATOR OWNER:(I)(OI)(CI)(IO)(F)

Successfully processed 1 files; Failed processing 0 files
```

Permissions of not-working container:

```
PS C:\inetpub\wwwroot> icacls .
. BUILTIN\Administrators:(F)
  BUILTIN\Administrators:(OI)(CI)(IO)(F)
  NT AUTHORITY\SYSTEM:(F)
  NT AUTHORITY\SYSTEM:(OI)(CI)(IO)(F)
  NT AUTHORITY\Authenticated Users:(M)
  NT AUTHORITY\Authenticated Users:(OI)(CI)(IO)(M)
  BUILTIN\Users:(RX)
  BUILTIN\Users:(OI)(CI)(IO)(GR,GE)

Successfully processed 1 files; Failed processing 0 files
```

Does anyone have a clue? I haven't got the faintest where to debug this.. The logfiles in `C:\Windows\System32\LogFiles\HTTPERR\httperr1.log` only tell me that DefaultAppPool is down

**Comment by tfrijsewijk** [comment]
I tried your suggestion but the same results.

I posted it to SO: https://stackoverflow.com/questions/57762836/application-only-works-in-docker-container-when-mounted-not-when-starting-the-c

Thanks so far!

**Comment by MichaelSimons** [comment]
@Honggit, @StephenBonikowsky - Do you have any suggestions?

**Comment by HongGit** [comment]
@tfrijsewijk just did a quick check, it seems that the two scenarios above are mounting two different directories:
_1 - "D:\temp\demo-docker\redactie\settings:C:\inetpub\wwwroot\apps\settings"_
_2 - "D:\temp\demo-docker\redactie\redactie\www:C:\inetpub\wwwroot"_
Is this intentional?

**Comment by tfrijsewijk** [comment]
Yes, this is intentional. But you gave me an idea.. Perhaps the bug is inside my application. Mounted volumes are symlinks, maybe my application does not follow symlinks and therefore crashes?

I'll look into it friday, thanks for your time

**Comment by MichaelSimons** [comment]
@tfrijsewijk - Were you able to resolve this issue?  Have you validated the mounts are behaving as expected and that your application handles the symlinks?

**Comment by tfrijsewijk** [comment]
Hi @MichaelSimons, I have concluded that the problem is in my application.. It was full of empty try/catch statements, hence the lack of errors 😲 

Thanks for your time (and HongGit's)
