### ISSUE TITLE
aspnet(iis) set acl to the path(VOLUME)  not working

### ISSUE THREAD

**Issue by lyling** [microsoft/dotnet-framework-docker#399]
it cannot set the acl to the path which be mounted to volume when build image using RUN(powershell).

the script to set-acl works when run in the running container and when build the image without mount the path to volume.

But set VOLUME when build image, the acl of the path is at less permission without any i set.  after running the container the run the script, it works.

why cannot set the acl when building image with VOLUME ??

Edit 1: it is the common scene that the website write logs or others to the website folder like (app_data). need to acl to IUSRS user(or AppPool) 

Edit 2: On docker for windows in windows 10 it all works. the proble only on window server(ltsc2019)

 PS C:\Users\Administrator> docker info
Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Docker clusters (Docker Inc., v1.0.1)

Server:
 Containers: 5
  Running: 1
  Paused: 0
  Stopped: 4
 Images: 36
 Server Version: 19.03.1
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics l2bridge l2tunnel nat null overlay transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: active
  NodeID: uh7cy281f4nwf4iiwucb5ezrz
  Is Manager: false
  Node Address: 192.168.1.22
  Manager Addresses:
   192.168.1.23:2377
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Standard Evaluation Version 1809 (OS Build 17763.379)
 OSType: windows
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.996GiB
 Name: Docker-Host-Win
 ID: XY5X:S25W:FAWH:KW3Z:L42Y:SF42:DM3F:Z3O7:72EV:XR3L:UDSB:JQ7C
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: this node is not a swarm manager - check license status on a manager node

**Comment by MichaelSimons** [comment]
This is an issue that is specific to the windowsservercore OS base image that the dotnet-framework images are based on.  Please post this to the [windows containers forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers).
