### ISSUE TITLE
WebApplication works locally breaks on Azure DevOps agents

### ISSUE THREAD

**Issue by OliverRC** [microsoft/dotnet-framework-docker#411]
Using the docker image mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019 running the application locally (Windows 10 and Windows Server 2019) it works and starts up correctly.

When running the Azure DevOps build agent an 500 error is thrown. When debugging and by turning CustomErrors off, the following error is thrown:

> Compiler Error Message: CS0016: Could not write to output file 
> 'c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET 
> Files\root\e22c2559\92c7e946\App_global.asax.7ir4dqzf.dll' -- 'The directory name is invalid. '

**Dockerfile**
```
FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019

WORKDIR /inetpub/wwwroot

COPY MyPublishApp ./
```

The expectation would be that running locally and on the agent had the same behavior.
Both the agent and my machine have Administrative privileges.

**Comment by OliverRC** [comment]
Happy to try bring down that specific digest and test on that.
Regarding the source code, I'm going to need to create a sample which illustrates the issue as currently it's happening on a corporate code base.

**Comment by mthalman** [comment]
@OliverRC - Any update on this?

**Comment by OliverRC** [comment]
Sorry this dropped off my radar as I our interim fix alleviated the issue. Will give it a test on the specific digest locally and report back

**Comment by OliverRC** [comment]
I was unable to reproduce the issue locally, even when specifying the specific digest of `mcr.microsoft.com/dotnet/framework/aspnet@sha256:8c850cb553f66ef7ca94ecf53f6bfe92a3f4bdaf990f9172a1aabdf21e8cac74`

So this is seeming more related to something on the build agent.

**Comment by Extant-1** [comment]
Can also say I have experienced this identical issue. Docker container running an asp.net app with base image mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019 works fine locally but gives this error when run on Hosted VS 2019 Azure pipeline agent.

The work-around also fixed my issue.
