### ISSUE TITLE
framework SDK image does not register VS Test tools correctly

### ISSUE THREAD

**Issue by grahambunce** [microsoft/dotnet-framework-docker#418]
* Downloaded the docker image framework/sdk 4.8
* Followed instructions here https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops to add Azure DevOps build agent

Issues:

1) VSTest capabilities not registered by build tool - fix: Manually add capability to build agent for VSTest and VSTest_16_0 (NB: This is not an issue when installing VS Build tools and Dev Ops build agent on a base VM)
2) DevOps build script fails if Visual Studio Test (v2) step set to use Test Platform Version "Visual Studio 2019" since it expects to find Visual Studio Installed
3) Change DevOps build task for Visual Studio Test (v2) uses Test Platform Version "Installed by Tools Installer. Task then fails with "Error: VsTest Test Platform folder was not found in cache."

Spend several hours on the internet
Eventually find reference to "Visual Studio Test Platform Installer". Try adding this to build steps.
Build works

Scratch head.... ponder why on earth is "VS Test Platform Installer" needed when VS build tools are installed and the exe for the VS test console runner exists.

Looks like some things are not correctly registered in the container.

**Comment by MichaelSimons** [comment]
It appears that the [Visual Studio Test task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/vstest?view=azure-devops) is discovering the VS Test Platform folder via the following cmd in this scenario:

`vswhere -version [15,17) -latest -products * -requires Microsoft.VisualStudio.PackageGroup.TestTools.Core -property installationPath -format text`

see https://github.com/microsoft/azure-pipelines-tasks/blob/dea0b9a14dadf5c5ed1d6c15ee482733dd45b246/Tasks/VsTestV2/inputparser.ts#L548

The `Microsoft.VisualStudio.PackageGroup.TestTools.Core` component is not found within the container.

Open questions:
1. How do you acquire the `Microsoft.VisualStudio.PackageGroup.TestTools.Core` component?  I don't see it documented on https://docs.microsoft.com/en-us/visualstudio/install/workload-and-component-ids?view=vs-2019
1. Should the Visual Studio Test task support scenarios where the Test Agent was acquired via installing vs_testagent.exe?

A workaround would be to set the `vstestLocation` argument of the Visual Studio Test task to `C:\Program Files (x86)\Microsoft Visual Studio\2019\TestAgent\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe`

**Comment by grahambunce** [comment]
@MichaelSimons are these questions for me?

I will try the workaround and feed back but the VS Test installer works ok too

**Comment by MichaelSimons** [comment]
@grahambunce - Those are open questions I will try to answer.

Yes you are correct in the VS Test installer is another good workaround.  The vstestLocation may be more desirable as it would be faster.

**Comment by MichaelSimons** [comment]
According to AzDo, the vstest task only supports installations with the full IDE or via using the `Visual Studio Test Platform Installer` task.  According to https://github.com/microsoft/azure-pipelines-tasks/issues/9278#issuecomment-455460751, adding support for "build tools" installs is on the backlog.

@grahambunce - feel free to comment on https://github.com/microsoft/azure-pipelines-tasks/issues/9278 or open a new issue to let your scenario be heard.

At this time there is nothing to change in the .NET FX SDK images - we will not be installing the full IDE.  Please use one of the two workarounds mentioned earlier until AzDO adds support for this scenario.
