### ISSUE TITLE
Installation of VS SKU can fail silently

### ISSUE THREAD

**Issue by mthalman** [microsoft/dotnet-framework-docker#419]
The installation of Build Tools SKU, and presumably Test Agent SKU, can silently fail during a Docker build.  Hopefully, this would get caught in tests but I'm guessing there could be cases where tests don't catch things.  The build should immediately fail if the VS installation fails.

Here's an example Dockerfile that will succeed on a build even though the installation has failed (note the referencing of a non-existent component named Foo):
```
# escape=`

ARG REPO=mcr.microsoft.com/dotnet/framework/runtime
FROM $REPO:4.8-windowsservercore-ltsc2019
RUN curl -fSLo vs_BuildTools.exe https://download.visualstudio.microsoft.com/download/pr/1d102ee6-9263-4353-8676-6430f0cc5998/c0457643c8a80b008250148151a51cb6cc0aa2ccb57316db496628faa9b9a84f/vs_BuildTools.exe `
    && start /w vs_BuildTools.exe ^ `
        --add Microsoft.VisualStudio.Workload.MSBuildTools ^ `
        --add Microsoft.VisualStudio.Workload.NetCoreBuildTools ^ `
        --add Microsoft.Net.Component.4.8.SDK ^ `
        --add Microsoft.Component.ClickOnce.MSBuild ^ `
        --add Microsoft.VisualStudio.Component.WebDeploy ^ `
        --add Foo ^ `
        --quiet --norestart --nocache --wait
```

**Comment by MichaelSimons** [comment]
Assigning to @mthalman to investigate how this can be achieved.  Unit tests could be created to validate content but it's desirable to have the Docker build fail up front if there is a failure.
