### ISSUE TITLE
Update 4.7.1 SDK to use 16.3 Build Tools

### ISSUE THREAD

**Issue by mthalman** [microsoft/dotnet-framework-docker#423]
For the 16.3 release, we were not able to update the 4.7.1 SDK image to use the 16.3 version of VS Build Tools SKU due to a couple blocking issues:
* https://dev.azure.com/devdiv/DevDiv/_workitems/edit/988014 (internal MSFT link)
* https://dev.azure.com/devdiv/DevDiv/_workitems/edit/988169 (internal MSFT link)

We need to investigate whether we can work around these issues.

**Comment by MichaelSimons** [comment]
We are unable to find a workaround for this issue.  Because of that a decision was made to no longer produce the 4.7.* images.  

Related #428.
