### ISSUE TITLE
[Question] dotnet framework image entrypoint script

### ISSUE THREAD

**Issue by Drewster727** [microsoft/dotnet-framework-docker#425]
I'm curious if anyone has any suggestions on better ways to start a .net framework application inside of a windows container (via docker).

My .net framework app is not going to be migrated to .net core anytime soon, I'm forced to use windows (and windows containers) to scale it. We use a CI/CD approach of building the images on the build server, pushing the image(s) to our docker registry, then a deployment server transforms config files (depending on the environment, e.g. stage, production, etc...) and places them in a network location the docker hosts can access in order to share/mount them into the containers -- These configs have such things like connection strings and app setting keys, which can vary between environments.

Dockerfile:
```
FROM mcr.microsoft.com/dotnet/framework/runtime:4.8

ENV NAME=Reprocessing-Node-TA-Console
ARG SOURCE=bin\\Release

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
WORKDIR /app
COPY ${SOURCE} .
COPY .\\entrypoint.ps1 .

ENTRYPOINT ["powershell"]
CMD .\\entrypoint.ps1
```
Notice how I have an entrypoint.ps1 powershell script that is my entrypoint, which is this:
```
filter timestamp {"$(Get-Date -Format G): $_"}
$name = $env:NAME
 
if(Test-Path c:\conf){
    Write-Output 'Copying files from c:\conf' | timestamp
    Copy-Item -path c:\conf\*.* -Recurse -Destination . -Force -Verbose
}
 
# start the service
$executable = (get-item "${name}.exe")
$job = Start-Job -Scriptblock { & $Input } -InputObject $executable
 
#Receive-Job $job
Write-Output $job.State
 
# logs
$sys_start_events = Get-EventLog -LogName System -EntryType Error,Warning -After (Get-Date).AddHours(-1)
$app_start_events = Get-EventLog -LogName Application -EntryType Error,Warning -After (Get-Date).AddHours(-1)
$sys_start_events | Format-List
$app_start_events | Format-List
 
# system logs index
$sys_idx = (get-eventlog -LogName System -EntryType Error,Warning -Newest 1).Index
 
#application logs index
$app_idx = (get-eventlog -LogName Application -EntryType Error,Warning -Newest 1).Index
 
while ($job.State -eq 'Running') {
    start-sleep -Seconds 1
 
    $sys_idx_latest = (Get-EventLog -LogName System -newest 1).index
    $app_idx_latest = (Get-EventLog -LogName Application -newest 1).index
    $sys_events = get-eventlog -logname System -EntryType Error,Warning -newest ($sys_idx_latest - $sys_idx) | sort index  
    $app_events = get-eventlog -logname Application -EntryType Error,Warning -newest ($app_idx_latest - $app_idx) | sort index 

    # console for debugging
    $sys_events | Format-List
    $app_events | Format-List
 
    $sys_idx = $sys_idx_latest
    $app_idx = $app_idx_latest
 
    #Receive-Job $job
    Write-Output $job.State | timestamp
    if ($job.State -ne 'Running') {
        Write-Output 'Service is not running, exiting...' | timestamp
    }
}
```
I'm essentially wrapping the start of my application with a script. It spawns the executable and then continuously monitors the status of it while dumping event viewer logs to the console. A key point of the script is at the top where it copies in config files from a generic location (c:\conf in this case) -- because my container image is environment agnostic and needs the transformed files (app.config / web.config for those that know .NET) for whichever environment it's running in.

I've been having some strange instability in my docker swarm cluster which I think may be related to the containers not stopping properly or some variation, that I've outlined here
https://github.com/moby/moby/issues/39955

Windows Server 2019 (1903)

Any thoughts or suggestions? The sample applications from you guys (microsoft) work great, but they don't take into account the need to mount/copy environment-specific config files into the container at runtime.

**Comment by MichaelSimons** [comment]
This looks like a question well-suited for [StackOverflow](https://stackoverflow.com/) rather than the .NET docker issue tracker.  The StackOverflow audience is much larger and you will have better luck getting a good answer there.

**Comment by Drewster727** [comment]
Hey @MichaelSimons you're right. I'll take it over there. However, my instability is totally related to the dotnet framework windows containers, so thought I'd just pop in here and see what people say.

**Comment by MichaelSimons** [comment]
According to moby/moby#39955, this is a 1903 specific issue and not related to the dotnet/framework images.  Closing.
