### ISSUE TITLE
Garbled problem

### ISSUE THREAD

**Issue by rcl4444** [microsoft/dotnet-framework-docker#427]
my source file encoding is not all utf-8,there is my docker file below:
> FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-20190923-windowsservercore-1903 AS build
> COPY . ./project
> WORKDIR /project/src/PSS/
> RUN nuget restore ./PSS.sln
> RUN msbuild ./RJ.PSS.Web/RJ.PSS.Web.csproj /p:Configuration=Release /p:OutDir=/PssWeb /consoleloggerparameters:ErrorsOnly
> 
> FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8-20190910-windowsservercore-1903 AS runtime
> WORKDIR /inetpub/wwwroot
> COPY --from=build /PssWeb/_PublishedWebsites/RJ.PSS.Web ./
> RUN mkdir -p ./app | Out-Null
> ENTRYPOINT ["C:\\ServiceMonitor.exe", "w3svc"]
is will resulting in garbled.

**Comment by MichaelSimons** [comment]
@rcl4444 - It is not clear to me what the problem is.  Can you please provide a set of steps that can be used to recreate the problem?  Is this a usage question/issue or an issue with one of the dotnet/framework Docker images?  For usage questions/issues you will have better luck getting a good answer on [StackOverflow](https://stackoverflow.com/) where the audience is much larger.

**Comment by rcl4444** [comment]
@MichaelSimons,it's problem the mcr.microsoft.com/dotnet/framework/sdk:4.8-20190923-windowsservercore-1903.I use the image compile my source code.some file codeing is gbk.This will lead to garbled problems.when i change those file to utf-8,
The garbled problem is solved.But I can't modify the encoding format of all the files.,my os code page is 936/gb2312., the command line will not cause garbled problems.The image's code page is 65001 ,I can't change the image 's code page to 936 to Verify my thoughts.It's code page 
lead to problems.

**Comment by MichaelSimons** [comment]
@mthalman - Can you investigate?

**Comment by MichaelSimons** [comment]
Since this issue is Windows Container specific and not specific to the .NET Framework images, please post this to the [windows containers forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers)
