### ISSUE TITLE
Docker Stop return status Exited "(3221225786)"

### ISSUE THREAD

**Issue by carloreggiani** [microsoft/dotnet-framework-docker#431]
Hi
I'm investigating a issue regarding official MCR images on a Win2019 server with Docker EE engine 19.03.2.

The images that I'm unsing are:

**mcr.microsoft.com/windows/servercore:1809
mcr.microsoft.com/dotnet/framework/aspnet:4.8**

Stopping containers based on these images ("docker stop" command) I'm getting:
"Exited (3221225786)"

On linux a stop command normally return: "Exited (137)"

Is it a normal behaviour? What's means 3221225786?

Carlo

**Comment by MichaelSimons** [comment]
@carloreggiani - This seems like a Windows Container interaction question.  It is a good question to post on [windows containers forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers).
