### ISSUE TITLE
Question - Is there any scope to include the windows base images

### ISSUE THREAD

**Issue by andyfisher100** [microsoft/dotnet-framework-docker#433]
I was wondering if there is any scope for supplying .net framework images built on the windows base OS image (mcr.microsoft.com/windows)

I know the images are bigger than servercore but we have a use case to use the Windows:1809 image and installing .net 4.8 is causing issues

**Comment by MichaelSimons** [comment]
@andyfisher100, There are no plans for provide Windows based .NET Fx images.  The overwhelming feedback is for smaller images.  While there are use cases for Windows based images, they are limited.  There does not appear to be enough demand to justify the investment to produce and service them.  We expect users to create and manage their own images if they are needed.

**Comment by andyfisher100** [comment]
> @andyfisher100, There are no plans for provide Windows based .NET Fx images. The overwhelming feedback is for smaller images. While there are use cases for Windows based images, they are limited. There does not appear to be enough demand to justify the investment to produce and service them. We expect users to create and manage their own images if they are needed.

Makes sense, i only want to use servercore myself but ended up with a use case for windows unfortunately. Thanks for the feedback!
