### ISSUE TITLE
update-dependencies tool to automate changes for each release

### ISSUE THREAD

**Issue by mthalman** [microsoft/dotnet-framework-docker#439]
To help eliminate human error when preparing changes for releases, we should automate the process of updating the usual set of files.  Examples of updates it would make include:
* timestamp values in manifest.json
* tag values in readme
* MSU patch files
* NuGet CLI version
* VS build tools URLs

This would work similarly to the [update-dependencies](https://github.com/dotnet/dotnet-docker/tree/master/eng/update-dependencies) tool in dotnet-docker.

**Comment by MichaelSimons** [comment]
This is something that would mitigate an area of risk.  Let's target having this in place for the January 2020 patch cycle.
