### ISSUE TITLE
Fix WCF terminology

### ISSUE THREAD

**Issue by mthalman** [microsoft/dotnet-framework-docker#449]
There are many cases in readme files where WCF is referred to as "Windows Communication **Framework**" when it should be referred to as "Windows Communication **Foundation**".

**Comment by MichaelSimons** [comment]
@StephenBonikowsky, is this something you can make a PR to fix?

**Comment by StephenBonikowsky** [comment]
Will do.

**Comment by StephenBonikowsky** [comment]
Fixed with #457 and microsoft/mcr#798
