### ISSUE TITLE
Update Dockerfiles to use COPY instruction rather than ADD

### ISSUE THREAD

**Issue by MichaelSimons** [Microsoft/dotnet-framework-docker#45]
To conform with [Dockerfile best practices](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#add-or-copy), the COPY instruction is preferred over ADD.  All Microsoft Dockerfiles should be following the best practices as they are often referred upon and copied.

**Comment by richlander** [comment]
Sounds good.

**Comment by MichaelSimons** [comment]
Issue #58 covers this issue better.
