### ISSUE TITLE
How to properly set container Time Zone configuration? OR, how to ignore host Time Zone configuration?

### ISSUE THREAD

**Issue by sanguedemonstro** [microsoft/dotnet-framework-docker#464]
Hi, I'm using the following Windows Server Core Image:
```
FROM microsoft/dotnet-framework:4.7.2-runtime-windowsservercore-ltsc2019
```
My container image need to run over unknown container hosts, like AWS, Azure AKS, On Premises and even on Windows Desktops and those hosts have unknown Time Zone configurations.

I need to ensure that an Windows Server Core ltsc2019 container runs under an exactly Time Zone.

I'm newbie, but as far as I know, the whole thing about containers is ship it as image once and run it everywhere, with **environment isolation and integrity**.. right?!

Well, I [already tried](https://stackoverflow.com/questions/55514732/setting-timezone-for-a-windows-container):
* tzutil or Set-Timezone: Not OK, lack of privileges
* set registry during dockerfile build: Not OK, container starting seems to ignore it

So,
* **How to properly set container Time Zone configuration?**
* **How to ignore host Time Zone configuration?**

By the way, Windows Location and Language container settings [seems to have same issues](https://windowsserver.uservoice.com/forums/295047-general-feedback/suggestions/36491128-add-support-to-multi-language-server-core-2019-whe) :(

**Comment by MichaelSimons** [comment]
This is an issue that is specific to the windowsservercore OS base image that the .NET Framework images are based on.  Please post this to the [windows containers forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers).

Regarding lock of priviliges, did you try running as the `ContainerAdministrator`?

**Comment by sanguedemonstro** [comment]
> Regarding lock of priviliges, did you try running as the `ContainerAdministrator`?

Hi @MichaelSimons  yes I did.. not ok:
```
PS C:\Benner\containers\outside\19.0.130.17> docker exec -ti tec-btl-old powershell                                                                                                                                Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\> whoami
user manager\containeradministrator
PS C:\> tzutil /s "AUS Eastern Standard Time"
TZUTIL: Insufficient privileges to set the current time zone.
PS C:\>
```

> This is an issue that is specific to the windowsservercore OS base image that the .NET Framework images are based on. Please post this to the windows containers forum.

Yes, there is an [post about it but, there is no solution](https://social.msdn.microsoft.com/Forums/en-US/windowscontainers/thread/6e9d4aac-9b17-4760-aeab-6688e83aa399/#6e9d4aac-9b17-4760-aeab-6688e83aa399)...
