### ISSUE TITLE
ROSLYN_COMPILER_LOCATION environment variable is not set correctly in the ASP.NET images

### ISSUE THREAD

**Issue by MichaelSimons** [microsoft/dotnet-framework-docker#474]
```
> docker run -it --rm --entrypoint cmd mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-1909 cmd /c "set"
...
ROSLYN_COMPILER_LOCATION=c:\\RoslynCompilers\\tools
...
```

See https://github.com/microsoft/dotnet-framework-docker/blob/master/4.8/aspnet/windowsservercore-1909/Dockerfile#L25

The back slashes are needlessly escaped.

**Comment by MichaelSimons** [comment]
@HongGit, @StephenBonikowsky - Is this something you could fix so that it can be included in the  Jan servicing release?

**Comment by StephenBonikowsky** [comment]
Working on it.

**Comment by StephenBonikowsky** [comment]
@HongGit I'm seeing test failures like this...
```
Expected: c:\\RoslynCompilers\\tools
Actual:   c:\RoslynCompilers\tools
```
I'm looking into why it is expecting the escaped backslashes, if you have some idea please let me know.

**Comment by StephenBonikowsky** [comment]
I found a static string, fixed.
