### ISSUE TITLE
3.5 ASP.NET images do not set PowerShell as default shell

### ISSUE THREAD

**Issue by mthalman** [microsoft/dotnet-framework-docker#483]
All .NET versions of the ASP.NET images set PowerShell as the default shell in the Dockerfile except for the 3.5 images.  This should be consistent across all versions.

Example of how it should be set:
https://github.com/microsoft/dotnet-framework-docker/blob/56db741b9165f7ab26f8ac401f9662ff3378df80/4.8/aspnet/windowsservercore-1903/Dockerfile#L6

**Comment by MichaelSimons** [comment]
This would be considered a breaking change to the existing images.  It is something that should only be considered with the release of a new OS version.  Even then it would be an impactful change that needs careful consideration.

**Comment by MichaelSimons** [comment]
Given the breaking/impactful nature of this change, we don't see a motivation to make the change.
