### ISSUE TITLE
Layout of rendered PDF is different when .NET application is running on docker

### ISSUE THREAD

**Issue by AbhishekPrajapati** [microsoft/dotnet-framework-docker#496]
I have a console application that is built on .NET Framework v4.8. I am trying to run it in Azure Container Instances(ACI) using the docker image. I have created a docker image locally and pushed it to ACI and it is running successfully.

This application sends an email with RDLC report pdf. But the reports I am getting in the mail have different fonts than the report I am getting previously(without docker). I found that the base docker image mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019 I am using does not have fonts loaded with it. I need to install fonts in my docker image/container. So I have copied required fonts to docker image.

Below is my Dockerfile commands:

```
FROM mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019  AS BASE
COPY arial*.ttf c:/windows/fonts/
COPY . .
ENTRYPOINT BackgroundService.exe
```

Still I am facing one issue. The layout of PDF is different than the one I received when I run the same application locally. Please check this snapshot:

![PDF_Layout](https://user-images.githubusercontent.com/9090896/72850074-25aef380-3cf8-11ea-8d6d-39aa030789b5.png)

Do I need to copy anything else as well?

**Comment by MichaelSimons** [comment]
This could be caused by a number of different things including the mechanism used to render the PDF.  This appears to be more of an issue related to the Windows container environment rather than the .NET Framework.  Please post this to the [windows containers forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers).
