### ISSUE TITLE
Can't build 4.8-20200211-windowsservercore-ltsc2019 with provided Dockerfile

### ISSUE THREAD

**Issue by joachim-isaksson** [microsoft/dotnet-framework-docker#520]
## Steps to reproduce the issue
1. Download the 4.8-20200211-windowsservercore-ltsc2019 docker file provided on https://hub.docker.com/_/microsoft-dotnet-framework-sdk/
2. docker build . -t test

## Expected behavior
Builds the image

## Actual behavior
Fails with 

The system cannot find the path specified.
The command 'cmd /S /C curl -fSLo vs_TestAgent.exe https://download.visualstudio.microsoft.com/download/pr/c7d8bceb-64c4-426d-85a2-89bc21b21245/43d1b07a15fa7c77ed6f5e0011d1966c2d6e2610e6a293dfa25dde277abbba94/vs_TestAgent.exe     && start /w vs_TestAgent.exe --quiet --norestart --nocache --wait     && powershell -Command "if ($err = dir $Env:TEMP -Filter dd_setup_*_errors.log | where Length -gt 0 | Get-Content) { throw $err }"     && del vs_TestAgent.exe         && curl -fSLo vs_BuildTools.exe https://download.visualstudio.microsoft.com/download/pr/c7d8bceb-64c4-426d-85a2-89bc21b21245/1f07eb88f128370a60ab6d592b1e0f3deb76036a168c7e3021d0fbaf4316a5a0/vs_BuildTools.exe     && setx /M DOTNET_SKIP_FIRST_TIME_EXPERIENCE 1     && start /w vs_BuildTools.exe ^         --add Microsoft.VisualStudio.Workload.MSBuildTools ^         --add Microsoft.VisualStudio.Workload.NetCoreBuildTools ^         --add Microsoft.Net.Component.4.8.SDK ^         --add Microsoft.Component.ClickOnce.MSBuild ^         --add Microsoft.VisualStudio.Component.WebDeploy ^         --quiet --norestart --nocache --wait     && powershell -Command "if ($err = dir $Env:TEMP -Filter dd_setup_*_errors.log | where Length -gt 0 | Get-Content) { throw $err }"     && del vs_BuildTools.exe         && rmdir /S /Q "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer"     && powershell Remove-Item -Force -Recurse "%TEMP%\*"     && rmdir /S /Q "%ProgramData%\Package Cache"' returned a non-zero code: 3

## Additional information (e.g. issue happens only occasionally)
Repeated on Win10 with HyperV isolation as well as a 2019 LTSC server in Azure, exact same issue.
The 1909 docker image from the same page builds fine on the same Win10 machine, both with process- and HyperV isolation.

## Output of `docker version`
On LTSC server;

Client: Docker Engine - Enterprise
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        2ee0c57608
 Built:             11/13/2019 08:00:16
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.12
  Git commit:       2ee0c57608
  Built:            11/13/2019 07:58:51
  OS/Arch:          windows/amd64
  Experimental:     false

## Output of `docker info`

Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Docker clusters (Docker Inc., v1.2.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 12
 Server Version: 19.03.5
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.1039)
 OSType: windows
 Architecture: x86_64
 CPUs: 2
 Total Memory: 8GiB
 Name: dhbuildagent
 ID: R3LH:OBL2:RCLG:SH6C:A74U:OVJP:XTIM:PPKP:MBLN:PVZK:4TYV:GUHW
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

**Comment by mthalman** [comment]
I just copied that Dockerfile to a new 2019 server VM in Azure and it's building fine for me.  Have you tried splitting out that `RUN` command into separate statements to isolate which command is actually causing the error?

**Comment by joachim-isaksson** [comment]
Tested with a local host server and an azure host server, both ltsc and both failed. When both were patched up to current, the local machine can now build the dockerfile without a problem while the azure machine still can't. Odd.

The failing step is;

`start /w vs_BuildTools.exe ^ --add Microsoft.VisualStudio.Workload.MSBuildTools ^ --add Microsoft.VisualStudio.Workload.NetCoreBuildTools ^ --add Microsoft.Net.Component.4.8.SDK ^ --add Microsoft.Component.ClickOnce.MSBuild ^ --add Microsoft.VisualStudio.Component.WebDeploy ^ --quiet --norestart --nocache --wait `

...which terminates within a second and does absolutely nothing, so attempting to remove the cache with;

`powershell Remove-Item -Force -Recurse "%TEMP%*" && rmdir /S /Q "%ProgramData%\Package Cache"`

...at the later stage fails since it has nothing to remove.

Nevertheless, it seems the patch level of the host has at least some effect, so I'll close this since the problem does not seem to be in the Dockerfile itself. I have some research to do to before possibly getting back with more info :)

**Comment by joachim-isaksson** [comment]
This was the problem;

https://support.microsoft.com/en-us/help/4542617/you-might-encounter-issues-when-using-windows-server-containers-with-t
