### ISSUE TITLE
My windows service in the image can't auto start when I start the container

### ISSUE THREAD

**Issue by goonux** [microsoft/dotnet-framework-docker#526]
Hello guys,
Please help me,
I have built an image windows server with a windows service inside from the dotnet-framework-docker as a base image. 
I have set (-StartupType Automatic) to that service, but when the container is online, the service doesn't start.
Here is the command in Dockerfile
```
New-Service -Name $service_name -DisplayName $service_display_name -Description 'Domain Handlers' -BinaryPathName $service_path -StartupType Automatic
```
and here is the status of that service I got from the running container.
```
ExitCode  : 0
Name      : Project-Dev
ProcessId : 0
StartMode : Auto
State     : Stopped
Status    : OK
```
I also have two solutions for now.
First, I think I can make a script and set it runs in ENDTRYPOINT or CMD, that script will start the service when the container is online.
Second, I saw that the service is running under localsystem permission and have heard about LocalService and NetworkService, so the question is if my service runs under Localservice or networkservice, then It can auto start? (I thought about the permission, maybe the service can't start because of the permission)
So, please help me to get out of these stuffs

**Comment by MichaelSimons** [comment]
This type of question is better suited for [StackOverflow](https://stackoverflow.com/) or the [windows containers forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers).
