### ISSUE TITLE
TimeZoneInfo StandardName, DisplayName changes

### ISSUE THREAD

**Issue by cristina-dorotan** [microsoft/dotnet-framework-docker#529]
## Steps to reproduce the issue
1. use Net Core 2.1 and  Display StandardName and DisplayName on Windows os
2. use Net Core 3.1 and  Display StandardName and DisplayName on Linux os

## Expected behavior
We expect that the StandardNamas and DisplayNames to be the same from 2.1 to 3.1

## Actual behavior
It seams that the behavior has changed from 2.1 to 3.1 on Linux os, the DisplayName is replaced by StandardName and vice versa.

**Comment by MichaelSimons** [comment]
@cristina-dorotan, Per the description, this appears related to .NET Core instead of .NET Framework.  Is this a Docker specific issue or an issue orthogonal to containers?  If this is not container specific please log the issue at https://github.com/dotnet/runtime.
