### ISSUE TITLE
MSBuild is broken in the SDK 4.8 Images

### ISSUE THREAD

**Issue by mkaring** [microsoft/dotnet-framework-docker#548]
## Steps to reproduce the issue

1. Execute `docker run --rm mcr.microsoft.com/dotnet/framework/sdk:4.8-20200211-windowsservercore-ltsc2019 msbuild -version`

## Expected behavior

The version number of MSBuild appears and the container exits.

## Actual behavior

Nothing appears and the container exists

## Additional information (e.g. issue happens only occasionally)

The issue can be reproduced currently on the following tags:
* `4.8-20200211-windowsservercore-ltsc2019`
* `4.8-20200316-windowsservercore-ltsc2019`
* `4.8-20200318-windowsservercore-ltsc2019`
* `4.8-windowsservercore-ltsc2019`
* `4.8`

The latest working tag is:
`4.8-20200114-windowsservercore-ltsc2019`

## Output of `docker version`

```
Client: Docker Engine - Enterprise
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        2ee0c57608
 Built:             11/13/2019 08:00:16
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.12
  Git commit:       2ee0c57608
  Built:            11/13/2019 07:58:51
  OS/Arch:          windows/amd64
  Experimental:     true
```

## Output of `docker info`

```
Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Docker clusters (Docker Inc., v1.2.0)

Server:
 Containers: 18
  Running: 9
  Paused: 0
  Stopped: 9
 Images: 262
 Server Version: 19.03.5
 Storage Driver: windowsfilter (windows) lcow (linux)
  Windows:
  LCOW:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Standard Version 1809 (OS Build 17763.107)
 OSType: windows
 Architecture: x86_64
 CPUs: 12
 Total Memory: 127.9GiB
 Name: SRV31
 ID: UCM7:GK7L:OKFR:PMHS:5KGB:GW2P:I3T7:Z5P7:QLXI:B4TE:5HRH:BCQ2
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  localhost:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by mthalman** [comment]
This is not specific to .NET Framework images but rather is a compatibility issue with the Windows container functionality.  The behavior you're seeing is due to a 32-bit issue that occurs when the Windows version of the container is not compatible with the Windows version of the host.  This is described here: https://support.microsoft.com/en-us/help/4542617/you-might-encounter-issues-when-using-windows-server-containers-with-t.  The resolution to this issue is to ensure your host machine is fully updated to the latest Windows patch.
