### ISSUE TITLE
Trying to Build and Push image via Github Actions but getting below error.

### ISSUE THREAD

**Issue by vinaysandela** [microsoft/dotnet-framework-docker#557]
Trying to Build and Push image via Github Actions but getting below error. Was able to successfully do from my local.

Was able to Build Docker Image using Dockerfile and push to the ACR from my local.
When trying to do the same on Github Actions workflow, getting error. 

Workflow - Build Step after docker login task > 

Step 10/23 : RUN dotnet build
 ---> Running in 9cc1be324a45
Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 70.26 ms for C:\app\dotnetapp\dotnetapp.csproj.
  Restore completed in 68.3 ms for C:\app\utils\utils.csproj.
  utils -> C:\app\utils\bin\Debug\netstandard2.0\utils.dll
  dotnetapp -> C:\app\dotnetapp\bin\Debug\net48\dotnetapp.exe

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.11
Removing intermediate container 9cc1be324a45
 ---> 36c1459e09aa
Step 11/23 : FROM build AS testrunner
pull access denied for build, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Error response from daemon: No such image: vsdotnetapp:latest
An image does not exist locally with the tag: vsgheacr.azurecr.io/vsdotnetapp
The push refers to repository [vsgheacr.azurecr.io/vsdotnetapp]

Please let me know if you need more details.

**Comment by MichaelSimons** [comment]
@vinaysandela - Can you share your entire Dockerfile?  Is `build` the name of a previous stage in your Dockerfile?

**Comment by vinaysandela** [comment]
Yes. Attached is the Dockerfile. 
I was able to build and push docker image to ACR. 
When trying from GitHub actions, getting the error. 

[Dockerfile.txt](https://github.com/microsoft/dotnet-framework-docker/files/4471959/Dockerfile.txt)

My GitHub workflow file is similar to whats mentioned in this link
https://docs.microsoft.com/en-us/azure/aks/kubernetes-action 

 and had all the values in the secrets of ACR and Azure credentials.

**Comment by MichaelSimons** [comment]
@vinaysandela - could you also include the full output from the Docker build step?

**Comment by vinaysandela** [comment]
Sure, Here it is - 
[4_Run docker build.txt](https://github.com/microsoft/dotnet-framework-docker/files/4472278/4_Run.docker.build.txt)

**Comment by MichaelSimons** [comment]
@vinaysandela - The Dockerfile you sent doesn't appear to match the build output.

From the build output I see the following.

> 2020-04-13T21:35:18.7261171Z Step 1/23 : FROM mcr.microsoft.com/dotnet/framework/sdk:4.8 as build-env

Your Dockerfile has the following as the first instruction:

> FROM mcr.microsoft.com/dotnet/framework/sdk:4.8 AS build

The problem from the build output looks to be you are referencing a `build` stage that doesn't exist.  From your build output, I am guessing you renamed the `build` stage to `build-env`.  If this is the case, you will need to update all references to the `build` stage.

**Comment by vinaysandela** [comment]
Thanks Michael, I was trying different things and the log is different from the Dockerfile. 
Please find below for docker file and the recent output- 
[Dockerfile.txt](https://github.com/microsoft/dotnet-framework-docker/files/4472522/Dockerfile.txt)

Also, made some changes and Got the step successful. Next step, I am facing is creating AKS Cluster. It says - "This size is currently unavailable in this location for this subscription"
Tried different locations with a minimum of 1 node. Can you suggest how can I get one? Thanks

**Comment by MichaelSimons** [comment]
@vinaysandela, glad to hear you got past that problem.  Your next question is better suited for [StackOverflow](https://stackoverflow.com/) rather than the .NET docker issue tracker.  The StackOverflow audience is much larger and you will have better luck getting a good answer there.
