### ISSUE TITLE
how to set identity of an application pool with this image?

### ISSUE THREAD

**Issue by karthikmuthiah** [microsoft/dotnet-framework-docker#563]
I am trying to host a .NET application which requires permissions to edit the configuration files. This requires adding identity to the application pool. How to do it?

**Comment by MichaelSimons** [comment]
@shirhatti - is this something you could provide guidance on?

**Comment by karoletrych** [comment]
I'm having a similiar issue. From within my .NET application I'd like to access a SMB share that I mount at the start of the container.

The identity can be set using:
```
Import-Module WebAdministration;
Set-ItemProperty IIS:\AppPools\DefaultAppPool -name processModel -value @{userName="admin";password="test123!";identitytype=3}
```
but the ContainerAdministrator has no password defined, and a password is required here.

I'm using mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019 and running it on Kubernetes (GKE).

I'd appreciate any guidance.

**Comment by shirhatti** [comment]
@karoletrych The recommended to achieve what you're doing is by using a gMSA. See this doc for more details- https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/manage-serviceaccounts

--------------
@karthikmuthiah I'm not sure what you're trying to achieve, and changing the identity may not be required 

You could use appcmd or Powershell to modify IIS Configuration. For e.g.,

```
C:\Windows\System32\inetsrv\appcmd.exe set config -section:system.applicationHost/applicationPools /[name='DefaultAppPool'].processModel.identityType:LocalSystem /commit:apphost
```

**Comment by MichaelSimons** [comment]
Closing per @shirhatti's answer.  Feel free to continue discussing.
