### ISSUE TITLE
Installing python on image with sdk:4.8 base fails without error.

### ISSUE THREAD

**Issue by joel388** [microsoft/dotnet-framework-docker#585]
## Steps to reproduce the issue
1. Create a docker image with `mcr.microsoft.com/dotnet/framework/sdk:4.8` as base, that installs Python using an installer executable, e.g. using a powershell script with the following command:
`Start-Process c:\python.exe -ArgumentList '/quiet InstallAllUsers=1 PrependPath=1' -Wait ;`
2. Build the image

## Expected behavior
The as part of the build, the installer is running in quiet mode/headless mode.
After the image has been build, running a container based on the image has python installed and available from the command line, i.e. python has been added to the path.

## Actual behavior
The installer is run, but without an error it doesn't finish. The build of the image succeeds. Running a container based on the image shows that python is not installed and not added to the path.

## Additional information (e.g. issue happens only occasionally)

- Installing python using Chocolatey seems to face the same issue. 
It does give an error number in that case: `Exit code was '-1073741511'.`

- Building with `mcr.microsoft.com/dotnet/framework/sdk:4.7.2` or `mcr.microsoft.com/windows/servercore:1809_amd64` seem to work fine.

### Docker file
```
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8
ADD . .
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
RUN .\scripts\install_python.ps1
```

### install_python.ps1
```
wget https://www.python.org/ftp/python/3.8.2/python-3.8.2.exe -OutFile c:\python.exe ;
Start-Process c:\python.exe -ArgumentList '/quiet InstallAllUsers=1 PrependPath=1' -Wait ;
Remove-Item c:\python.exe -Force
```

## Output of `docker version`

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:37:20 2020
  OS/Arch:          windows/amd64
  Experimental:     false
```

## Output of `docker info`

```
Client:
 Debug Mode: false

Server:
 Containers: 75
  Running: 1
  Paused: 0
  Stopped: 74
 Images: 274
 Server Version: 19.03.8
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.1)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 3.743GiB
 Name: WIN-60HKIT8NGUS
 ID: DJS7:BL6Q:D3WF:L5GU:BY5D:O52D:TVG4:SELD:BEQK:574M:4NXA:SD6B
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 45
  System Time: 2020-05-26T12:16:33.7684673+02:00
  EventsListeners: 2
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by MichaelSimons** [comment]
FWIW, I am unable to reproduce this issue.  I was able to build the image with the provided repro steps and run python in the resulting image.

**Comment by MichaelSimons** [comment]
@mthalman - can you try reproducing this?

**Comment by joel388** [comment]
Thank you for picking up this issue. I'd like to add the following information. mcr.microsoft.com/dotnet/framework/sdk:4.8 for us had the same hash as mcr.microsoft.com/dotnet/framework/sdk:4.8-ltsc2019 (we've tried both, but with the same result). I'm not sure whether using mcr.microsoft.com/dotnet/framework/sdk:4.8 resolves to different tags depending on the environment, so that is why I wanted to be more explicit.

**Comment by MichaelSimons** [comment]
@joel388 - thanks for the additional information.  The `4.8` tag is a multi-platform tag which will retrieve a different image depending on the platform (e.g. Windows version) you pull from.  If you pull it from a 1809 box, it should resolve to the same image that the `4.8-windowsservercore-ltsc2019` tag references.

**Comment by mthalman** [comment]
It looks like the Python installer is 32-bit.  So I suspect this is due to the Windows host incompatiblity issue introduced in the February update of Windows.  Basically, if the version of your Windows host machine and the version of the Windows container you're running are on different sides of that February update version, then they're not compatible and 32-bit processes won't work.  See https://support.microsoft.com/en-us/help/4542617/you-might-encounter-issues-when-using-windows-server-containers-with-t.  Ensure you're running an updated version of Windows on your host machine.

**Comment by joel388** [comment]
> It looks like the Python installer is 32-bit. So I suspect this is due to the Windows host incompatiblity issue introduced in the February update of Windows. Basically, if the version of your Windows host machine and the version of the Windows container you're running are on different sides of that February update version, then they're not compatible and 32-bit processes won't work. See https://support.microsoft.com/en-us/help/4542617/you-might-encounter-issues-when-using-windows-server-containers-with-t. Ensure you're running an updated version of Windows on your host machine.

We've updated Windows and rebuild the image with 4.8 tag as base image; and it worked.

Thank you for your support. I'll close this issue.
