### ISSUE TITLE
MSBuild is broken in the SDK 4.7.2 Images

### ISSUE THREAD

**Issue by RLovelett** [microsoft/dotnet-framework-docker#589]
## Steps to reproduce the issue
0. `powershell`
1. `docker run --rm mcr.microsoft.com/dotnet/framework/sdk:4.7.2-windowsservercore-ltsc2019 msbuild -version`
2. `$lastExitCode`

## Expected behavior
The version number of MSBuild appears and the container exits. The output of `$lastExitCode` is `0`.

## Actual behavior
The container exits. There is no MSBuild information. The output of `$lastExitCode` is `-1073741502`.

## Additional information
I've read through https://github.com/MicrosoftDocs/visualstudio-docs/issues/4772, https://github.com/microsoft/dotnet-framework-docker/issues/548 and a few others. Those issues seem to indicate that I am supposed to update my host. My host has every patch applied to it that Windows Update shows.

## Output of `docker version`

```
Client: Docker Engine - Enterprise
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        2ee0c57608
 Built:             11/13/2019 08:00:16
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.12
  Git commit:       2ee0c57608
  Built:            11/13/2019 07:58:51
  OS/Arch:          windows/amd64
  Experimental:     false
```

## Output of `docker info`

```
Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Docker clusters (Docker Inc., v1.2.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 13
 Server Version: 19.03.5
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Standard Version 1809 (OS Build 17763.1217)
 OSType: windows
 Architecture: x86_64
 CPUs: 6
 Total Memory: 7.999GiB
 Name: DOCKER-HOST-WINDOWS
 ID: SGZJ:BBSP:AIDB:7LMS:SGDH:PPGB:PQTF:CGHF:LHAR:ZAMW:VCFQ:LS4W
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by mthalman** [comment]
4.7.2 SDK images are no longer supported.  See this announcement: https://github.com/microsoft/dotnet-framework-docker/issues/428
