### ISSUE TITLE
Question: What image to use for .net core web api targeting net472?

### ISSUE THREAD

**Issue by luminescent** [microsoft/dotnet-framework-docker#592]
Hi 

We're trying to dockerise a .NET core web api project that eventually had to target net472 instead of .net core. 

What is the best windows container to use for that? It seems like the repo has either .net core images or full framework images. 

Thank you.

**Comment by mthalman** [comment]
A project either targets .NET Core or .NET Framework but not both.  So a .NET Core project that targets net472 is not possible.  If the target is net472, it's a .NET Framework application.  It's possible you're thinking the new [SDK-style](https://docs.microsoft.com/en-us/dotnet/standard/frameworks) project format means it's a .NET Core project.  That's not the case.  That's just a project format that can be used to target either .NET Core or .NET Framework.

So if you have a Web project targeting net472, you should use the .NET Framework Docker images described by this repo.  You can find such a sample project here: https://github.com/microsoft/dotnet-framework-docker/tree/master/samples/aspnetapp.

**Comment by luminescent** [comment]
Sorry, yes, I am fully aware of the difference between the 2 frameworks, I was rather ambiguous in my question. Exactly, I did mean a new SDK-style project format that targets 472 (created with `dotnet new webapi`, and subsequently changed to target the full framework).  

I will need the dotnet cli to work on this container - but I suppose only nuget and msbuild will work "out of the box" on it?

**Comment by mthalman** [comment]
The `dotnet` CLI is capable of building .NET Framework projects if they're defined as an SDK-style project.  In addition, the [.NET Core build tools are installed](https://github.com/microsoft/dotnet-framework-docker/blob/132e32d440294b68cf237ccb97607d4102d7b6d9/4.8/sdk/windowsservercore-2004/Dockerfile#L25) in the .NET Framework SDK images.  So you can use the `dotnet` CLI to build your project with the SDK image if you choose.

**Comment by luminescent** [comment]
That's perfect, thank you, that's been very helpful.
