### ISSUE TITLE
Manifest for 4.8-3.5 tag includes versions of Windows that don't have 4.8 installed

### ISSUE THREAD

**Issue by mthalman** [microsoft/dotnet-framework-docker#604]
The changes in https://github.com/microsoft/dotnet-framework-docker/commit/19559e06a9703dfde0a276589d353a9834787d78 added the `4.8-3.5` tag but it gets applied to all Windows versions.  This means you could pull that tag on a Windows Server 2016 machine and it will successfully pull down the 3.5 image.  But the 3.5 image on Server 2016 doesn't have 4.8 installed in it.  The `4.8-3.5` tag should really only apply to 1903 and later versions which do have 4.8 installed on them.

**Comment by zorpasg** [comment]
I confirmed that pulling image `mcr.microsoft.com/dotnet/framework/aspnet:4.8-3.5` on a **Windows 10 (version 1909)** machine and running a container off of it, has 4.8 installed in it. Pulling the same image on a **Windows Server 2019 (version 1809)** and running a container off of it, does not have 4.8 installed, but rather 4.7.

**Comment by mthalman** [comment]
The infrastructure doesn't readily support being able to be define a manifest tag that only applies to a subset of the supported Windows versions.  This is the only scenario that would require it.  It's a nontrivial amount of work to support it.  Because the ROI of making such changes is low and the usage of this tag is quite low, we've decided to no longer document this tag.  It will still exist for backwards-compatibility purposes but will not appear in the documented list of supported tags in readmes.
