### ISSUE TITLE
Image does not work with gmsa accounts

### ISSUE THREAD

**Issue by undecided2013** [microsoft/dotnet-framework-docker#607]
## Steps to reproduce the issue

Execute docker run like this

docker run --security-opt "credentialspec=file://testgmsa.json" --hostname gmsaWeb -it mcr.microsoft.com/dotnet/framework/wcf:4.8 powershell

You need to have a valid testgmsa.json credentialspec file. I tested mine with

docker run --security-opt "credentialspec=file://testgmsa.json" --hostname gmsaWeb  -it mcr.microsoft.com/windows/servercore:ltsc2019 powershell

## Additional Info
I was trying to port some existing WCF Web Application to docker images and when I got to the gmsa step I got this error, I thought it had to do with me having modified the defaultapppool but I slowly removed lines from my dockerfile until I was left just with the 'from' line. I then realized the image has an issue.

## Expected behavior

Container should start and should get powershell prompt.

## Actual behavior

Error messages are emitted
"
Stopping service 'w3svc'

Service 'w3svc' has been stopped

APPCMD failed with error code 4312

Failed to update IIS configuration
"

## Output of `docker version`
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:36:50 2019
  OS/Arch:          windows/amd64
  Experimental:     false
## Output of `docker info`
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.3.1-tp-docker)

Server:
 Containers: 31
  Running: 0
  Paused: 0
  Stopped: 31
 Images: 233
 Server Version: 19.03.5
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 18362 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Enterprise Version 1903 (OS Build 18362.900)
 OSType: windows
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.83GiB
 Name: CONSTANTZ-22D1
 ID: YYFL:WODX:J43U:UBF7:DUWS:VRR2:YRWL:F7WO:DGY6:PMLI:KQ6A:SPKC
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 30
  System Time: 2020-07-09T15:43:40.1152957-04:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

**Comment by mthalman** [comment]
@honggit - Can you take a look at this?

**Comment by MichaelSimons** [comment]
Closing this as a duplicate of https://github.com/microsoft/iis-docker/issues/175.  The https://github.com/microsoft/iis-docker repo is a better place to log the issue.
