### ISSUE TITLE
Unable to clone ssh-based GIT URIs

### ISSUE THREAD

**Issue by atrauzzi** [Microsoft/dotnet-framework-docker#61]
Not sure what happened, but up until last week, I was able to clone git repositories via SSH-based URIs in my Windows containers based on this image.  Now, suddenly without warning, when I go to clone - even a public repository, I get this error:

```
C:\>git clone git@github.com:atrauzzi/praxis.git
git clone git@github.com:atrauzzi/praxis.git
Cloning into 'praxis'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Here's a simple `Dockerfile` that can be used to reproduce the issue:

```
FROM microsoft/dotnet-framework:4.7.1-windowsservercore-1709
SHELL ["powershell"]

RUN Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
RUN choco install --yes git

RUN refreshenv
```

I'm just not sure at this point.  The only suspicious thing is that if I try to run the mingw based `ssh.exe`, it prints a blank line and then exits.

### cc.
 - https://forums.docker.com/t/unable-to-run-git-inside-a-windows-container/42803
 - https://serverfault.com/questions/887752/unable-to-clone-ssh-based-git-uris-in-a-windows-container
 - https://social.msdn.microsoft.com/Forums/en-US/4d2578c6-c380-4657-9dff-9f5eeb570cd3/git-clone-doesnt-work-in-container?forum=windowscontainers
 - https://github.com/git-for-windows/git/issues/1403

**Comment by atrauzzi** [comment]
Also, attempting to install using chocolatey results in the same issue.

**Comment by MichaelSimons** [comment]
@atrauzzi - Can you clarify what image this use to work in?  Also have you tried doing this with a base OS image?

**Comment by atrauzzi** [comment]
Any derived from the two available Windows server core containers.

Haven't tried the main Windows one, but I'm not sure where to report issues for it.

**Comment by atrauzzi** [comment]
Er, nano or core. Whichever can run the full .net framework. I always confuse them.

**Comment by MichaelSimons** [comment]
As seen in https://github.com/git-for-windows/git/issues/1403, this is not an issue specific to the microsoft/dotnet-framework images.
