### ISSUE TITLE
The dotnet-framework:4.7 image is ~12GB in size

### ISSUE THREAD

**Issue by masroorhasan** [Microsoft/dotnet-framework-docker#62]
Leveraging the dotnet-framework:4.7 as a base image for some dotnet applications however the size of the base image 12GB.
![image](https://user-images.githubusercontent.com/802678/33897620-d4aaea44-df1a-11e7-9118-d2b55ca3d57d.png)

I understand its built on top of windowsservercore image but still a framework and runtime with 12GB is difficult to wrap my head around. I'm thinking about extracting the framework and runtime and build it off nanoservercore or using scratch. Am I missing something or some other existing image that is a lightweight version of just the dotnet framework and runtime?

Thanks.

**Comment by atrauzzi** [comment]
Yeah, these images are far too large.

**Comment by MichaelSimons** [comment]
I would suggest using Windows Server 2016 Version 1709 (Fall Creators Update) based images if possible.  They are still too big but they are half the size.

```
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
microsoft/windowsservercore   1709                be1324f21832        3 weeks ago         5.58GB
microsoft/windowsservercore   ltsc2016            1fbef5019583        3 weeks ago         10.4GB
```

Full .NET Framework will not run on Nano Server which is why these images are based on Windows Server Core.  .NET Core will run on Nano Server.

**Comment by masroorhasan** [comment]
Thanks @MichaelSimons  - that's a decent alternative. 

I'm curious to know what the limitations are for dotnet-framework that it requires the full windowsservercore as a base image. Kind unrelated to this issue but to be honest even ~5GB is quite large in terms of docker image - correct me if I'm wrong but its almost as if a VM image is being converted to a docker image. Do you know if there is a way it can be built off scratch?

Thanks again.

**Comment by MichaelSimons** [comment]
@masroorhasan - Yes I agree 5 GB is still pretty big.  It is not just a VM image.  Can you explain what you mean by `built off scratch`?  I'm not following.

**Comment by masroorhasan** [comment]
@MichaelSimons apologies I thought a base image could be built off the '[scratch](https://docs.docker.com/engine/userguide/eng-image/baseimages/#create-a-simple-parent-image-using-scratch)' image provided by docker, but I realized windows containers relies on the isolation process provided by windows server (i.e. the windows server core).

**Comment by richlander** [comment]
@masroorhasan I understand the desire but microsoft/windowsservercore is a hard dependency of .NET Framework. There is nothing we can do to change that.

We will continue to seek ways of making our images smaller, but they will never be smaller than microsoft/windowsservercore images by virtue of this dependency.

**Comment by masroorhasan** [comment]
Thanks for the explanation @richlander - the dependency problem makes sense now. Just to clarify, the fall creators edition should be referenced as the following?
```
FROM microsoft/dotnet-framework:4.7.1-windowsservercore-1709
```

It would definitely be an improvement in cutting down the image size by half for sure.

**Comment by masroorhasan** [comment]
The reason I ask is because, using the above base image throws an error with any intermediary instructions between `FROM` and `CMD` on the Dockerfile. i.e.
```Dockerfile
FROM microsoft/dotnet-framework:4.7.1-windowsservercore-1709
RUN mkdir c:\bin
CMD [ "cmd" ]
```
Gives the following error:

```powershell
C:\Users\MasroorH\Desktop\dotnet-docker> docker build -t dotnet-bsr-new .
Sending build context to Docker daemon  26.68MB
Step 1/10 : FROM microsoft/dotnet-framework:4.7.1-windowsservercore-1709
Step 2/10 : RUN mkdir   c:\bin
container 591b8664e71c9d4e54f00fdaa51a784844e6a61db73c2f0cbf5d35f1f911d89a encountered an error during CreateContainer: failure in a Windows system call: A connection could not be established with the Virtual Machine hosting the
Container. (0xc0370108) extra info: {"SystemType":"Container","Name":"591b8664e71c9d4e54f00fdaa51a784844e6a61db73c2f0cbf5d35f1f911d89a","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\w
indowsfilter\\591b8664e71c9d4e54f00fdaa51a784844e6a61db73c2f0cbf5d35f1f911d89a","Layers":[{"ID":"3cf02adf-e79c-56c6-b846-160a313f0682","Path":"C:\\ProgramData\\Docker\\windowsfilter\\d7417fd1e35435faf80b144e57e34a13008a31b91bd30c
a85d2223328fac10fc"},{"ID":"02678abf-bdc3-53c2-8e4a-bf7c0c8e602e","Path":"C:\\ProgramData\\Docker\\windowsfilter\\76ac769a65a37c585517acc81f467288ee298465ccecb0be97de1d16e3b1c78e"},{"ID":"25e2369e-39f2-5c98-ab7d-3b6adf943344","Pa
th":"C:\\ProgramData\\Docker\\windowsfilter\\4a3e61f4d672c46cd9f7c7e92270fe36b0c06c033df5c53faba728d911c2808a"}],"HostName":"591b8664e71c","HvPartition":true,"EndpointList":["366e03a5-c872-4759-840e-eb21a2d5bb08"],"HvRuntime":{"I
magePath":"C:\\ProgramData\\Docker\\windowsfilter\\76ac769a65a37c585517acc81f467288ee298465ccecb0be97de1d16e3b1c78e\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}
``` 

However, if the image has no intermediary instructions, then the build is fine. i.e.
```Dockerfile
FROM microsoft/dotnet-framework:4.7.1-windowsservercore-1709
CMD [ "cmd" ]
```

Is this base image only meant to be used for interactive running containers? Or maybe an issue with the underlying host being windows 10 (not a problem with regular windowsservercore-ltsc2016?

Let me know if this can be tracked on this issue or whether I should open a separate issue for it. 

Thanks again.

**Comment by MichaelSimons** [comment]
@masroorhasan 

> Just to clarify, the fall creators edition should be referenced like the following?
> FROM microsoft/dotnet-framework:4.7.1-windowsservercore-1709

Yes that is correct.

Can you explain what your Docker host environment is?  You need to be on a Fall Creators Update host in order to use the 1709 based images.  There are [compatibility limitations](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility) with 1709.

**Comment by masroorhasan** [comment]
@MichaelSimons Thanks for confirming - my host OS's are windows 10 and/or windows server 2016. I would need to look into 1709 and fall creator's update on both moving forward.
