### ISSUE TITLE
IIS CORS Module pre-installed in aspnet image?

### ISSUE THREAD

**Issue by GerryWilko** [microsoft/dotnet-framework-docker#625]
I have been unable to find a definitive answer to this question so thought I should create an issue in case anyone else is struggling with this.

Is the IIS CORS Module installed and enabled in IIS inisde the aspnet image?

I am currently experiencing some strange CORS issues which I was wondering if they might be related to this.

Many thanks,
Gerard

**Comment by mthalman** [comment]
No, it's not configured.  You can see how the ASP.NET image is generated by viewing the appropriate Dockerfile linked to on the [Docker Hub page](https://hub.docker.com/_/microsoft-dotnet-framework-aspnet).

cc @HongGit

**Comment by GerryWilko** [comment]
Many thanks. This was the route cause of my issues I was having. If anyone is interested here is the command for installing CORS module with Chocolatey:
``
    RUN Set-ExecutionPolicy Bypass -Scope Process -Force; `
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; `
        iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')); `
        choco install iis-cors-module -y
``

If anyone is interested in my other learnings from wrapping up my ASP.NET WebForms app into a container sitting behind kubernetes then take a look here: https://stackoverflow.com/questions/63338065/kubernetes-nginx-ingress-ingress-controller-cors-handled-by-application/63360780
