### ISSUE TITLE
Unable to build 2019 vcxproj using mcr.microsoft.com/dotnet/framework/sdk:4.8

### ISSUE THREAD

**Issue by soorajpudiyadath** [microsoft/dotnet-framework-docker#633]
## Steps to reproduce the issue
1. MSBuild.exe abcd.vcxproj -p:Platform=x64
2. project was upgraded to 2019 VS , <PlatformToolset>v142</PlatformToolset>
3.

## Expected behavior
build should succeed

## Actual behavior
error in build : error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props" was not found. Confirm that the expression in the Import declaration "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\\Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.

## Additional information (e.g. issue happens only occasionally)
- Using AWS codebuild to load the docker image
- docker image mcr.microsoft.com/dotnet/framework/sdk:4.8
- i also ran the command "gci -Recurse -Filter "Microsoft.Cpp.Default.props" -File -ErrorAction Continue -Path "C:\Program Files (x86)" -Verbose". This didn't give any result may be because v142 tool set is not installed ?

## Output of `docker version`

```
(paste your output here)
```

## Output of `docker info`

```
(paste your output here)
```

**Comment by MichaelSimons** [comment]
The `sdk` images do not install the c++ workloads.  You can see which workloads are installed by looking at the Dockerfiles ([example](https://github.com/microsoft/dotnet-framework-docker/blob/master/src/sdk/4.8/windowsservercore-ltsc2019/Dockerfile#L24)).  I would suggest creating your own image based on the .NET FX sdk image and install the workloads your scenario requires.  I'm not certain which specific workload you need to install - maybe `Microsoft.VisualStudio.Component.VC.Tools.x86.x64`?
