### ISSUE TITLE
windows server version 2004 image not published for aspnet 4.6.2

### ISSUE THREAD

**Issue by mmccord-mdbuyline** [microsoft/dotnet-framework-docker#638]
Windows server version 2004 images have been [published it seems](https://github.com/microsoft/dotnet-framework-docker/issues/586) for all other framework image versions except `4.6.2`. As you can see in the [latest tag list](https://mcr.microsoft.com/v2/dotnet/framework/aspnet/tags/list), `4.6.2` did not receive the same update. The fact that the image is based on a windows server version less than 2004 I believe is causing issues with msvsmon.exe in containers on windows 10 hosts which are at version 2004.

**Comment by mthalman** [comment]
Version 2004 has 4.8 installed by default, so having 4.6.2 in a 2004 image is not relevant.  Are you aware of the [Windows container compatibility matrix](https://docs.microsoft.com/virtualization/windowscontainers/deploy-containers/version-compatibility)?  The 4.6.2 image is based on Windows Server 2016; in order to run it on a host machine with Windows Server, version 2004, you'll need to enable Hyper-V isolation.

**Comment by mmccord-mdbuyline** [comment]
Yes, we had reviewed the compatibility matrix. The application we're using is based on framework 4.6.2. This page (https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/version-compatibility) made us a little scared that compatibility issues _could_ arise even though theoretically it was compatible. For this reason, we had considered using the 4.8 image but wanted to get things working with 4.6.2 image if we could. So in this situation you're saying the recommended approach is to use the 4.8 image due to framework backwards compatibility?

**Comment by mthalman** [comment]
> So in this situation you're saying the recommended approach is to use the 4.8 image due to framework backwards compatibility?

Each situation is different so you'll need to decide which approach is best for your application.

The two options are:
1. Run the app in a 4.6.2 image on a 2004 host using Hyper-V isolation.  This requires more machine resources compared to process isolation.
2. Run the app in a 4.8 image and deal with the potential for compatibility issues.  Thorough testing of code paths will be required.

**Comment by mmccord-mdbuyline** [comment]
Sounds good. Thanks!
