### ISSUE TITLE
New Windows Release - 20H2

### ISSUE THREAD

**Issue by mthalman** [microsoft/dotnet-framework-docker#647]
# New Windows Release

Windows version: 20H2

## Prep Tasks

1. - [x] Ensure a ["New Windows Release" issue](https://github.com/dotnet/docker-tools/blob/.github/ISSUE_TEMPLATE/releases/new-windows-release.md) exists for docker-tools repo
1. - [x] Copy the Dockerfiles of the most recent published Windows version for `3.5` and `4.8` Dockerkfiles and place them in a version-specific folder under their respective variants (`runtime`, `sdk`, `aspnet`, `wcf`)
1. - [x] Modify the Dockerfiles as appropriate for any specific changes related to the new Windows version
      - [x] The `3.5/runtime` Dockerfile will need to have the `Apply latest patch` section removed since there is no patch to apply for a new Windows version
1. - [x] Update [manifest.json](https://github.com/microsoft/dotnet-framework-docker/blob/master/manifest.json) to reference the new set of Dockerfiles with the appropriate tags
1. - [x] Update [manifest.samples.json](https://github.com/microsoft/dotnet-framework-docker/blob/master/manifest.samples.json) to include the new Windows version for each of the samples
1. - [x] Update the test data for each of the [test classes](https://github.com/microsoft/dotnet-framework-docker/tree/master/tests/Microsoft.DotNet.Framework.Docker.Tests) to include the new Windows version
1. - [x] Look up the recommended latest [NuGet CLI version](https://www.nuget.org/downloads) and update the [nuget-info.json](https://github.com/microsoft/dotnet-framework-docker/blob/master/eng/nuget-info.json) file to associate that NuGet version with the new version of Windows
1. - [x] Run the `update-dependencies` tool to update all the necessary files:
      - [x] `dotnet run --project .\eng\update-dependencies`
1. - [x] Inspect generated changes for correctness
1. - [x] Test the images
      1. - [x] Create a local VM of the new Windows version
      1. - [x] Clone this repo with the above changes onto the VM
      1. - [x] Run `.\build-and-test.ps1 -OS windowsservercore-<VERSION>` to build and test your changes
1. - [x] Revert any modifications that were made to the 3.5/runtime Dockerfile to support local testing due to the lack of the https://dotnetbinaries.blob.core.windows.net/dockerassets/microsoft-windows.netfx3-<VERSION>.zip file.
1. - [x] Commit generated changes
1. - [x] Create PR
1. - [x] Get PR signoff. **Don't merge PR to master.**

## Release Day Tasks

1. - [x] Create a [`microsoft-windows.netfx3-<VERSION>.zip](https://github.com/microsoft/dotnet-framework-docker/blob/1c3dd6638c6b827b81ffb13386b924f6dcdee533/3.5/runtime/windowsservercore-1909/Dockerfile#L11) file containing the .NET Fx 3.5 cab installer file and upload it to the [blob storage location](https://dotnetbinaries.blob.core.windows.net/dockerassets).
1. - [x] Ensure all build agent scale sets have the appropriate number of machines allocated for a build
1. - [x] Merge any pending PRs or commits from `dev` branch:
      - [x] &lt;placeholder link&gt;
1. - [x] Look up the latest [NuGet CLI versions](https://www.nuget.org/downloads) and update the [nuget-info.json](https://github.com/microsoft/dotnet-framework-docker/blob/master/eng/nuget-info.json) file with the latest patch of each major/minor version listed in the file.
1. - [x] Run the `update-dependencies` tool to update all the necessary files:
      - [x] `dotnet run --project .\eng\update-dependencies --datestamp-all <YYYYMMDD>`
1. - [x] Inspect generated changes for correctness
1. - [x] Commit generated changes
1. - [x] Create PR
1. - [x] Get PR signoff
1. - [x] Merge PR
1. - [x] Wait for changes to be mirrored to internal [dotnet-framework-docker repo](https://dev.azure.com/dnceng/internal/_git/Microsoft-dotnet-framework-docker) (internal MSFT link)
1. - [x] Run the [`Get-BaseImageStatus.ps1`](https://github.com/microsoft/dotnet-framework-docker/blob/master/eng/common/Get-BaseImageStatus.ps1) script and wait until the Windows images have been updated as part of the Windows Patch Tuesday release process. This script will display when the dependent Windows images were last updated. Wait until all the images show that they have been recently updated. "Recently updated" amounts to be having been updated within the past week or so; images from a month ago should be considered to be the old version.

          ./eng/common/Get-BaseImageStatus.ps1 -Continuous
1. - [x] Queue build of [dotnet-framework-docker pipeline](https://dev.azure.com/dnceng/internal/_build?definitionId=372) (internal MSFT link). Path args: `src/*/windowsservercore-2009`
1. - [x] Confirm images have been ingested by MCR
1. - [x] Confirm READMEs have been updated in Docker Hub for [microsoft-dotnet-framework](https://hub.docker.com/_/microsoft-dotnet-framework)
1. - [x] Confirm build for [dotnet-docker-framework-samples](https://dev.azure.com/dnceng/internal/_build?definitionId=374) (internal MSFT link) was queued. This will be queued automatically by [dotnet-docker-tools-check-base-image-updates](https://dev.azure.com/dnceng/internal/_build?definitionId=536) when it detects that the product images have been updated (detection runs on a schedule). Alternatively, you can manually queue the samples build.
1. - [x] Confirm sample images have been ingested by MCR
1. - [x] Confirm `Last Modified` field has been updated in Docker Hub for [microsoft-dotnet-framework-samples](https://hub.docker.com/_/microsoft-dotnet-framework-samples/)
1. - [x] Deallocate any extra scale set build agent machines if necessary
1. - [x] Create an announcement (example: [Windows Server, version 1909](https://github.com/microsoft/dotnet-framework-docker/issues/448))

**Comment by ChrisMcKee** [comment]
Will this release contain the size reductions shown in https://devblogs.microsoft.com/dotnet/we-made-windows-server-core-container-images-40-smaller/ by any chance?

**Comment by MichaelSimons** [comment]
> Will this release contain the size reductions shown in https://devblogs.microsoft.com/dotnet/we-made-windows-server-core-container-images-40-smaller/ by any chance?

@ChrisMcKee - They were already released as part of [20H1](https://techcommunity.microsoft.com/t5/containers/windows-server-version-2004-now-available/ba-p/1419194).

**Comment by ChrisMcKee** [comment]
> > Will this release contain the size reductions shown in https://devblogs.microsoft.com/dotnet/we-made-windows-server-core-container-images-40-smaller/ by any chance?
> 
> @ChrisMcKee - They were already released as part of [20H1](https://techcommunity.microsoft.com/t5/containers/windows-server-version-2004-now-available/ba-p/1419194).

Ah right I was looking at these stats 
![image](https://user-images.githubusercontent.com/83597/95737481-a72c2480-0c7f-11eb-91d0-31083081aad1.png)
But the image for 4.8 runtime was 6.84gb, so I assumed it hadn't gone out. 
I've probably missed something in the docs.

**Comment by MichaelSimons** [comment]
The current `mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-2004` image is 5.22 GB.  Unfortunately this has grown substantially because of the Windows OS patching layer which is currently 1.54 GB.  The patching layer is part of the windowsservercore base OS image.

``` console
> docker history mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-2004
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
d01395ea8dc2        4 weeks ago         cmd /S /C \Windows\Microsoft.NET\Framework64…   369MB
<missing>           4 weeks ago         cmd /S /C #(nop)  ENV DOTNET_RUNNING_IN_CONT…   41kB
<missing>           4 weeks ago         cmd /S /C curl -fSLo patch.msu http://downlo…   674MB
<missing>           5 weeks ago         Install update 2004-amd64                       1.54GB
<missing>           10 months ago       Apply image 2004-RTM-amd64                      2.65GB
```

**Comment by ChrisMcKee** [comment]
@MichaelSimons Thanks; I'd pulled an earlier insider one and couldn't work out where all the extra disk was being used 👍  
Constantly chasing the dream of not having to push multiple gigs into ACR 😉 

Thanks again; at least I know I'm not doing something wrong 😁
