### ISSUE TITLE
Proposal: Remove the 4.8-3.5 tagging pattern

### ISSUE THREAD

**Issue by mthalman** [microsoft/dotnet-framework-docker#650]
The concept of the [4.8-3.5 tagging pattern](https://github.com/microsoft/dotnet-framework-docker/issues/70#issuecomment-620224647) was intended to provide more clarity around what versions of .NET Fx were installed in the 3.5 images.  There is still some question whether that goal has been accomplished and whether this tagging pattern is more understandable.

In addition, the `4.8-3.5` shared tag had to be discontinued because of the lack of good infrastructure support (https://github.com/microsoft/dotnet-framework-docker/issues/604).  So it's only used for the concrete tags at this point.

And while the tagging pattern is accurate in that both the 4.8 and 3.5 runtimes are installed in the image, it doesn't reflect the compatibility of those runtimes with other versions as mentioned in https://github.com/microsoft/dotnet-framework-docker/issues/629.

I propose that we remove this tagging pattern and instead just rely on documentation in the README to illustrate what we want to convey as far what versions are relevant to these tags.  I think the suggestion offered [here](https://github.com/microsoft/dotnet-framework-docker/pull/645#issuecomment-697918565) is a nice way to represent this.

**Comment by MichaelSimons** [comment]
Remaining work is to mark the 4.8-3.5 tags as undocumented in the manifest.  We will still update and produce them, but no longer include them in the tag listing of the readme.
