### ISSUE TITLE
no matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by backspacer80** [microsoft/dotnet-framework-docker#660]
I am not able to pull the .NET framework images from https://hub.docker.com/_/microsoft-dotnet-framework-samples/ for my machine. I keep getting error "no matching manifest for linux/amd64 in the manifest list entries." My machine is either windows/x86_64 or linux/x86_64 (I can switch between both using Docker Desktop). When I look into your manifest I find only amd64 is defined. Do you currently support only amd64 or is this a bug? 

### Steps to Reproduce

// Try run .NET Framework image
$ docker run --rm mcr.microsoft.com/dotnet/framework/samples:dotnetapp
Unable to find image 'mcr.microsoft.com/dotnet/framework/samples:dotnetapp' locally
dotnetapp: Pulling from dotnet/framework/samples
docker: no matching manifest for linux/amd64 in the manifest list entries.
See 'docker run --help'.

// What is my architecture?
$ docker info  -f '{{.OSType}}/{{.Architecture}}'
linux/x86_64

// What's inside the images' manifest?
$ docker manifest inspect mcr.microsoft.com/dotnet/framework/samples:dotnetapp
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2496,
         "digest": "sha256:34478bae28a835ce2983c7ac993b9cbf342a22e4f0bf6e42e62c223c4e999719",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.14393.3986"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2574,
         "digest": "sha256:ae4280b30da5c8d1ead13982222510801b400f0b128f94a794dbb4d3e57e5599",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.17763.1518"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2361,
         "digest": "sha256:e0dd30f1bec8119d892d84319e8a39b6fcf137d06340211f6e033b445f7ba73f",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.18362.1139"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2361,
         "digest": "sha256:6ff4832b32b5b79062141915780b577fc14a7164e77f932fde4e4527a42363e2",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.18363.1139"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2361,
         "digest": "sha256:5eef29bd5ebe13f07ed589b73a53bf8c343d87260f6ae654518cc7f06aace116",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.19041.572"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2147,
         "digest": "sha256:aef5131e96654ac1f71f58fbf41b4aff9aa0fcb0bec615d4201aa5ed980ea8c8",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.19042.572"
         }
      }
   ]
}

### Output of `docker version`

Docker version 19.03.13, build 4484c46d9d

### Output of `docker info`

$ docker info
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.4.2-tp-docker)

Server:
 Containers: 7
  Running: 2
  Paused: 0
  Stopped: 5
 Images: 11
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.922GiB
 Name: docker-desktop
 ID: ENYH:3THM:4TW2:KD3O:27YI:6WGQ:YAUV:RNPG:US27:MGIR:7V3U:E3KZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

**Comment by MichaelSimons** [comment]
@backspacer80, .NET Framework images can only be run in a Windows container environment.  From the `docker info` output you included, I can see you are running in a Linux container environment.  This is why you are seeing "no matching manifest for linux/amd64 in the manifest list entries".  The manifest does not contain any linux/amd64 entries.  It only includes windows/amd64 entries.  If you want to use the .NET Framework images you will have to run them from your windows/x86_64 configuration.  If you are looking to run .NET on Linux, please use the [.NET Core images](https://hub.docker.com/_/microsoft-dotnet/).
