### ISSUE TITLE
Can't not build the image

### ISSUE THREAD

**Issue by fengyinyong** [microsoft/dotnet-framework-docker#664]
I downloaded the asp.net mvc sample，and want to build a image according your tutorial。but it failed， and i can not find any way to solve it。
![image](https://user-images.githubusercontent.com/68414905/97954063-64bcba00-1ddd-11eb-80be-09290b81db77.png)

![image](https://user-images.githubusercontent.com/68414905/97954086-7ef69800-1ddd-11eb-8313-4002bb20c8c1.png)

**Comment by fengyinyong** [comment]
![1](https://user-images.githubusercontent.com/68414905/97954249-f2000e80-1ddd-11eb-955c-c5495c4541e8.png)

Step 9/12 : RUN msbuild /p:Configuration=Release
 ---> Running in 092a903a8f7b
The command 'powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; msbuild /p:Configuration=Release' returned a non-zero code: 1

**Comment by MichaelSimons** [comment]
@fengyinyong, I would suggest enabling verbose build output (e.g. `-v:diag`) and looking to see if there is an indication of what is causing the failure.  https://docs.microsoft.com/en-us/visualstudio/msbuild/obtaining-build-logs-with-msbuild?view=vs-2019.  If you don't see anything, save the output to a log file and post it here.

**Comment by fengyinyong** [comment]
@MichaelSimons
I can run the demo project in vs2019.
![image](https://user-images.githubusercontent.com/68414905/98063424-f9312600-1e8a-11eb-917e-bb89680b5c31.png)

and I also can build it in powershell:
![image](https://user-images.githubusercontent.com/68414905/98063653-70ff5080-1e8b-11eb-9541-51cb5156c32d.png)

But, I still can not build a image according the dockerfile you provided:
![image](https://user-images.githubusercontent.com/68414905/98063709-9f7d2b80-1e8b-11eb-8363-94c8449a3062.png)

Here is the demo I download:git clone https://github.com/microsoft/dotnet-framework-docker/

**Comment by MichaelSimons** [comment]
@fengyinyong, yes I was able to build the sample myself.  Have you verified a simple `msbuild` scenarios such as `docker run -it --rm mcr.microsoft.com/dotnet/framework/sdk:4.8 msbuild /?`?

**Comment by MichaelSimons** [comment]
@fengyinyong - Can you check to make sure you are not encountering this [issue](https://support.microsoft.com/en-us/help/4542617/you-might-encounter-issues-when-using-windows-server-containers-with-t)?  If that's the case, you will need to update/patch the version of windows running on your Docker host machine.

**Comment by MichaelSimons** [comment]
Closing as we believe this is an instance of this [issue](https://support.microsoft.com/en-us/help/4542617/you-might-encounter-issues-when-using-windows-server-containers-with-t).  If this turns out not to be the case, please let us know.
