### ISSUE TITLE
Unhandled exception. System.DllNotFoundException: Unable to load DLL or one of its dependencies: The specified module could not be found. (0x8007007E)

### ISSUE THREAD

**Issue by ydan87** [microsoft/dotnet-framework-docker#682]
### Describe the Bug
Hello there,
I have a .NET core application that uses a library DLL called PortSip.
So far that application was hosted in an AWS EC2 with Windows Server 2019 and now I would like to examine the concept of Docker and how to activate my application inside such container.

So I have created an image, using the following Dockerfile:
```
# escape=`

# .NET Core image to copy that stuff
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-nanoserver-1903 as dotnet

# Windows Server image with .NET Framework image as base
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019

# copy the .NET Core stuff from the .NET Core Image to the Windows Server Image
ENV DOTNET_PATH="C:\Program Files\dotnet" 
COPY --from=dotnet ${DOTNET_PATH} ${DOTNET_PATH}

# set environment path with .NET Core
RUN $env:PATH = $env:DOTNET_PATH + ';' + $env:PATH; `
    [Environment]::SetEnvironmentVariable('PATH', $env:PATH, [EnvironmentVariableTarget]::Machine)

SHELL ["powershell"]

# Install C++ Redistributable
RUN Invoke-WebRequest "https://aka.ms/vs/16/release/vc_redist.x64.exe" -OutFile "$env:TEMP\vc_redist.x64.exe" -UseBasicParsing
RUN & "$env:TEMP\VC_redist.x64.exe" /install /quiet | Out-Default
RUN & rm "$env:TEMP\vc_redist.x64.exe"

RUN Invoke-WebRequest "https://aka.ms/highdpimfc2013x64enu" -OutFile "$env:TEMP\vc_redist_13.x64.exe" -UseBasicParsing
RUN & "$env:TEMP\vc_redist_13.x64.exe" /install /quiet | Out-Default
RUN & rm "$env:TEMP\vc_redist_13.x64.exe"

# Install Visual Studio Community
RUN Invoke-WebRequest "https://aka.ms/vs/16/release/vs_community.exe" -OutFile "$env:TEMP\vs_community.exe" -UseBasicParsing
RUN & "$env:TEMP\vs_community.exe" --add Microsoft.VisualStudio.Workload.ManagedDesktop --add Microsoft.VisualStudio.Workload.Azure --add Microsoft.VisualStudio.Workload.NetWeb --add Microsoft.VisualStudio.Workload.CoreEditor --add Microsoft.VisualStudio.Workload.NativeDesktop --add Microsoft.VisualStudio.Workload.NetCoreTools --add Microsoft.VisualStudio.Workload.Universal --add Microsoft.VisualStudio.Workload.VisualStudioExtension --add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools --add Microsoft.VisualStudio.Workload.MSBuildTools --add Microsoft.VisualStudio.Workload.NetCoreBuildTools --add Microsoft.VisualStudio.Workload.UniversalBuildTools --add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Workload.VisualStudioExtensionBuildTools --add Microsoft.VisualStudio.Workload.WebBuildTools --add Microsoft.Net.Component.4.7.2.SDK --add Microsoft.Net.Component.4.7.1.SDK --add  Microsoft.Net.Component.4.7.SDK --add Microsoft.VisualStudio.Component.VC.Redist.MSM --quiet --wait --norestart --noUpdateInstaller | Out-Default

# Set working dir
WORKDIR /app
COPY ./netcoreapp3.1/ ./
RUN & "C:\app\vc_redist_12.x64.exe" /install /quiet | Out-Default
RUN & rm "C:\app\vc_redist_12.x64.exe"

# Restore the default Windows shell for correct batch processing.
SHELL ["cmd"]
RUN "C:\Program Files\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" /version

# Run this on startup
WORKDIR /app
CMD ["dotnet", "ServerApp.dll"]
```
Please note that the resulted image has both .NET core 3.1 and .NET framework 4.8 since I need them both. Also, note that I've also tried to install vc++ redistributable in different versions (for VS 2012, VS2013 and VS2015 to VS2019) and even installed Visual Studio community 2019 to have as much components installed as possible (It's almost 30GB image!).

However when I run this image, I get the following:
`Unhandled exception. System.DllNotFoundException: Unable to load DLL 'portsip.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)`

The DLLs are surely there, and the exact same steps and installation in an EC2 instance made that work, as well as locally in my laptop.
What am I missing?

### Output of `docker version`
Client: Docker Engine - Community
 Cloud integration: 1.0.2
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:00:27 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:14:20 2020
  OS/Arch:          windows/amd64
  Experimental:     false

### Output of `docker info`
Client:
 Debug Mode: false
 Plugins:
  scan: Docker Scan (Docker Inc., v0.3.4)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 21
 Server Version: 19.03.13
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 18363 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Enterprise Version 1909 (OS Build 18363.1198)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.86GiB
 Name: ES-DANIELYA-L10
 ID: AMKH:PKUG:E46Y:7NU3:HN53:3GSS:26CM:F25Z:MZL2:7B4L:TP55:UVJN
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

Thanks in advance

**Comment by MichaelSimons** [comment]
@ydan87, I see you have also logged the same [issue](https://github.com/dotnet/dotnet-docker/issues/2416) in the dotnet/dotnet-docker repo as well.  Let's use that one to try to resolve your issue since it was opened first.  I'm going to close this one as a duplicate.
