### ISSUE TITLE
Administrator password

### ISSUE THREAD

**Issue by Osbern** [Microsoft/dotnet-framework-docker#7]
I need the administrator password for launching a WCF host console (service crash when trying to open port because run as non-admin). But the administrator password is neither mention in the documentation of the dotnet-framework image nor in the  windowsservercore image.

Where can I find this default password ?

**Comment by kendrahavens** [comment]
@Osbern Not sure if you are still having this issue, but you may try running with the privileged flag.
`docker run --privileged `...

**Comment by kendrahavens** [comment]
Closing if no further discussion is needed. Thank you for logging this and please let us know if this is still an issue.
