### ISSUE TITLE
Add support for SSDT inside SDK docker images

### ISSUE THREAD

**Issue by xavokill** [microsoft/dotnet-framework-docker#732]
### Describe the Problem

Inside a Docker build process in which some _dotnet-framework-docker-sdk_ base image  is used the MSBUILD build task fails due to missing SSDT components.

In this sample **Database.sln** contains a single database project (*.sqlproj)

`
RUN msbuild "Database.sln" /p:configuration=release
`

Throws this error:

`The imported project Microsoft.Data.Tools.Schema.SqlTasks.targets was not found`

### Describe the Solution

During installation of "vs_BuildTools" add **DataBuildTools** workload to install SSDT components and its recommended items.

`
  --add Microsoft.VisualStudio.Workload.DataBuildTools;includeRecommended 
`

**Comment by MichaelSimons** [comment]
[Triage] We haven't received many requests for this.  We have refrained from adding workloads for non-mainline scenarios.  Adding all possible workloads bloat the images and make them less attractive for the majority of users.  Our recommendation is to create your own custom images based on the .NET Fx SDK image and add the workloads you need.  Here is an [example](https://github.com/microsoft/dotnet-framework-docker/issues/693#issuecomment-742855442) that adds DataBuildTools.
