### ISSUE TITLE
Add build images for ASP.NET projects

### ISSUE THREAD

**Issue by sixeyed** [Microsoft/dotnet-framework-docker#74]
The `microsoft/dotnet-framework-build` images are great, but it would be good to add a set for building web projects, targeting relevant .NET framework versions.

Currently users can build their own on top of these images by adding WebDeploy and the web build workload, but it would be nice to have official versions.

Sample for .NET 3.5:

```
# escape=`
FROM microsoft/dotnet-framework-build:3.5-windowsservercore-ltsc2016 AS builder
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# Install web workload
RUN Invoke-WebRequest -UseBasicParsing https://download.visualstudio.microsoft.com/download/pr/100196686/e64d79b40219aea618ce2fe10ebd5f0d/vs_BuildTools.exe -OutFile vs_BuildTools.exe; `
    Start-Process vs_BuildTools.exe -ArgumentList  '--add', 'Microsoft.VisualStudio.Workload.WebBuildTools', '--quiet', '--norestart', '--nocache' -NoNewWindow -Wait

# Install WebDeploy
RUN Install-PackageProvider -Name chocolatey -RequiredVersion 2.8.5.130 -Force; `
    Install-Package -Name webdeploy -RequiredVersion 3.6.0 -Force
```

**Comment by bariscaglar** [comment]
There's https://github.com/Microsoft/aspnet-docker and https://github.com/Microsoft/wcf-docker images. Would these work or do these need more to be more functional?

**Comment by MichaelSimons** [comment]
There are plans to support ASP.NET projects - see https://github.com/Microsoft/aspnet-docker/issues/63.  The plan is to add the web components within an microsoft/aspnet-build image that is based on the microsoft/dotnet-framework-build images.

**Comment by sixeyed** [comment]
Thanks @MichaelSimons - that works for me. Any idea of timeframes? :)

**Comment by MichaelSimons** [comment]
This is something we are actively working on.

Closing in lieu of Microsoft/aspnet-docker#63.
