### ISSUE TITLE
Powershell commands doesn't work

### ISSUE THREAD

**Issue by flmf3005** [microsoft/dotnet-framework-docker#744]
When I build an image from  mcr.microsoft.com/dotnet/framework/aspnet:4.8 (latest), some commands from powershell doesn't work.

DockerFile:

FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8-20210112-windowsservercore-ltsc2019
MAINTAINER fernando
#Cria os aplications pools
RUN powershell -command \
    New-WebAppPool -Name sqbi ; \
    New-WebAppPool -Name sqbi-service ;\
    #Cria as pastas utilizadas pelas aplicações
    New-Item -Path 'C:\inetpub\wwwroot' -Name sqbi -ItemType Directory ; \
    New-Item -Path 'C:\inetpub\wwwroot\sqbi' -Name Senior.ServiceFramework.Controller -ItemType Directory ; \
    New-Item -Path 'C:\inetpub\wwwroot\sqbi' -Name Senior.SBS.UI -ItemType Directory ; \
    #Cria e configura as aplicacoes WEB e Virtual Dir
    New-WebApplication -Name sqbi -Site 'Default Web Site' -PhysicalPath C:\inetpub\wwwroot\sqbi -ApplicationPool sqbi ; \
    New-WebApplication -Name sqbi-service -Site 'Default Web Site' -PhysicalPath C:\inetpub\wwwroot\sqbi\Senior.ServiceFramework.Controller -ApplicationPool sqbi-service ; \
    New-WebVirtualDirectory -Site 'Default Web Site' -Application sqbi -Name UI -PhysicalPath C:\inetpub\wwwroot\sqbi\Senior.SBS.UI ; \
    $pool  = Get-ChildItem IIS:\AppPools | where { $_.name -eq  'sqbi'} | Select-Object -First 1 ; \
    $pool.managedPipelineMode = 'Classic' ; \
    $pool | Set-Item ; \
    #Nessário atribuir permissao para everyone para execucao do site
    $sharepath = 'C:\inetpub\wwwroot' ;\
    $Acl = Get-ACL $SharePath ; \
    $AccessRule= New-Object System.Security.AccessControl.FileSystemAccessRule('everyone','FullControl','ContainerInherit,Objectinherit','none','Allow') ; \
    $Acl.AddAccessRule($AccessRule) ; \
    Set-Acl $SharePath $Acl ; \
    Start-Service aspnet_state
EXPOSE 80
ENTRYPOINT powershell

Error:
'Select-Object' is not recognized as an internal or external command,operable program or batch file.

To temporarily fix this problem I used the mcr.microsoft.com/dotnet/framework/aspnet:4.8-20210113-windowsservercore-1909, without the latest update.

**Comment by MichaelSimons** [comment]
[Triage] Closing - see @mthalman's suggested fix.
