### ISSUE TITLE
mcr.microsoft.com error pulling aspnet image

### ISSUE THREAD

**Issue by dave-yotta** [microsoft/dotnet-framework-docker#750]
CI got this over the weekend - this probably isn't the right place to report this, but I'm out of ideas - I guess you'll have to forward this to your azure service provider there 🤔 (I tried looking for past incidents in the azure status page, but couldn't find it...)

#3 ERROR: failed to copy: httpReadSeeker: failed open: unexpected status code https://mcr.microsoft.com/v2/dotnet/core/aspnet/blobs/sha256:fe3a4716eba4304fdb3b6a63fd0e54aa9c6c8519f9d1ba2f67a043679dd2f64a: 500 Internal Server Error

**Comment by mthalman** [comment]
Issue moved to [microsoft/containerregistry #56](https://github.com/microsoft/containerregistry/issues/56) via [**ZenHub**](https://www.zenhub.com/)
