### ISSUE TITLE
Docker image sets NUGET_XMLDOC_MODE=skip, disrupting nuget restore

### ISSUE THREAD

**Issue by aaronla-ms** [microsoft/dotnet-framework-docker#760]
### Describe the Bug

The docker image https://hub.docker.com/_/microsoft-dotnet-framework-sdk/?tab=reviews sets environment variable NUGET_XMLDOC_MODE=skip. This negatively impacts nuget restore, causing certain package files to fail to restore properly. 

While this setting may be useful in your build process during creation of the nuget package, it negatively impacts users of the docker image that may not be aware of this non-default setting. Our build infrastructure used this nuget image as an image for our build agents, and it's causing our builds to fail due to missing files in the nuget restore.

While I do know how to override this setting, I consider this a temporary work around. Nuget images shouldn't leak their build settings into the image produced, and should instead clean up the environment for the user's uses when finalizing the docker image. The only environment variables set in the final image should be (a) those built into the OS it's using (e.g. having a username set, program files, etc.) and (b) those necessary for the container's intended function (e.g. WindowsSdkDir, and other things a Developer Command Prompt for VS 2019 might set).

### Steps to Reproduce

in the linked docker container, run `echo NUGET_XMLDOC_MODE='%NUGET_XMLDOC_MODE%'`

[expected]: NUGET_XMLDOC_MODE=''
[actual]: NUGET_XMLDOC_MODE='skip'

**Comment by mthalman** [comment]
The [.NET Framework SDK images](https://hub.docker.com/_/microsoft-dotnet-framework-sdk) do not define this environment variable.  But the [.NET Core SDK images](https://hub.docker.com/_/microsoft-dotnet-sdk) do. Did you mean to reference .NET Core instead?  If so, this should be logged in https://github.com/dotnet/dotnet-docker.

**Comment by aaronla-ms** [comment]
Thanks, it looks like my build engineer pointed me at the wrong image. Will follow up at the link you provided!

**Comment by aaronla-ms** [comment]
Filed in error against wrong docker image. Corrected with new issue https://github.com/dotnet/dotnet-docker/issues/2790
