### ISSUE TITLE
Install F# 4 in the mcr.microsoft.com/dotnet/framework/sdk:4.8 image

### ISSUE THREAD

**Issue by ryanewtaylor** [microsoft/dotnet-framework-docker#762]
### Describe the Problem

F# 5 is available, however, I am unable to reference .NET Framework only assemblies from F#. 

### Describe the Solution

Install the full F# 4.x (Framework version)in the image as is done with C# and VB.NET.

**Comment by MichaelSimons** [comment]
[Triage]  This is the first ask for full F# support.  How many customers want this?  Adding every possible component would make the sdk image that much bigger and less attractive.  We try to adhere to only adding mainline components. For non-mainline scenarios, our recommendation is to add the missing required components on top of the 'sdk' image in your own layer/image.

If you would like to see us add full f# 4.x support, please let us know.  If we don't receive much response, we will close this issue in one month.

**Comment by ryanewtaylor** [comment]
I am okay with adding this in my own layer/image. However I am having trouble doing so. I have documented my attempts here which have so far been unsuccessful. Any suggestions?

https://stackoverflow.com/q/67479997/19977

**Comment by ryanewtaylor** [comment]
I found a solution that works for me and I am okay with closing this request. In short, I was able to solve the issue by installing the F# Compiler Tools using paket.

https://stackoverflow.com/a/67641441/19977

**Comment by MichaelSimons** [comment]
[Triage] Closing as there were no other requests for this and a solution was found for the original scenario.
