### ISSUE TITLE
[internal] load metadata for mcr.microsoft.com/dotnet/framework/sdk:4.8

### ISSUE THREAD

**Issue by stevchen99** [microsoft/dotnet-framework-docker#768]
hallo,

i got this error:
#1 [internal] load build definition from Dockerfile
#1 sha256:01bba10c6c079c689c2c0060817b7de826af14ef296547bd3d3ed56f730bfae1
#1 transferring dockerfile: 32B 0.0s done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:8a5d5635bab36f25b82547879d5f297396ba23ccaebc40d4c739e53658a67719
#2 transferring context: 34B 0.0s done
#2 DONE 0.0s

#3 [internal] load metadata for mcr.microsoft.com/dotnet/framework/sdk:4.8
#3 sha256:a65c83e65a8e948de5cf54dae52e5acbe4db998d579d44a77a2fcfc68bfc5527
#3 ERROR: no match for platform in manifest sha256:f72014f02b2ba7e624e0097bc282c2a7d3c77691ef9cf145df5cf94088a491fa: not found
------
 > [internal] load metadata for mcr.microsoft.com/dotnet/framework/sdk:4.8:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:f72014f02b2ba7e624e0097bc282c2a7d3c77691ef9cf145df5cf94088a491fa: not found

**Comment by mthalman** [comment]
What does your Dockerfile look like?

Can you provide the output of `docker info` and `docker version`?

**Comment by stevchen99** [comment]
i found the solution, just switch from linux to windows Container. the error message is not clear. i know that Framework 4.8 only work on windows not on linux.
