### ISSUE TITLE
Consider updating Roslyn binaries

### ISSUE THREAD

**Issue by richlander** [microsoft/dotnet-framework-docker#774]
I noticed that the Roslyn package we use is super old.

https://github.com/microsoft/dotnet-framework-docker/blob/66cfc9536db13fa27b82c2bc33fd916e5f583366/eng/dockerfile-templates/aspnet/Dockerfile#L18

We're using a version from 2018. https://www.nuget.org/packages/Microsoft.Net.Compilers/

This package should probably get updated every time we release (as a checklist item). I'd recommend looking at all the content we curl down. It looks like there are some other assets that might be stale.

/cc @jaredpar

**Comment by mthalman** [comment]
cc @HongGit

**Comment by MichaelSimons** [comment]
[Triage] @HongGit, can you please make a PR for this?

**Comment by Benjie-Liu** [comment]
#786
