### ISSUE TITLE
docker sample not working at build : failed to solve with frontend dockerfile.v0

### ISSUE THREAD

**Issue by cristian2422** [microsoft/dotnet-framework-docker#775]
i´m trying to build this sample app but it does not work at build it 
https://github.com/microsoft/dotnet-framework-docker/tree/main/samples/aspnetapp   

**error**:   

aspnetmvcapp> docker build --pull -t aspnetapp .   
[+] Building 1.7s (3/3) FINISHED   
 => [internal] load build definition from Dockerfile                                                                                                                     0.0s   
 => => transferring dockerfile: 552B                                                                                                                                  0.0s   
 => [internal] load .dockerignore                                                                                                                                     0.0s   
 => => transferring context: 2B                                                                                                                                       0.0s   
 => ERROR [internal] load metadata for mcr.microsoft.com/dotnet/framework/aspnet:4.8                                                                                       1.6s    
------    
 > [internal] load metadata for mcr.microsoft.com/dotnet/framework/aspnet:4.8:    
------    
**failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:401127068472cedcac4a9aa3684611e50a790eae18eac8246b50fb39e9eb0c95: not found**    
   
**steps**:    

1download this sample:    
https://github.com/microsoft/dotnet-framework-docker/tree/main/samples/aspnetapp   

2go to filder path
3try to create a image docker build --pull -t aspnetapp .
4get above failure.

side information:
--------------------
i have windows 10 version 21H1 (OS Build 19043.985) 
I can build and run other projects using .net core but it doesn´t using you sample with .net framework.  (asp.net MVC).
it fails with any project i create and trying to use your dockerfile sample  it fails at FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8 AS build

whole dockerfile is :   

FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8 AS build

WORKDIR /app

### copy csproj and restore as distinct layers
COPY *.sln .
COPY aspnetmvcapp/*.csproj ./aspnetmvcapp/
COPY aspnetmvcapp/*.config ./aspnetmvcapp/
RUN nuget restore

### copy everything else and build app
COPY aspnetmvcapp/. ./aspnetmvcapp/
WORKDIR /app/aspnetmvcapp
RUN msbuild /p:Configuration=Release -r:False

FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8 AS runtime
WORKDIR /inetpub/wwwroot
COPY --from=build /app/aspnetmvcapp/. ./

**Comment by MichaelSimons** [comment]
The .NET images don't support pre-release versions of 21H1.  Once it is RTM, images will be added.

@mthalman, is there any guidance for people who want to build their own 21H1 images?

**Comment by mthalman** [comment]
I don't think the host version is the issue here.  I'm running 21H1 and this works fine for me.  Docker for Windows will successfully pull the image for the highest available Windows version, in this case 20H2, when using a multi-arch tag like `4.8`.  I believe this is likely a matter of not having Docker Desktop configured to target Windows containers (see [related issue](https://github.com/microsoft/dotnet-framework-docker/issues/776) that was logged by @cristian2422 as well).

**Comment by cristian2422** [comment]
thank you all for your quick turnaround .  i will "switch to windows container" my docker desktop and give it a try...     
all i want is get it running locally in my windows10 host...   
https://github.com/microsoft/dotnet-framework-docker/tree/main/samples/aspnetapp   

any additional suggestion would be appreciated.  thanks for your support.

**Comment by MichaelSimons** [comment]
[Triage] Yes, please switch to Windows Containers.  Closing as this is the expected workflow but please let us know if you got the sample to work.
