### ISSUE TITLE
docker: no matching manifest for linux/amd64 in the manifest list entries.  when using asp.net MVC project (.net framework)

### ISSUE THREAD

**Issue by cristian2422** [microsoft/dotnet-framework-docker#776]
from here:https://hub.docker.com/_/microsoft-dotnet-framework 

if i run this test locally 
**docker run -it --rm -p 8000:80 --name aspnet_sample mcr.microsoft.com/dotnet/framework/samples:aspnetapp**

**i get this failure:**

\aspnetmvcapp> docker run -it --rm -p 8000:80 --name aspnet_sample mcr.microsoft.com/dotnet/framework/samples:aspnetapp
Unable to find image 'mcr.microsoft.com/dotnet/framework/samples:aspnetapp' locally
aspnetapp: Pulling from dotnet/framework/samples
docker: no matching manifest for linux/amd64 in the manifest list entries.
See 'docker run --help'.

i have windows 10
docker destktop installed
i can work/build other images or samples in .net core. 
i can not create images ussing .net framework form Dockefile. 

**any help to get around this error ?**

**Comment by mthalman** [comment]
> docker: no matching manifest for linux/amd64 in the manifest list entries.

This implies that your Docker Desktop is configured to target Linux containers.  There are no .NET Framework images available for Linux because .NET Framework only runs on Windows.  Are you wanting to use [.NET Core/.NET 5](https://hub.docker.com/_/microsoft-dotnet) instead?

**Comment by cristian2422** [comment]
> > docker: no matching manifest for linux/amd64 in the manifest list entries.
> 
> This implies that your Docker Desktop is configured to target Linux containers. There are no .NET Framework images available for Linux because .NET Framework only runs on Windows. Are you wanting to use [.NET Core/.NET 5](https://hub.docker.com/_/microsoft-dotnet) instead?     

Yes, actually i wanted to run and test it using .net framework . maybe i can right click on "docker desktop " and "switch to windows containers "  but not sure if that would be a solution to get it working.      
all i want is run this locally from my windows 10 machine .      
docker run -it --rm -p 8000:80 --name aspnet_sample mcr.microsoft.com/dotnet/framework/samples:aspnetapp

**Comment by MichaelSimons** [comment]
[Triage] Duplicate issue of #775
