### ISSUE TITLE
Consider merging .NET Framework Runtime and Builder Docker repos

### ISSUE THREAD

**Issue by richlander** [Microsoft/dotnet-framework-docker#78]
We recently produced [builder images](https://hub.docker.com/r/microsoft/dotnet-framework-build/) for .NET Framework. Folks have been asking for those images for a long time, so that's good. We chose to add docker source assets for the builder images within this GitHub repo. Conversely, we chose to create a different Docker repo than the [.NET Framework runtime repo](https://hub.docker.com/r/microsoft/dotnet-framework/) for image assets. This is the same model as [microsoft/aspnetcore-build](https://hub.docker.com/r/microsoft/aspnetcore-build/).

For .NET Core, we chose a differently model, to share the same [Docker repo](https://hub.docker.com/r/microsoft/dotnet/) and [GitHub repo](https://github.com/dotnet/dotnet-docker) for both the runtime and builder/SDK images.

We decided to talk about this asymmetry in our approaches. Here are our take-aways:

**Pros on using a single Docker repo for runtime + builder (SDK) assets:**

* Most of our samples use multi-stage-build, which then pull from a single repo. That's simpler.
* Forces a single tag scheme.
* Any difference in support (like chip or OS) between runtime and builder is obvious.
* Builder and SDK together results in higher pull counts on a single repo, which pushes a given repo higher in the ranking in various [Docker views](https://hub.docker.com/u/microsoft/) where pull count is important. This isn't a vanity thing but a way of rising above the crowd around us. 
* For .NET Core, we think of the SDK as the "getting started" distro while we seem to think of the Runtime as the "getting started" distro for .NET Framework. This leads to potential discontinuity in naming across .NET Core and .NET Framework if we we were to have separate runtime and builder repos with only one of them getting the "good" short name.

**Pros on separate Docker repos:**

* Smaller set of tags offered per repo, but the same set of tags to learn in aggregate.
* More focused meaning of a Docker repo, meaning a smaller set of tags to search through for a given repo.

A major take-away is that the microsoft/dotnet repo has been highly successful. By pull counts, it is far and away the most popular of our repos, with almost 10x pull traffic relative to the next .NET Docker repo. We think that this is in part due to the whole (runtime and SDK) of .NET Core being available in one place. Effectively, we nailed the discoverability problem. We're now wondering if we should do the same thing with microsoft/dotnet-framework, that is make the SDK/builder images available there as well. We want to make .NET Docker use/adoption easier and more convenient. Will this help with that?

We'd like your feedback.

**Comment by stevedesmond-ca** [comment]
Docker tags are similar to SVN tags in that there are conventions around how they should be used, but no hard rules -- a tag can be something completely arbitrary and not related to the project at all. Contrast this with git tags, which have a very specific purpose: naming a point in history of a repo. I like to think of Docker tags more like git tags, naming a point in history of a project (in this case, a release).

I've definitely seen both suggestions in the wild, for both having different tags/repos for builds with different base OS images, and having different tags/repos for different feature subsets / configurations (like we're talking about here).

My opinion as a more experienced Docker user is, if the builder and runtime images are intended for fundamentally different purposes (and I believe they are), they should live in different repos.

**Comment by richlander** [comment]
Here's another good example: https://hub.docker.com/_/openjdk/. It uses the same model as the .NET Core repo.

> My opinion as a more experienced Docker user is, if the builder and runtime images are intended for fundamentally different purposes (and I believe they are), they should live in different repos.

This is part of the rub. In the cases of both .NET Framework and .NET Core, the SDK/builder image contains the runtime, too, so it offers a superset of scenarios, not a disjoint set. I assume that this is the same with Java as well.

**Comment by richlander** [comment]
I have been thinking more about this. If we do this, the naive approach would be to add a new `build` tag as a direct translation of the `microsoft/dotnet-framework-builder` repo. The `build` tag would behave much like the `sdk` tag we use in the microsoft/dotnet repo. But then, why wouldn't we re-use the `sdk` tag instead? That seems accurate and would make it easier to talk about .NET Framework and .NET Core repos.

The only downside is that the current  `microsoft/dotnet-framework-builder` images don't contain the .NET Framework SDK (certainly not in its entirety). I'd say that any .NET Framework SDK tool that is relevant for use in Docker is fair game for being pulled in.

**Comment by stevedesmond-ca** [comment]
I like what PHP has done around your last point, by providing a Docker-specific way to consistently and easily install extensions -- check out the `docker-php-ext-install`section [here](https://hub.docker.com/_/php/) -- this keeps the base image smaller and (a benefit in my opinion) leads to explicitly stating those types of dependencies.

**Comment by richlander** [comment]
That makes sense. For our platform, we don't have the extensions in a package manager, like NuGet. So, I don't see a good path forward to enable the proposal.

**Comment by MichaelSimons** [comment]
The repos were merge with https://github.com/Microsoft/dotnet-framework-docker/pull/123.
