### ISSUE TITLE
Cleanup Docker assets in CI

### ISSUE THREAD

**Issue by ravimeda** [Microsoft/dotnet-framework-docker#79]
Repro:

1. Submit a PR
2. Wait for CI to finish

_Actual_: Docker assets (containers, images) are  not cleaned up.

_Expected_: Docker assets produced during the check should be cleaned up always.  This means cleanup whether the test gracefully exits or hits an exception.
CI invokes `build-and-test.ps1` (https://github.com/Microsoft/dotnet-framework-docker/blob/master/build-and-test.ps1). Add a cleanup logic in this script. Refer to https://github.com/dotnet/dotnet-docker-nightly/issues/529

**Comment by MichaelSimons** [comment]
Adding the cleanup logic to CI and updating the build to use the build-and-test script should be logged as two different issues.  They have different priority and don't need to be done together.  Adding the cleanup logic to CI is important as it is causing issues on the CI machines.  Updating the build to use build-and-test is a 'nice to have'.

**Comment by ravimeda** [comment]
Let's focus this issue on cleanup in CI.  A separate issue was logged to update official build steps.

**Comment by ravimeda** [comment]
Official build step improvement is logged as https://github.com/Microsoft/dotnet-framework-docker/issues/82
