### ISSUE TITLE
Issue while pulling "microsoft/dotnet-framework:3.5-windowsservercore-1709" image

### ISSUE THREAD

**Issue by ThomasMouret** [Microsoft/dotnet-framework-docker#84]
Hello everyone,

I have an issue while I want do pull "microsoft/dotnet-framework:3.5-windowsservercore-1709" Image.
I have tried to pull the image from 3 differents computer and I still have the same Issue :

PS C:\Windows\system32> docker pull microsoft/dotnet-framework:3.5-windowsservercore-1709
3.5-windowsservercore-1709: Pulling from microsoft/dotnet-framework
5847a47b8593: Pull complete
9f887ccb8077: Pull complete
6f01d475c669: Extracting [==================================================>]  331.7MB/331.7MB
c10fd66f80df: Download complete
64761d42b426: Download complete
failed to register layer: re-exec error: exit status 1: output: time="2018-01-29T15:21:44Z" level=error msg="hcsshim::ImportLayer failed in Win32: The system cannot find the file specified. (0x2) layerId=\\\\?\\C:\\ProgramData\\Docker\\windowsfilter\\1002394cad81a62abcc5fd3bf8561c93da7d3ebbf542918e5286e0cc74e47d1a flavour=1 folder=C:\\Windows\\TEMP\\hcs214503879"
hcsshim::ImportLayer failed in Win32: The system cannot find the file specified. (0x2) layerId=\\?\C:\ProgramData\Docker\windowsfilter\1002394cad81a62abcc5fd3bf8561c93da7d3ebbf542918e5286e0cc74e47d1a flavour=1 folder=C:\Windows\TEMP\hcs214503879

Pulling "microsoft/windowsservercore:1709" works:
PS C:\Windows\system32> docker pull microsoft/windowsservercore:1709
1709: Pulling from microsoft/windowsservercore
5847a47b8593: Pull complete
9f887ccb8077: Pull complete
Digest: sha256:895ff031c39003a474365b9326dfa95b8f689434f16573943fcc38abed1d3a9b
Status: Downloaded newer image for microsoft/windowsservercore:1709

Pulling "microsoft/dotnet-framework:3.5-windowsservercore-ltsc2016" also works:
PS C:\Windows\system32> docker pull microsoft/dotnet-framework:3.5-windowsservercore-ltsc2016
3.5-windowsservercore-ltsc2016: Pulling from microsoft/dotnet-framework
3889bb8d808b: Pull complete
449343c9d7e2: Pull complete
f5deee6e1b63: Pull complete
153fdc43d57d: Pull complete
bfeb4c571e9e: Pull complete
Digest: sha256:3e3523155044acaaa6a848104c9fcf1ccd3d4f706a8549cf020174217f20a93e
Status: Downloaded newer image for microsoft/dotnet-framework:3.5-windowsservercore-ltsc2016

Thanks for your help

Best regards
Thomas

**Comment by ravimeda** [comment]
Thomas, please could you provide the output of `docker info` and `docker version` commands.  This will allow me to reproduce the issue locally, and help investigate.

**Comment by ThomasMouret** [comment]
Hello Ravimeda,

Please find below the output asked,

```
PS C:\Users\Administrat0r> docker info
Containers: 9
 Running: 0
 Paused: 0
 Stopped: 9
Images: 33
Server Version: 17.06.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.2035.amd64fre.rs1_release_inmarket.180110-1910)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 8GiB
Name: container
ID: CLBN:TDOV:6XRB:3X77:YGBL:22CL:OKHF:JVZN:CMLW:LUS6:H6MG:HYMH
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false 
```

```
PS C:\Users\Administrat0r> docker version
Client:
 Version:      17.06.0-dev
 API version:  1.34
 Go version:   go1.8.5
 Git commit:   e2ada66
 Built:        Thu Nov  2 23:37:13 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-dev
 API version:  1.34 (minimum version 1.24)
 Go version:   go1.8.5
 Git commit:   462d791
 Built:        Thu Nov  2 23:41:07 2017
 OS/Arch:      windows/amd64
 Experimental: false 

```
Best regards
Thomas

**Comment by ThomasMouret** [comment]
Hello, 
I think i have solved my problem.
An Image based on Windows server 1709 can not be run on Windows Server 2016 Datacenter.
I have succesfully pulled the Image on a new Server with Windows Server 1709

Could someone confirm this ?

Best regards
Thomas

**Comment by MichaelSimons** [comment]
@ThomasMouret - That is correct.  You can read about the Windows Container Version Compatibility [here](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility)
