### ISSUE TITLE
Windows License Activation failed in image aspnet:4.8

### ISSUE THREAD

**Issue by monderino** [microsoft/dotnet-framework-docker#855]
### Describe the Bug

I have several asp.net framework apps running in a kubernetes cluster. But since the last friday (19. Nov) on of these apps didn't start anymore because the licence check fails and the IIS process isn't started.

All applications are build on the same dockerfile, only the content (the app) is different.
This is my dockerfile:
![Screenshot 2021-11-24 at 14 32 31](https://user-images.githubusercontent.com/23459030/143248931-a6df85a5-5367-43e8-bb50-3296da293e26.png)

I checked the windows eventlog to see any difference and I could see that the licence check occur less in the running image.
Here in on the left site is the running image on the right site the image which isn't running.
![Screenshot 2021-11-24 at 14 30 07](https://user-images.githubusercontent.com/23459030/143249442-17e8fc7b-3523-4552-9c11-b388220d9415.png)
You can see in both the Software protection service is running, but on the right site the licence check failed.

I tried to get answers on stackoverflow as well, but unfortunately without success.
https://stackoverflow.com/questions/70081941/windows-license-activation-failed-in-mcr-microsoft-com-dotnet-framework-aspnet4

I'm afraid of that this maybe will happen also in my other applications. 

Thanks a lot for your help.

### Other Information

The images are build in a github action on the windows latest image.

**Comment by mthalman** [comment]
Issue moved to [microsoft/iis-docker #195](https://github.com/microsoft/iis-docker/issues/195) via [**ZenHub**](https://www.zenhub.com/)
