### ISSUE TITLE
Dockerfile links in Docker Hub are incorrect

### ISSUE THREAD

**Issue by MichaelSimons** [Microsoft/dotnet-framework-docker#9]
The Dockerfile links in the [README.md](https://github.com/Microsoft/dotnet-framework-docker/blob/master/README.md) are not defined correctly.  

```
-       [`4.6.2`, `latest` (*4.6.2/Dockerfile*)](4.6.2/Dockerfile)
-       [`3.5` (*3.5/Dockerfile*)](3.5/Dockerfile)
```

They are relative links which don't work when the README.md is displayed in [Docker Hub](https://hub.docker.com/r/microsoft/dotnet-framework/).  This results in 404s.  The README.md should be using absolute paths.

**Comment by shirhatti** [comment]
Thanks for catching that. I just fixed the links on DockerHub

**Comment by MichaelSimons** [comment]
IMO the version in the repo should be updated as well.  This should be considered the master copy which gets copied to Docker Hub.
