### ISSUE TITLE
aspnetapp: Pulling from dotnet/framework/samples docker: no matching manifest for linux/amd64 in the manifest list entries.

### ISSUE THREAD

**Issue by gelsonmascarenhas** [microsoft/dotnet-framework-docker#908]

**Comment by mthalman** [comment]
Looks like you're using Docker Desktop and targeting Linux containers. .NET Framework does not support Linux. Only .NET Core/.NET 5+ supports Linux. Be sure to [switch to Windows containers](https://docs.docker.com/desktop/windows/#switch-between-windows-and-linux-containers).

**Comment by gelsonmascarenhas** [comment]
Greetings Dear Sir,

Thanks for the prompt reply yesterday! Switched to windows container as per your advice but still having errors. Maybe its worth mentioning that the intended aspnet pod deployment is being done to AWS EKS from my laptop via AWS CLI.
I even used a Dockerfile(refer to the Ref-a below) for multi-arch meaning they pull either Windows or Linux containers depending on what mode is set in Docker Desktop for Windows, yet I still obtain errors such as(please refer to Ref-b). I mean all other images are working fine like nginx, apache and so on, its only aspnet giving issues.

Regards

-----------------------------------------------------------------------------------------------------------------------------------------------
Ref-a
# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY ../engine/examples ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "aspnetapp.dll"]

Ref-b
NAME                                                           READY   STATUS                       RESTARTS   AGE
pod/test-app-deployment-6b9d457f64-zdskf                       0/1     InvalidImageName             0          6s

NAME                                                           READY   STATUS                       RESTARTS   AGE
pod/test-app-deployment-76545f7b67-vz96v                       0/1     ImagePullBackOff             0          24m

NAME                                                           READY   STATUS                       RESTARTS   AGE
pod/test-app-deployment-5dc7ccf5b4-26j4b                       0/1     ErrImagePull                 0          11s

**Comment by mthalman** [comment]
The Dockerfile you've provided contains different tag references than the title of this issue references. The title of this issue referenced a .NET Framework image tag (dotnet/framework/samples) but the Dockerfile you just posted is referencing mcr.microsoft.com/dotnet/sdk. These are two different types of .NET products. This repo is the correct location for .NET Framework container images. But if you are having issues with mcr.microsoft.com/dotnet/sdk, please post to https://github.com/dotnet/dotnet-docker. And please provide detailed information in the issue you create. This issue originally only had a title which is not sufficient to receive thorough guidance on.
