### ISSUE TITLE
WCF Image with netNamedPipeBinding enabled in IIS

### ISSUE THREAD

**Issue by joymon** [microsoft/dotnet-framework-docker#912]
### Describe the problem 
I am trying to host net.pipe services inside wcf container to be consumed by another webHttp based service hosted in same container. 
The requirement is to port an existing .Net Framework application(15+years, half a million lines of code) hosted in IIS that uses net.pipe for hosting internal shared services.  

Currently, the WCF image is only having HTTP and net.tcp enabled. In order to host net.pipe below additional steps are required

- RUN Install-WindowsFeature -name NET-WCF-Pipe-Activation45
- RUN &$Env:windir\system32\inetsrv\appcmd set app 'Default Web Site/' /enabledProtocols:"http,net.tcp,net.pipe"

### Describe the Solution

Have a new image on top of existing wcf (proposed named: wcf-extended) that includes support for bindings such as net.pipe .Below are the commands to get net.pipe support.

- RUN Install-WindowsFeature -name NET-WCF-Pipe-Activation45
- RUN &$Env:windir\system32\inetsrv\appcmd set app 'Default Web Site/' /enabledProtocols:"http,net.tcp,net.pipe"

### Additional Context

I tried this already and the source is in [my repo wcf-netnamedpipe-container](https://github.com/dotnet-demos/wcf-netnamedpipe-container/blob/main/Dockerfile.base)

**Comment by mthalman** [comment]
[Triage] The intention is to provide a general purpose WCF image that satisfies the majority of scenarios. If this is a widely used configuration, we'd consider adding it. But at this point in time, this is the only feedback we've received for this configuration. If we get more feedback to add support for this, we'll revisit this topic. We'll leave this issue open for a month to gather any more feedback.

**Comment by joymon** [comment]
Thanks, @mthalman for the response. Since we are not blocked, it is fine to wait for more feedback.

**Comment by mthalman** [comment]
Closing this. Feel free to provide more feedback if there's interest in this.
