### ISSUE TITLE
Install 4.8.1 targeting pack

### ISSUE THREAD

**Issue by richlander** [microsoft/dotnet-framework-docker#981]
re: https://github.com/microsoft/dotnet-framework-docker/blob/935817b4df76d13b04f274d1349ec0aefb377d1f/src/sdk/4.8/windowsservercore-ltsc2022/Dockerfile#L75

**Comment by MichaelKetting** [comment]
@mthalman & @MichaelSimons Thanks for looking into this! 

Do you already have an estimate as to when the .net 4.8.1 Docker image will be available?

We're having some strange problems building our own version to tide us over until the official image is done, and it would be great to get a feel as to the progress you guys are making. That way, we can decide if it's reasonable to just wait it out or continue with getting our own version to work.

Thanks, Michael

**Comment by mthalman** [comment]
@MichaelKetting - This will be available next Tuesday as part of our monthly servicing release.

**Comment by MichaelKetting** [comment]
@mthalman That's great news. Thanks!
