### ISSUE TITLE
Incorrect nomenclature in README

### ISSUE THREAD

**Issue by shirhatti** [Microsoft/dotnet-framework-docker#99]
We incorrectly refer to Windows Server, Version 1709 as ~~Windows Server 2016 Version 1709~~.
We need to fix
- [ ] READMEs in this repo
- [ ] Product pages on DockerHub

**Comment by ravimeda** [comment]
`v` should be lowercase as in `Windows Server, version 1709`. Refer to https://docs.microsoft.com/en-us/windows-server/get-started/get-started-with-1709
